import { LyricLine } from "@/lib/types";

// Auto-generated by scripts/generate-lyrics.mjs for "Colors" by Flow.
// Words come from kuromoji (segmentation), wanakana (romaji), and Jisho
// (dictionary meanings) — spot-check before shipping, don't trust blindly.
export const colorsLyrics: LyricLine[] = [
  {
    "id": "l1",
    "start": 8.3,
    "end": 15.76,
    "tokens": [
      {
        "surface": "自分",
        "romaji": "jibun",
        "meaning": "myself; yourself; oneself; himself; herself",
        "pos": "noun"
      },
      {
        "surface": "を",
        "romaji": "wo",
        "meaning": "indicates direct object of action",
        "pos": "particle"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "空白",
        "skip": true
      },
      {
        "surface": "世界",
        "romaji": "sekai",
        "meaning": "the world; society; the universe",
        "pos": "noun"
      },
      {
        "surface": "さえ",
        "romaji": "sae",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "particle"
      },
      {
        "surface": "も",
        "romaji": "mo",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "particle"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "空白",
        "skip": true
      },
      {
        "surface": "変え",
        "romaji": "kae",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "verb"
      },
      {
        "surface": "て",
        "romaji": "te",
        "meaning": "hand; arm",
        "pos": "particle"
      },
      {
        "surface": "しまえ",
        "romaji": "shimae",
        "meaning": "to finish; to stop; to end; to put an end to; to bring to a close",
        "pos": "verb"
      },
      {
        "surface": "そう",
        "romaji": "sou",
        "meaning": "monk; priest",
        "pos": "adverb"
      },
      {
        "surface": "な",
        "romaji": "na",
        "meaning": "don't",
        "pos": "particle"
      }
    ],
    "translation": "I feel like I can change myself and even the world"
  },
  {
    "id": "l2",
    "start": 15.76,
    "end": 23.56,
    "tokens": [
      {
        "surface": "瞬間",
        "romaji": "shunkan",
        "meaning": "moment; instant; second",
        "pos": "noun"
      },
      {
        "surface": "は",
        "romaji": "ha",
        "meaning": "indicates sentence topic",
        "pos": "particle"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "空白",
        "skip": true
      },
      {
        "surface": "いつも",
        "romaji": "itsumo",
        "meaning": "always; all the time; at all times",
        "pos": "adverb"
      },
      {
        "surface": "すぐ",
        "romaji": "sugu",
        "meaning": "immediately; at once; right away; directly",
        "pos": "adverb"
      },
      {
        "surface": "そば",
        "romaji": "soba",
        "meaning": "buckwheat (Fagopyrum esculentum)",
        "pos": "noun"
      },
      {
        "surface": "に",
        "romaji": "ni",
        "meaning": "two; 2",
        "pos": "particle"
      },
      {
        "surface": "...",
        "romaji": "...",
        "meaning": "one; 1",
        "pos": "noun"
      }
    ],
    "translation": "The moment is always right next to you..."
  },
  {
    "id": "l3",
    "start": 23.56,
    "end": 36.94,
    "tokens": [
      {
        "surface": "隠せ",
        "romaji": "kakuse",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "verb"
      },
      {
        "surface": "ぬ",
        "romaji": "nu",
        "meaning": "not",
        "pos": "auxiliary verb"
      },
      {
        "surface": "苛立ち",
        "romaji": "iradachi",
        "meaning": "to be irritated; to get annoyed; to lose one's patience",
        "pos": "verb"
      },
      {
        "surface": "と",
        "romaji": "to",
        "meaning": "door (esp. Japanese-style)",
        "pos": "particle"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "空白",
        "skip": true
      },
      {
        "surface": "立ち尽くす",
        "romaji": "tachitsukusu",
        "meaning": "to keep standing; to stand motionless",
        "pos": "verb"
      },
      {
        "surface": "自分",
        "romaji": "jibun",
        "meaning": "myself; yourself; oneself; himself; herself",
        "pos": "noun"
      },
      {
        "surface": "を",
        "romaji": "wo",
        "meaning": "indicates direct object of action",
        "pos": "particle"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "空白",
        "skip": true
      },
      {
        "surface": "見つめ",
        "romaji": "mitsume",
        "meaning": "to stare (at); to gaze (at); to look hard (at); to watch intently; to fix one's eyes (on)",
        "pos": "verb"
      }
    ],
    "translation": "Staring at myself standing still with unconcealed frustration"
  },
  {
    "id": "l4",
    "start": 36.94,
    "end": 40.55,
    "tokens": [
      {
        "surface": "迷い",
        "romaji": "mayoi",
        "meaning": "to lose one's way; to get lost; to go astray",
        "pos": "verb"
      },
      {
        "surface": "ながら",
        "romaji": "nagara",
        "meaning": "while; during; as",
        "pos": "particle"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "空白",
        "skip": true
      },
      {
        "surface": "悩み",
        "romaji": "nayami",
        "meaning": "to be worried; to be troubled",
        "pos": "verb"
      },
      {
        "surface": "ながら",
        "romaji": "nagara",
        "meaning": "while; during; as",
        "pos": "particle"
      }
    ],
    "translation": "While wondering and worrying"
  },
  {
    "id": "l5",
    "start": 40.55,
    "end": 44.24,
    "tokens": [
      {
        "surface": "悔やみ",
        "romaji": "kuyami",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "verb"
      },
      {
        "surface": "ながら",
        "romaji": "nagara",
        "meaning": "while; during; as",
        "pos": "particle"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "空白",
        "skip": true
      },
      {
        "surface": "決めれ",
        "romaji": "kimere",
        "meaning": "to decide; to choose; to determine; to make up one's mind; to resolve; to set one's heart on; to settle; to arrange; to set; to appoint; to fix",
        "pos": "verb"
      },
      {
        "surface": "ば",
        "romaji": "ba",
        "meaning": "place; spot; space",
        "pos": "particle"
      },
      {
        "surface": "いい",
        "romaji": "ii",
        "meaning": "good; excellent; fine; nice; pleasant; agreeable",
        "pos": "adjective"
      },
      {
        "surface": "さ",
        "romaji": "sa",
        "meaning": "difference; variation",
        "pos": "particle"
      }
    ],
    "translation": "You should make a decision while feeling regretful."
  },
  {
    "id": "l6",
    "start": 44.24,
    "end": 51.42,
    "tokens": [
      {
        "surface": "君",
        "romaji": "kimi",
        "meaning": "you; buddy; pal",
        "pos": "noun"
      },
      {
        "surface": "が",
        "romaji": "ga",
        "meaning": "indicates the subject of a sentence",
        "pos": "particle"
      },
      {
        "surface": "くれ",
        "romaji": "kure",
        "meaning": "to get dark; to grow dark",
        "pos": "verb"
      },
      {
        "surface": "た",
        "romaji": "ta",
        "meaning": "rice field",
        "pos": "auxiliary verb"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "空白",
        "skip": true
      },
      {
        "surface": "言葉",
        "romaji": "kotoba",
        "meaning": "language; dialect",
        "pos": "noun"
      },
      {
        "surface": "ひとつ",
        "romaji": "hitotsu",
        "meaning": "one",
        "pos": "noun"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "空白",
        "skip": true
      },
      {
        "surface": "戸惑い",
        "romaji": "tomadoi",
        "meaning": "being at sea; losing one's bearings; confusion; wonderment",
        "pos": "noun"
      },
      {
        "surface": "は",
        "romaji": "ha",
        "meaning": "indicates sentence topic",
        "pos": "particle"
      },
      {
        "surface": "消え去り",
        "romaji": "kiesari",
        "meaning": "to disappear; to vanish",
        "pos": "verb"
      }
    ],
    "translation": "With the one word you gave me, my confusion disappears"
  },
  {
    "id": "l7",
    "start": 51.42,
    "end": 57.58,
    "tokens": [
      {
        "surface": "からっぽ",
        "romaji": "karappo",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "noun"
      },
      {
        "surface": "だっ",
        "romaji": "da",
        "meaning": "be; is",
        "pos": "auxiliary verb"
      },
      {
        "surface": "た",
        "romaji": "ta",
        "meaning": "rice field",
        "pos": "auxiliary verb"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "空白",
        "skip": true
      },
      {
        "surface": "僕",
        "romaji": "boku",
        "meaning": "I; me",
        "pos": "noun"
      },
      {
        "surface": "の",
        "romaji": "no",
        "meaning": "indicates possessive",
        "pos": "particle"
      },
      {
        "surface": "部屋",
        "romaji": "heya",
        "meaning": "room; chamber",
        "pos": "noun"
      },
      {
        "surface": "に",
        "romaji": "ni",
        "meaning": "two; 2",
        "pos": "particle"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "空白",
        "skip": true
      },
      {
        "surface": "光",
        "romaji": "hikari",
        "meaning": "light",
        "pos": "noun"
      },
      {
        "surface": "が",
        "romaji": "ga",
        "meaning": "indicates the subject of a sentence",
        "pos": "particle"
      },
      {
        "surface": "射し",
        "romaji": "sashi",
        "meaning": "to shine",
        "pos": "verb"
      },
      {
        "surface": "た",
        "romaji": "ta",
        "meaning": "rice field",
        "pos": "auxiliary verb"
      }
    ],
    "translation": "Light shone into my empty room"
  },
  {
    "id": "l8",
    "start": 57.58,
    "end": 65.58,
    "tokens": [
      {
        "surface": "見上げ",
        "romaji": "miage",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "verb"
      },
      {
        "surface": "た",
        "romaji": "ta",
        "meaning": "rice field",
        "pos": "auxiliary verb"
      },
      {
        "surface": "大空",
        "romaji": "oozora",
        "meaning": "wide open sky; the blue; heavens; firmament",
        "pos": "noun"
      },
      {
        "surface": "が",
        "romaji": "ga",
        "meaning": "indicates the subject of a sentence",
        "pos": "particle"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "空白",
        "skip": true
      },
      {
        "surface": "青く",
        "romaji": "aoku",
        "meaning": "blue; azure",
        "pos": "adjective"
      },
      {
        "surface": "澄み切っ",
        "romaji": "sumiki",
        "meaning": "to be perfectly clear (water, air, etc.); to clear up",
        "pos": "verb"
      },
      {
        "surface": "て",
        "romaji": "te",
        "meaning": "hand; arm",
        "pos": "particle"
      },
      {
        "surface": "行く",
        "romaji": "iku",
        "meaning": "to go; to move (towards); to head (towards); to leave (for)",
        "pos": "verb"
      }
    ],
    "translation": "The sky I looked up at becomes clear and blue"
  },
  {
    "id": "l9",
    "start": 65.58,
    "end": 71.8,
    "tokens": [
      {
        "surface": "閉ざし",
        "romaji": "tozashi",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "verb"
      },
      {
        "surface": "た",
        "romaji": "ta",
        "meaning": "rice field",
        "pos": "auxiliary verb"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "空白",
        "skip": true
      },
      {
        "surface": "窓",
        "romaji": "mado",
        "meaning": "window",
        "pos": "noun"
      },
      {
        "surface": "を",
        "romaji": "wo",
        "meaning": "indicates direct object of action",
        "pos": "particle"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "空白",
        "skip": true
      },
      {
        "surface": "開く",
        "romaji": "hiraku",
        "meaning": "to open; to undo; to unseal; to unpack",
        "pos": "verb"
      },
      {
        "surface": "事",
        "romaji": "koto",
        "meaning": "thing; matter",
        "pos": "noun"
      },
      {
        "surface": "を",
        "romaji": "wo",
        "meaning": "indicates direct object of action",
        "pos": "particle"
      },
      {
        "surface": "決め",
        "romaji": "kime",
        "meaning": "to decide; to choose; to determine; to make up one's mind; to resolve; to set one's heart on; to settle; to arrange; to set; to appoint; to fix",
        "pos": "verb"
      },
      {
        "surface": "た",
        "romaji": "ta",
        "meaning": "rice field",
        "pos": "auxiliary verb"
      }
    ],
    "translation": "I decided to open the closed window"
  },
  {
    "id": "l10",
    "start": 71.8,
    "end": 79.04,
    "tokens": [
      {
        "surface": "自分",
        "romaji": "jibun",
        "meaning": "myself; yourself; oneself; himself; herself",
        "pos": "noun"
      },
      {
        "surface": "を",
        "romaji": "wo",
        "meaning": "indicates direct object of action",
        "pos": "particle"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "空白",
        "skip": true
      },
      {
        "surface": "世界",
        "romaji": "sekai",
        "meaning": "the world; society; the universe",
        "pos": "noun"
      },
      {
        "surface": "さえ",
        "romaji": "sae",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "particle"
      },
      {
        "surface": "も",
        "romaji": "mo",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "particle"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "空白",
        "skip": true
      },
      {
        "surface": "変え",
        "romaji": "kae",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "verb"
      },
      {
        "surface": "て",
        "romaji": "te",
        "meaning": "hand; arm",
        "pos": "particle"
      },
      {
        "surface": "しまえ",
        "romaji": "shimae",
        "meaning": "to finish; to stop; to end; to put an end to; to bring to a close",
        "pos": "verb"
      },
      {
        "surface": "そう",
        "romaji": "sou",
        "meaning": "monk; priest",
        "pos": "adverb"
      },
      {
        "surface": "な",
        "romaji": "na",
        "meaning": "don't",
        "pos": "particle"
      }
    ],
    "translation": "I feel like I can change myself and even the world"
  },
  {
    "id": "l11",
    "start": 79.04,
    "end": 87.21,
    "tokens": [
      {
        "surface": "瞬間",
        "romaji": "shunkan",
        "meaning": "moment; instant; second",
        "pos": "noun"
      },
      {
        "surface": "は",
        "romaji": "ha",
        "meaning": "indicates sentence topic",
        "pos": "particle"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "空白",
        "skip": true
      },
      {
        "surface": "いつも",
        "romaji": "itsumo",
        "meaning": "always; all the time; at all times",
        "pos": "adverb"
      },
      {
        "surface": "すぐ",
        "romaji": "sugu",
        "meaning": "immediately; at once; right away; directly",
        "pos": "adverb"
      },
      {
        "surface": "そば",
        "romaji": "soba",
        "meaning": "buckwheat (Fagopyrum esculentum)",
        "pos": "noun"
      },
      {
        "surface": "に",
        "romaji": "ni",
        "meaning": "two; 2",
        "pos": "particle"
      },
      {
        "surface": "...",
        "romaji": "...",
        "meaning": "one; 1",
        "pos": "noun"
      }
    ],
    "translation": "The moment is always right next to you..."
  },
  {
    "id": "l12",
    "start": 87.21,
    "end": 129.68,
    "tokens": [
      {
        "surface": "満たせ",
        "romaji": "mitase",
        "meaning": "to be full",
        "pos": "verb"
      },
      {
        "surface": "ぬ",
        "romaji": "nu",
        "meaning": "not",
        "pos": "auxiliary verb"
      },
      {
        "surface": "日常",
        "romaji": "nichijou",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "noun"
      },
      {
        "surface": "に",
        "romaji": "ni",
        "meaning": "two; 2",
        "pos": "particle"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "空白",
        "skip": true
      },
      {
        "surface": "在る",
        "romaji": "aru",
        "meaning": "to be; to exist; to live",
        "pos": "verb"
      },
      {
        "surface": "はず",
        "romaji": "hazu",
        "meaning": "should (be); bound (to be); expected (to be); must (be)",
        "pos": "noun"
      },
      {
        "surface": "の",
        "romaji": "no",
        "meaning": "indicates possessive",
        "pos": "particle"
      },
      {
        "surface": "答え",
        "romaji": "kotae",
        "meaning": "answer; reply; response",
        "pos": "noun"
      },
      {
        "surface": "を",
        "romaji": "wo",
        "meaning": "indicates direct object of action",
        "pos": "particle"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "空白",
        "skip": true
      },
      {
        "surface": "探し",
        "romaji": "sagashi",
        "meaning": "to search for; to look for; to hunt for; to seek",
        "pos": "verb"
      },
      {
        "surface": "て",
        "romaji": "te",
        "meaning": "hand; arm",
        "pos": "particle"
      }
    ],
    "translation": "Searching for the answer that should exist in my unsatisfying daily life"
  },
  {
    "id": "l13",
    "start": 129.68,
    "end": 135.77,
    "tokens": [
      {
        "surface": "朝日",
        "romaji": "asahi",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "noun"
      },
      {
        "surface": "に",
        "romaji": "ni",
        "meaning": "two; 2",
        "pos": "particle"
      },
      {
        "surface": "独り",
        "romaji": "hitori",
        "meaning": "one person",
        "pos": "noun"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "空白",
        "skip": true
      },
      {
        "surface": "柔らか",
        "romaji": "yawaraka",
        "meaning": "soft; tender; pliant; supple",
        "pos": "noun"
      },
      {
        "surface": "な",
        "romaji": "na",
        "meaning": "be; is",
        "pos": "auxiliary verb"
      },
      {
        "surface": "声",
        "romaji": "koe",
        "meaning": "voice",
        "pos": "noun"
      },
      {
        "surface": "に",
        "romaji": "ni",
        "meaning": "two; 2",
        "pos": "particle"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "空白",
        "skip": true
      },
      {
        "surface": "振り向け",
        "romaji": "furimuke",
        "meaning": "to turn one's face; to turn around; to look over one's shoulder",
        "pos": "verb"
      },
      {
        "surface": "ば",
        "romaji": "ba",
        "meaning": "place; spot; space",
        "pos": "particle"
      }
    ],
    "translation": "Alone in the morning sun, when I turn to the soft voice,"
  },
  {
    "id": "l14",
    "start": 135.77,
    "end": 142.97,
    "tokens": [
      {
        "surface": "眩い",
        "romaji": "mabayui",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "adjective"
      },
      {
        "surface": "日射し",
        "romaji": "hizashi",
        "meaning": "sunlight; rays of the Sun",
        "pos": "noun"
      },
      {
        "surface": "の",
        "romaji": "no",
        "meaning": "indicates possessive",
        "pos": "particle"
      },
      {
        "surface": "中",
        "romaji": "naka",
        "meaning": "medium (size); average (grade, level, etc.); middle",
        "pos": "noun"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "空白",
        "skip": true
      },
      {
        "surface": "ふと",
        "romaji": "futo",
        "meaning": "suddenly; casually; accidentally; incidentally; unexpectedly; unintentionally",
        "pos": "adverb"
      },
      {
        "surface": "君",
        "romaji": "kimi",
        "meaning": "you; buddy; pal",
        "pos": "noun"
      },
      {
        "surface": "が",
        "romaji": "ga",
        "meaning": "indicates the subject of a sentence",
        "pos": "particle"
      },
      {
        "surface": "微笑む",
        "romaji": "hohoemu",
        "meaning": "to smile",
        "pos": "verb"
      }
    ],
    "translation": "In the bright sunlight, you suddenly smile"
  },
  {
    "id": "l15",
    "start": 142.97,
    "end": 149.57,
    "tokens": [
      {
        "surface": "閉ざし",
        "romaji": "tozashi",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "verb"
      },
      {
        "surface": "た",
        "romaji": "ta",
        "meaning": "rice field",
        "pos": "auxiliary verb"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "空白",
        "skip": true
      },
      {
        "surface": "窓",
        "romaji": "mado",
        "meaning": "window",
        "pos": "noun"
      },
      {
        "surface": "が",
        "romaji": "ga",
        "meaning": "indicates the subject of a sentence",
        "pos": "particle"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "空白",
        "skip": true
      },
      {
        "surface": "開き",
        "romaji": "hiraki",
        "meaning": "to open; to undo; to unseal; to unpack",
        "pos": "verb"
      },
      {
        "surface": "そう",
        "romaji": "sou",
        "meaning": "monk; priest",
        "pos": "noun"
      },
      {
        "surface": "に",
        "romaji": "ni",
        "meaning": "two; 2",
        "pos": "particle"
      },
      {
        "surface": "なる",
        "romaji": "naru",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "verb"
      }
    ],
    "translation": "The closed window feels like it's about to open"
  },
  {
    "id": "l16",
    "start": 149.57,
    "end": 157.34,
    "tokens": [
      {
        "surface": "自分",
        "romaji": "jibun",
        "meaning": "myself; yourself; oneself; himself; herself",
        "pos": "noun"
      },
      {
        "surface": "を",
        "romaji": "wo",
        "meaning": "indicates direct object of action",
        "pos": "particle"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "空白",
        "skip": true
      },
      {
        "surface": "世界",
        "romaji": "sekai",
        "meaning": "the world; society; the universe",
        "pos": "noun"
      },
      {
        "surface": "さえ",
        "romaji": "sae",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "particle"
      },
      {
        "surface": "も",
        "romaji": "mo",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "particle"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "空白",
        "skip": true
      },
      {
        "surface": "変え",
        "romaji": "kae",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "verb"
      },
      {
        "surface": "て",
        "romaji": "te",
        "meaning": "hand; arm",
        "pos": "particle"
      },
      {
        "surface": "しまえ",
        "romaji": "shimae",
        "meaning": "to finish; to stop; to end; to put an end to; to bring to a close",
        "pos": "verb"
      },
      {
        "surface": "そう",
        "romaji": "sou",
        "meaning": "monk; priest",
        "pos": "adverb"
      },
      {
        "surface": "な",
        "romaji": "na",
        "meaning": "don't",
        "pos": "particle"
      }
    ],
    "translation": "I feel like I can change myself and even the world"
  },
  {
    "id": "l17",
    "start": 157.34,
    "end": 164.21,
    "tokens": [
      {
        "surface": "存在",
        "romaji": "sonzai",
        "meaning": "existence; being; presence",
        "pos": "noun"
      },
      {
        "surface": "は",
        "romaji": "ha",
        "meaning": "indicates sentence topic",
        "pos": "particle"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "空白",
        "skip": true
      },
      {
        "surface": "僕",
        "romaji": "boku",
        "meaning": "I; me",
        "pos": "noun"
      },
      {
        "surface": "の",
        "romaji": "no",
        "meaning": "indicates possessive",
        "pos": "particle"
      },
      {
        "surface": "目",
        "romaji": "me",
        "meaning": "eye; eyeball",
        "pos": "noun"
      },
      {
        "surface": "の",
        "romaji": "no",
        "meaning": "indicates possessive",
        "pos": "particle"
      },
      {
        "surface": "前",
        "romaji": "mae",
        "meaning": "last (i.e. immediately preceding); previous; ex-; former",
        "pos": "noun"
      },
      {
        "surface": "に",
        "romaji": "ni",
        "meaning": "two; 2",
        "pos": "particle"
      },
      {
        "surface": "...",
        "romaji": "...",
        "meaning": "one; 1",
        "pos": "noun"
      }
    ],
    "translation": "Existence is right in front of my eyes..."
  },
  {
    "id": "l18",
    "start": 164.21,
    "end": 171.04,
    "tokens": [
      {
        "surface": "見上げ",
        "romaji": "miage",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "verb"
      },
      {
        "surface": "た",
        "romaji": "ta",
        "meaning": "rice field",
        "pos": "auxiliary verb"
      },
      {
        "surface": "大空",
        "romaji": "oozora",
        "meaning": "wide open sky; the blue; heavens; firmament",
        "pos": "noun"
      },
      {
        "surface": "が",
        "romaji": "ga",
        "meaning": "indicates the subject of a sentence",
        "pos": "particle"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "空白",
        "skip": true
      },
      {
        "surface": "青く",
        "romaji": "aoku",
        "meaning": "blue; azure",
        "pos": "adjective"
      },
      {
        "surface": "澄み切っ",
        "romaji": "sumiki",
        "meaning": "to be perfectly clear (water, air, etc.); to clear up",
        "pos": "verb"
      },
      {
        "surface": "て",
        "romaji": "te",
        "meaning": "hand; arm",
        "pos": "particle"
      },
      {
        "surface": "行く",
        "romaji": "iku",
        "meaning": "to go; to move (towards); to head (towards); to leave (for)",
        "pos": "verb"
      }
    ],
    "translation": "The sky I looked up at becomes clear and blue"
  },
  {
    "id": "l19",
    "start": 171.04,
    "end": 177.81,
    "tokens": [
      {
        "surface": "閉ざし",
        "romaji": "tozashi",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "verb"
      },
      {
        "surface": "た",
        "romaji": "ta",
        "meaning": "rice field",
        "pos": "auxiliary verb"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "空白",
        "skip": true
      },
      {
        "surface": "窓",
        "romaji": "mado",
        "meaning": "window",
        "pos": "noun"
      },
      {
        "surface": "を",
        "romaji": "wo",
        "meaning": "indicates direct object of action",
        "pos": "particle"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "空白",
        "skip": true
      },
      {
        "surface": "開く",
        "romaji": "hiraku",
        "meaning": "to open; to undo; to unseal; to unpack",
        "pos": "verb"
      },
      {
        "surface": "事",
        "romaji": "koto",
        "meaning": "thing; matter",
        "pos": "noun"
      },
      {
        "surface": "を",
        "romaji": "wo",
        "meaning": "indicates direct object of action",
        "pos": "particle"
      },
      {
        "surface": "決め",
        "romaji": "kime",
        "meaning": "to decide; to choose; to determine; to make up one's mind; to resolve; to set one's heart on; to settle; to arrange; to set; to appoint; to fix",
        "pos": "verb"
      },
      {
        "surface": "た",
        "romaji": "ta",
        "meaning": "rice field",
        "pos": "auxiliary verb"
      }
    ],
    "translation": "I decided to open the closed window"
  },
  {
    "id": "l20",
    "start": 177.81,
    "end": 185.42,
    "tokens": [
      {
        "surface": "自分",
        "romaji": "jibun",
        "meaning": "myself; yourself; oneself; himself; herself",
        "pos": "noun"
      },
      {
        "surface": "を",
        "romaji": "wo",
        "meaning": "indicates direct object of action",
        "pos": "particle"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "空白",
        "skip": true
      },
      {
        "surface": "世界",
        "romaji": "sekai",
        "meaning": "the world; society; the universe",
        "pos": "noun"
      },
      {
        "surface": "さえ",
        "romaji": "sae",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "particle"
      },
      {
        "surface": "も",
        "romaji": "mo",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "particle"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "空白",
        "skip": true
      },
      {
        "surface": "変え",
        "romaji": "kae",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "verb"
      },
      {
        "surface": "て",
        "romaji": "te",
        "meaning": "hand; arm",
        "pos": "particle"
      },
      {
        "surface": "しまえ",
        "romaji": "shimae",
        "meaning": "to finish; to stop; to end; to put an end to; to bring to a close",
        "pos": "verb"
      },
      {
        "surface": "そう",
        "romaji": "sou",
        "meaning": "monk; priest",
        "pos": "adverb"
      },
      {
        "surface": "な",
        "romaji": "na",
        "meaning": "don't",
        "pos": "particle"
      }
    ],
    "translation": "I feel like I can change myself and even the world"
  },
  {
    "id": "l21",
    "start": 185.42,
    "end": 192.24,
    "tokens": [
      {
        "surface": "瞬間",
        "romaji": "shunkan",
        "meaning": "moment; instant; second",
        "pos": "noun"
      },
      {
        "surface": "を",
        "romaji": "wo",
        "meaning": "indicates direct object of action",
        "pos": "particle"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "空白",
        "skip": true
      },
      {
        "surface": "感じる",
        "romaji": "kanjiru",
        "meaning": "to feel; to sense; to experience",
        "pos": "verb"
      },
      {
        "surface": "今",
        "romaji": "ima",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "noun"
      },
      {
        "surface": "ここ",
        "romaji": "koko",
        "meaning": "individual; one by one; separate; each",
        "pos": "noun"
      },
      {
        "surface": "に",
        "romaji": "ni",
        "meaning": "two; 2",
        "pos": "particle"
      },
      {
        "surface": "...",
        "romaji": "...",
        "meaning": "one; 1",
        "pos": "noun"
      }
    ],
    "translation": "Here I am, feeling the moment..."
  },
  {
    "id": "l22",
    "start": 192.24,
    "end": 199.94,
    "tokens": [
      {
        "surface": "光",
        "romaji": "hikari",
        "meaning": "light",
        "pos": "noun"
      },
      {
        "surface": "へ",
        "romaji": "he",
        "meaning": "to; towards; for",
        "pos": "particle"
      },
      {
        "surface": "と",
        "romaji": "to",
        "meaning": "door (esp. Japanese-style)",
        "pos": "particle"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "空白",
        "skip": true
      },
      {
        "surface": "両手",
        "romaji": "ryoute",
        "meaning": "both hands; both arms",
        "pos": "noun"
      },
      {
        "surface": "を",
        "romaji": "wo",
        "meaning": "indicates direct object of action",
        "pos": "particle"
      },
      {
        "surface": "伸ばし",
        "romaji": "nobashi",
        "meaning": "to grow long (e.g. hair, nails)",
        "pos": "verb"
      },
      {
        "surface": "て",
        "romaji": "te",
        "meaning": "hand; arm",
        "pos": "particle"
      },
      {
        "surface": "...",
        "romaji": "...",
        "meaning": "one; 1",
        "pos": "noun"
      }
    ],
    "translation": "Reach out your hands towards the light..."
  },
  {
    "id": "l23",
    "start": 199.94,
    "end": 203.94,
    "tokens": [
      {
        "surface": "心",
        "romaji": "kokoro",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "noun"
      },
      {
        "surface": "を",
        "romaji": "wo",
        "meaning": "indicates direct object of action",
        "pos": "particle"
      },
      {
        "surface": "吹き抜ける",
        "romaji": "fukinukeru",
        "meaning": "to blow through; to blow across",
        "pos": "verb"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "空白",
        "skip": true
      },
      {
        "surface": "空",
        "romaji": "sora",
        "meaning": "sky; the air; the heavens",
        "pos": "noun"
      },
      {
        "surface": "の",
        "romaji": "no",
        "meaning": "indicates possessive",
        "pos": "particle"
      },
      {
        "surface": "色",
        "romaji": "iro",
        "meaning": "colour; color; hue; tint; tinge; shade",
        "pos": "noun"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "空白",
        "skip": true
      },
      {
        "surface": "香る",
        "romaji": "kaoru",
        "meaning": "to smell sweet; to be fragrant",
        "pos": "verb"
      },
      {
        "surface": "風",
        "romaji": "kaze",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "noun"
      }
    ],
    "translation": "The color of the sky and the fragrant wind that blows through your heart"
  }
];
