import { LyricLine } from "@/lib/types";

// Auto-generated by scripts/generate-lyrics.mjs for "colors" by flow.
// Words come from kuromoji (segmentation), wanakana (romaji), and Jisho
// (dictionary meanings) — spot-check before shipping, don't trust blindly.
export const colorsLyrics: LyricLine[] = [
  {
    "id": "l1",
    "start": 8.3,
    "end": 15.76,
    "tokens": [
      {
        "surface": "自分",
        "romaji": "jibun",
        "meaning": "myself; yourself; oneself; himself; herself",
        "pos": "noun",
        "skip": false,
        "lookupWord": "自分",
        "baseForm": "自分",
        "conjugation": null
      },
      {
        "surface": "を",
        "romaji": "wo",
        "meaning": "indicates direct object of an action",
        "pos": "particle",
        "skip": false
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "",
        "pos": "空白",
        "skip": true,
        "lookupWord": "",
        "baseForm": "",
        "conjugation": null
      },
      {
        "surface": "世界",
        "romaji": "sekai",
        "meaning": "the world; society; the universe",
        "pos": "noun",
        "skip": false,
        "lookupWord": "世界",
        "baseForm": "世界",
        "conjugation": null
      },
      {
        "surface": "さえ",
        "romaji": "sae",
        "meaning": "even",
        "pos": "particle",
        "skip": false,
        "lookupWord": "さえ",
        "baseForm": "さえ",
        "conjugation": null
      },
      {
        "surface": "も",
        "romaji": "mo",
        "meaning": "indicates addition or inclusion (also / too / as well)",
        "pos": "particle",
        "skip": false
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "",
        "pos": "空白",
        "skip": true,
        "lookupWord": "",
        "baseForm": "",
        "conjugation": null
      },
      {
        "surface": "変えて",
        "romaji": "kaete",
        "meaning": "to change; to alter; to transform; to convert; to turn; to vary",
        "pos": "verb",
        "skip": false,
        "lookupWord": "変える",
        "baseForm": "変える",
        "conjugation": "te-form"
      },
      {
        "surface": "しまえ",
        "romaji": "shimae",
        "meaning": "to finish; to stop; to end; to put an end to; to bring to a close",
        "pos": "verb",
        "skip": false,
        "lookupWord": "しまう",
        "baseForm": "しまう",
        "conjugation": null
      },
      {
        "surface": "そう",
        "romaji": "sou",
        "meaning": "monk; priest",
        "pos": "adverb",
        "skip": false,
        "lookupWord": "そう",
        "baseForm": "そう",
        "conjugation": null
      },
      {
        "surface": "な",
        "romaji": "na",
        "meaning": "don't",
        "pos": "particle",
        "skip": false,
        "lookupWord": "な",
        "baseForm": "な",
        "conjugation": null
      }
    ],
    "translation": "I feel like I can change myself and even the world"
  },
  {
    "id": "l2",
    "start": 15.76,
    "end": 23.56,
    "tokens": [
      {
        "surface": "瞬間",
        "romaji": "shunkan",
        "meaning": "moment; instant; second",
        "pos": "noun",
        "skip": false,
        "lookupWord": "瞬間",
        "baseForm": "瞬間",
        "conjugation": null
      },
      {
        "surface": "は",
        "romaji": "ha",
        "meaning": "indicates topic of a sentence",
        "pos": "particle",
        "skip": false
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "",
        "pos": "空白",
        "skip": true,
        "lookupWord": "",
        "baseForm": "",
        "conjugation": null
      },
      {
        "surface": "いつも",
        "romaji": "itsumo",
        "meaning": "always; all the time; at all times",
        "pos": "adverb",
        "skip": false,
        "lookupWord": "いつも",
        "baseForm": "いつも",
        "conjugation": null
      },
      {
        "surface": "すぐ",
        "romaji": "sugu",
        "meaning": "immediately; at once; right away; directly",
        "pos": "adverb",
        "skip": false,
        "lookupWord": "すぐ",
        "baseForm": "すぐ",
        "conjugation": null
      },
      {
        "surface": "そば",
        "romaji": "soba",
        "meaning": "buckwheat (Fagopyrum esculentum)",
        "pos": "noun",
        "skip": false,
        "lookupWord": "そば",
        "baseForm": "そば",
        "conjugation": null
      },
      {
        "surface": "に",
        "romaji": "ni",
        "meaning": "indicates direction, destination, time, or target (to / at / in)",
        "pos": "particle",
        "skip": false
      },
      {
        "surface": "...",
        "romaji": "...",
        "meaning": "",
        "pos": "noun",
        "skip": true,
        "lookupWord": "",
        "baseForm": "",
        "conjugation": null
      }
    ],
    "translation": "The moment is always right next to you.."
  },
  {
    "id": "l3",
    "start": 23.56,
    "end": 36.94,
    "tokens": [
      {
        "surface": "隠せぬ",
        "romaji": "kakusenu",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "verb",
        "skip": false,
        "lookupWord": "隠せる",
        "baseForm": "隠せる",
        "conjugation": "auxiliary / conjugated"
      },
      {
        "surface": "苛立ち",
        "romaji": "iradachi",
        "meaning": "to be irritated; to get annoyed; to lose one's patience",
        "pos": "verb",
        "skip": false,
        "lookupWord": "苛立つ",
        "baseForm": "苛立つ",
        "conjugation": null
      },
      {
        "surface": "と",
        "romaji": "to",
        "meaning": "indicates togetherness or quotation (and / with)",
        "pos": "particle",
        "skip": false
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "",
        "pos": "空白",
        "skip": true,
        "lookupWord": "",
        "baseForm": "",
        "conjugation": null
      },
      {
        "surface": "立ち尽くす",
        "romaji": "tachitsukusu",
        "meaning": "to keep standing; to stand motionless",
        "pos": "verb",
        "skip": false,
        "lookupWord": "立ち尽くす",
        "baseForm": "立ち尽くす",
        "conjugation": null
      },
      {
        "surface": "自分",
        "romaji": "jibun",
        "meaning": "myself; yourself; oneself; himself; herself",
        "pos": "noun",
        "skip": false,
        "lookupWord": "自分",
        "baseForm": "自分",
        "conjugation": null
      },
      {
        "surface": "を",
        "romaji": "wo",
        "meaning": "indicates direct object of an action",
        "pos": "particle",
        "skip": false
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "",
        "pos": "空白",
        "skip": true,
        "lookupWord": "",
        "baseForm": "",
        "conjugation": null
      },
      {
        "surface": "見つめ",
        "romaji": "mitsume",
        "meaning": "to stare (at); to gaze (at); to look hard (at); to watch intently; to fix one's eyes (on)",
        "pos": "verb",
        "skip": false,
        "lookupWord": "見つめる",
        "baseForm": "見つめる",
        "conjugation": null
      }
    ],
    "translation": "Staring at myself standing still with unconcealed frustration"
  },
  {
    "id": "l4",
    "start": 36.94,
    "end": 40.55,
    "tokens": [
      {
        "surface": "迷い",
        "romaji": "mayoi",
        "meaning": "to lose one's way; to get lost; to go astray",
        "pos": "verb",
        "skip": false,
        "lookupWord": "迷う",
        "baseForm": "迷う",
        "conjugation": null
      },
      {
        "surface": "ながら",
        "romaji": "nagara",
        "meaning": "while; during; as",
        "pos": "particle",
        "skip": false,
        "lookupWord": "ながら",
        "baseForm": "ながら",
        "conjugation": null
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "",
        "pos": "空白",
        "skip": true,
        "lookupWord": "",
        "baseForm": "",
        "conjugation": null
      },
      {
        "surface": "悩み",
        "romaji": "nayami",
        "meaning": "to be worried; to be troubled",
        "pos": "verb",
        "skip": false,
        "lookupWord": "悩む",
        "baseForm": "悩む",
        "conjugation": null
      },
      {
        "surface": "ながら",
        "romaji": "nagara",
        "meaning": "while; during; as",
        "pos": "particle",
        "skip": false,
        "lookupWord": "ながら",
        "baseForm": "ながら",
        "conjugation": null
      }
    ],
    "translation": "While wondering and worrying"
  },
  {
    "id": "l5",
    "start": 40.55,
    "end": 44.24,
    "tokens": [
      {
        "surface": "悔やみ",
        "romaji": "kuyami",
        "meaning": "to mourn; to lament",
        "pos": "verb",
        "skip": false,
        "lookupWord": "悔やむ",
        "baseForm": "悔やむ",
        "conjugation": null
      },
      {
        "surface": "ながら",
        "romaji": "nagara",
        "meaning": "while; during; as",
        "pos": "particle",
        "skip": false,
        "lookupWord": "ながら",
        "baseForm": "ながら",
        "conjugation": null
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "",
        "pos": "空白",
        "skip": true,
        "lookupWord": "",
        "baseForm": "",
        "conjugation": null
      },
      {
        "surface": "決めれ",
        "romaji": "kimere",
        "meaning": "to decide; to choose; to determine; to make up one's mind; to resolve; to set one's heart on; to settle; to arrange; to set; to appoint; to fix",
        "pos": "verb",
        "skip": false,
        "lookupWord": "決める",
        "baseForm": "決める",
        "conjugation": null
      },
      {
        "surface": "ば",
        "romaji": "ba",
        "meaning": "place; spot; space",
        "pos": "particle",
        "skip": false,
        "lookupWord": "ば",
        "baseForm": "ば",
        "conjugation": null
      },
      {
        "surface": "いい",
        "romaji": "ii",
        "meaning": "good; excellent; fine; nice; pleasant; agreeable",
        "pos": "adjective",
        "skip": false,
        "lookupWord": "いい",
        "baseForm": "いい",
        "conjugation": null
      },
      {
        "surface": "さ",
        "romaji": "sa",
        "meaning": "difference; variation",
        "pos": "particle",
        "skip": false,
        "lookupWord": "さ",
        "baseForm": "さ",
        "conjugation": null
      }
    ],
    "translation": "You should make a decision while feeling regretful"
  },
  {
    "id": "l6",
    "start": 44.24,
    "end": 51.42,
    "tokens": [
      {
        "surface": "君",
        "romaji": "kimi",
        "meaning": "you; buddy; pal",
        "pos": "noun",
        "skip": false,
        "lookupWord": "君",
        "baseForm": "君",
        "conjugation": null
      },
      {
        "surface": "が",
        "romaji": "ga",
        "meaning": "indicates subject of a sentence",
        "pos": "particle",
        "skip": false
      },
      {
        "surface": "くれた",
        "romaji": "kureta",
        "meaning": "to get dark; to grow dark",
        "pos": "verb",
        "skip": false,
        "lookupWord": "くれる",
        "baseForm": "くれる",
        "conjugation": "auxiliary / conjugated"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "",
        "pos": "空白",
        "skip": true,
        "lookupWord": "",
        "baseForm": "",
        "conjugation": null
      },
      {
        "surface": "言葉",
        "romaji": "kotoba",
        "meaning": "language; dialect",
        "pos": "noun",
        "skip": false,
        "lookupWord": "言葉",
        "baseForm": "言葉",
        "conjugation": null
      },
      {
        "surface": "ひとつ",
        "romaji": "hitotsu",
        "meaning": "one",
        "pos": "noun",
        "skip": false,
        "lookupWord": "ひとつ",
        "baseForm": "ひとつ",
        "conjugation": null
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "",
        "pos": "空白",
        "skip": true,
        "lookupWord": "",
        "baseForm": "",
        "conjugation": null
      },
      {
        "surface": "戸惑い",
        "romaji": "tomadoi",
        "meaning": "being at sea; losing one's bearings; confusion; wonderment",
        "pos": "noun",
        "skip": false,
        "lookupWord": "戸惑い",
        "baseForm": "戸惑い",
        "conjugation": null
      },
      {
        "surface": "は",
        "romaji": "ha",
        "meaning": "indicates topic of a sentence",
        "pos": "particle",
        "skip": false
      },
      {
        "surface": "消え去り",
        "romaji": "kiesari",
        "meaning": "to disappear; to vanish",
        "pos": "verb",
        "skip": false,
        "lookupWord": "消え去る",
        "baseForm": "消え去る",
        "conjugation": null
      }
    ],
    "translation": "With the one word you gave me, my confusion disappears"
  },
  {
    "id": "l7",
    "start": 51.42,
    "end": 57.58,
    "tokens": [
      {
        "surface": "からっぽ",
        "romaji": "karappo",
        "meaning": "empty; vacant; hollow",
        "pos": "noun",
        "skip": false,
        "lookupWord": "からっぽ",
        "baseForm": "からっぽ",
        "conjugation": null
      },
      {
        "surface": "だっ",
        "romaji": "da",
        "meaning": "be; is",
        "pos": "auxiliary verb",
        "skip": false,
        "lookupWord": "だ",
        "baseForm": "だ",
        "conjugation": null
      },
      {
        "surface": "た",
        "romaji": "ta",
        "meaning": "rice field",
        "pos": "auxiliary verb",
        "skip": false,
        "lookupWord": "た",
        "baseForm": "た",
        "conjugation": null
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "",
        "pos": "空白",
        "skip": true,
        "lookupWord": "",
        "baseForm": "",
        "conjugation": null
      },
      {
        "surface": "僕",
        "romaji": "boku",
        "meaning": "I; me",
        "pos": "noun",
        "skip": false,
        "lookupWord": "僕",
        "baseForm": "僕",
        "conjugation": null
      },
      {
        "surface": "の",
        "romaji": "no",
        "meaning": "indicates possession or noun modification (of / 's)",
        "pos": "particle",
        "skip": false
      },
      {
        "surface": "部屋",
        "romaji": "heya",
        "meaning": "room; chamber",
        "pos": "noun",
        "skip": false,
        "lookupWord": "部屋",
        "baseForm": "部屋",
        "conjugation": null
      },
      {
        "surface": "に",
        "romaji": "ni",
        "meaning": "indicates direction, destination, time, or target (to / at / in)",
        "pos": "particle",
        "skip": false
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "",
        "pos": "空白",
        "skip": true,
        "lookupWord": "",
        "baseForm": "",
        "conjugation": null
      },
      {
        "surface": "光",
        "romaji": "hikari",
        "meaning": "light",
        "pos": "noun",
        "skip": false,
        "lookupWord": "光",
        "baseForm": "光",
        "conjugation": null
      },
      {
        "surface": "が",
        "romaji": "ga",
        "meaning": "indicates subject of a sentence",
        "pos": "particle",
        "skip": false
      },
      {
        "surface": "射した",
        "romaji": "sashita",
        "meaning": "to shine",
        "pos": "verb",
        "skip": false,
        "lookupWord": "射す",
        "baseForm": "射す",
        "conjugation": "auxiliary / conjugated"
      }
    ],
    "translation": "Light shone into my empty room"
  },
  {
    "id": "l8",
    "start": 57.58,
    "end": 65.58,
    "tokens": [
      {
        "surface": "見上げた",
        "romaji": "miageta",
        "meaning": "to look up at; to raise one's eyes",
        "pos": "verb",
        "skip": false,
        "lookupWord": "見上げる",
        "baseForm": "見上げる",
        "conjugation": "auxiliary / conjugated"
      },
      {
        "surface": "大空",
        "romaji": "oozora",
        "meaning": "wide open sky; the blue; heavens; firmament",
        "pos": "noun",
        "skip": false,
        "lookupWord": "大空",
        "baseForm": "大空",
        "conjugation": null
      },
      {
        "surface": "が",
        "romaji": "ga",
        "meaning": "indicates subject of a sentence",
        "pos": "particle",
        "skip": false
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "",
        "pos": "空白",
        "skip": true,
        "lookupWord": "",
        "baseForm": "",
        "conjugation": null
      },
      {
        "surface": "青く",
        "romaji": "aoku",
        "meaning": "blue; azure",
        "pos": "adjective",
        "skip": false,
        "lookupWord": "青い",
        "baseForm": "青い",
        "conjugation": null
      },
      {
        "surface": "澄み切って",
        "romaji": "sumikite",
        "meaning": "to be perfectly clear (water, air, etc.); to clear up",
        "pos": "verb",
        "skip": false,
        "lookupWord": "澄み切る",
        "baseForm": "澄み切る",
        "conjugation": "te-form"
      },
      {
        "surface": "行く",
        "romaji": "iku",
        "meaning": "to go; to move (towards); to head (towards); to leave (for)",
        "pos": "verb",
        "skip": false,
        "lookupWord": "行く",
        "baseForm": "行く",
        "conjugation": null
      }
    ],
    "translation": "The sky I looked up at becomes clear and blue"
  },
  {
    "id": "l9",
    "start": 65.58,
    "end": 71.8,
    "tokens": [
      {
        "surface": "閉ざした",
        "romaji": "tozashita",
        "meaning": "to shut; to close; to fasten; to lock",
        "pos": "verb",
        "skip": false,
        "lookupWord": "閉ざす",
        "baseForm": "閉ざす",
        "conjugation": "auxiliary / conjugated"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "",
        "pos": "空白",
        "skip": true,
        "lookupWord": "",
        "baseForm": "",
        "conjugation": null
      },
      {
        "surface": "窓",
        "romaji": "mado",
        "meaning": "window",
        "pos": "noun",
        "skip": false,
        "lookupWord": "窓",
        "baseForm": "窓",
        "conjugation": null
      },
      {
        "surface": "を",
        "romaji": "wo",
        "meaning": "indicates direct object of an action",
        "pos": "particle",
        "skip": false
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "",
        "pos": "空白",
        "skip": true,
        "lookupWord": "",
        "baseForm": "",
        "conjugation": null
      },
      {
        "surface": "開く",
        "romaji": "hiraku",
        "meaning": "to open; to undo; to unseal; to unpack",
        "pos": "verb",
        "skip": false,
        "lookupWord": "開く",
        "baseForm": "開く",
        "conjugation": null
      },
      {
        "surface": "事",
        "romaji": "koto",
        "meaning": "thing; matter",
        "pos": "noun",
        "skip": false,
        "lookupWord": "事",
        "baseForm": "事",
        "conjugation": null
      },
      {
        "surface": "を",
        "romaji": "wo",
        "meaning": "indicates direct object of an action",
        "pos": "particle",
        "skip": false
      },
      {
        "surface": "決めた",
        "romaji": "kimeta",
        "meaning": "to decide; to choose; to determine; to make up one's mind; to resolve; to set one's heart on; to settle; to arrange; to set; to appoint; to fix",
        "pos": "verb",
        "skip": false,
        "lookupWord": "決める",
        "baseForm": "決める",
        "conjugation": "auxiliary / conjugated"
      }
    ],
    "translation": "I decided to open the closed window"
  },
  {
    "id": "l10",
    "start": 71.8,
    "end": 79.04,
    "tokens": [
      {
        "surface": "自分",
        "romaji": "jibun",
        "meaning": "myself; yourself; oneself; himself; herself",
        "pos": "noun",
        "skip": false,
        "lookupWord": "自分",
        "baseForm": "自分",
        "conjugation": null
      },
      {
        "surface": "を",
        "romaji": "wo",
        "meaning": "indicates direct object of an action",
        "pos": "particle",
        "skip": false
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "",
        "pos": "空白",
        "skip": true,
        "lookupWord": "",
        "baseForm": "",
        "conjugation": null
      },
      {
        "surface": "世界",
        "romaji": "sekai",
        "meaning": "the world; society; the universe",
        "pos": "noun",
        "skip": false,
        "lookupWord": "世界",
        "baseForm": "世界",
        "conjugation": null
      },
      {
        "surface": "さえ",
        "romaji": "sae",
        "meaning": "even",
        "pos": "particle",
        "skip": false,
        "lookupWord": "さえ",
        "baseForm": "さえ",
        "conjugation": null
      },
      {
        "surface": "も",
        "romaji": "mo",
        "meaning": "indicates addition or inclusion (also / too / as well)",
        "pos": "particle",
        "skip": false
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "",
        "pos": "空白",
        "skip": true,
        "lookupWord": "",
        "baseForm": "",
        "conjugation": null
      },
      {
        "surface": "変えて",
        "romaji": "kaete",
        "meaning": "to change; to alter; to transform; to convert; to turn; to vary",
        "pos": "verb",
        "skip": false,
        "lookupWord": "変える",
        "baseForm": "変える",
        "conjugation": "te-form"
      },
      {
        "surface": "しまえ",
        "romaji": "shimae",
        "meaning": "to finish; to stop; to end; to put an end to; to bring to a close",
        "pos": "verb",
        "skip": false,
        "lookupWord": "しまう",
        "baseForm": "しまう",
        "conjugation": null
      },
      {
        "surface": "そう",
        "romaji": "sou",
        "meaning": "monk; priest",
        "pos": "adverb",
        "skip": false,
        "lookupWord": "そう",
        "baseForm": "そう",
        "conjugation": null
      },
      {
        "surface": "な",
        "romaji": "na",
        "meaning": "don't",
        "pos": "particle",
        "skip": false,
        "lookupWord": "な",
        "baseForm": "な",
        "conjugation": null
      }
    ],
    "translation": "I feel like I can change myself and even the world"
  },
  {
    "id": "l11",
    "start": 79.04,
    "end": 87.21,
    "tokens": [
      {
        "surface": "瞬間",
        "romaji": "shunkan",
        "meaning": "moment; instant; second",
        "pos": "noun",
        "skip": false,
        "lookupWord": "瞬間",
        "baseForm": "瞬間",
        "conjugation": null
      },
      {
        "surface": "は",
        "romaji": "ha",
        "meaning": "indicates topic of a sentence",
        "pos": "particle",
        "skip": false
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "",
        "pos": "空白",
        "skip": true,
        "lookupWord": "",
        "baseForm": "",
        "conjugation": null
      },
      {
        "surface": "いつも",
        "romaji": "itsumo",
        "meaning": "always; all the time; at all times",
        "pos": "adverb",
        "skip": false,
        "lookupWord": "いつも",
        "baseForm": "いつも",
        "conjugation": null
      },
      {
        "surface": "すぐ",
        "romaji": "sugu",
        "meaning": "immediately; at once; right away; directly",
        "pos": "adverb",
        "skip": false,
        "lookupWord": "すぐ",
        "baseForm": "すぐ",
        "conjugation": null
      },
      {
        "surface": "そば",
        "romaji": "soba",
        "meaning": "buckwheat (Fagopyrum esculentum)",
        "pos": "noun",
        "skip": false,
        "lookupWord": "そば",
        "baseForm": "そば",
        "conjugation": null
      },
      {
        "surface": "に",
        "romaji": "ni",
        "meaning": "indicates direction, destination, time, or target (to / at / in)",
        "pos": "particle",
        "skip": false
      },
      {
        "surface": "...",
        "romaji": "...",
        "meaning": "",
        "pos": "noun",
        "skip": true,
        "lookupWord": "",
        "baseForm": "",
        "conjugation": null
      }
    ],
    "translation": "The moment is always right next to you.."
  },
  {
    "id": "l12",
    "start": 87.21,
    "end": 129.68,
    "tokens": [
      {
        "surface": "満たせぬ",
        "romaji": "mitasenu",
        "meaning": "to be full",
        "pos": "verb",
        "skip": false,
        "lookupWord": "満たせる",
        "baseForm": "満たせる",
        "conjugation": "auxiliary / conjugated"
      },
      {
        "surface": "日常",
        "romaji": "nichijou",
        "meaning": "everyday; daily; ordinary; usual; routine; regular",
        "pos": "noun",
        "skip": false,
        "lookupWord": "日常",
        "baseForm": "日常",
        "conjugation": null
      },
      {
        "surface": "に",
        "romaji": "ni",
        "meaning": "indicates direction, destination, time, or target (to / at / in)",
        "pos": "particle",
        "skip": false
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "",
        "pos": "空白",
        "skip": true,
        "lookupWord": "",
        "baseForm": "",
        "conjugation": null
      },
      {
        "surface": "在る",
        "romaji": "aru",
        "meaning": "to be; to exist; to live",
        "pos": "verb",
        "skip": false,
        "lookupWord": "在る",
        "baseForm": "在る",
        "conjugation": null
      },
      {
        "surface": "はず",
        "romaji": "hazu",
        "meaning": "should (be); bound (to be); expected (to be); must (be)",
        "pos": "noun",
        "skip": false,
        "lookupWord": "はず",
        "baseForm": "はず",
        "conjugation": null
      },
      {
        "surface": "の",
        "romaji": "no",
        "meaning": "indicates possession or noun modification (of / 's)",
        "pos": "particle",
        "skip": false
      },
      {
        "surface": "答え",
        "romaji": "kotae",
        "meaning": "answer; reply; response",
        "pos": "noun",
        "skip": false,
        "lookupWord": "答え",
        "baseForm": "答え",
        "conjugation": null
      },
      {
        "surface": "を",
        "romaji": "wo",
        "meaning": "indicates direct object of an action",
        "pos": "particle",
        "skip": false
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "",
        "pos": "空白",
        "skip": true,
        "lookupWord": "",
        "baseForm": "",
        "conjugation": null
      },
      {
        "surface": "探して",
        "romaji": "sagashite",
        "meaning": "to search for; to look for; to hunt for; to seek",
        "pos": "verb",
        "skip": false,
        "lookupWord": "探す",
        "baseForm": "探す",
        "conjugation": "te-form"
      }
    ],
    "translation": "Searching for the answer that should exist in my unsatisfying daily life"
  },
  {
    "id": "l13",
    "start": 129.68,
    "end": 135.77,
    "tokens": [
      {
        "surface": "朝日",
        "romaji": "asahi",
        "meaning": "morning sun",
        "pos": "noun",
        "skip": false,
        "lookupWord": "朝日",
        "baseForm": "朝日",
        "conjugation": null
      },
      {
        "surface": "に",
        "romaji": "ni",
        "meaning": "indicates direction, destination, time, or target (to / at / in)",
        "pos": "particle",
        "skip": false
      },
      {
        "surface": "独り",
        "romaji": "hitori",
        "meaning": "one person",
        "pos": "noun",
        "skip": false,
        "lookupWord": "独り",
        "baseForm": "独り",
        "conjugation": null
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "",
        "pos": "空白",
        "skip": true,
        "lookupWord": "",
        "baseForm": "",
        "conjugation": null
      },
      {
        "surface": "柔らか",
        "romaji": "yawaraka",
        "meaning": "soft; tender; pliant; supple",
        "pos": "noun",
        "skip": false,
        "lookupWord": "柔らか",
        "baseForm": "柔らか",
        "conjugation": null
      },
      {
        "surface": "な",
        "romaji": "na",
        "meaning": "be; is",
        "pos": "auxiliary verb",
        "skip": false,
        "lookupWord": "だ",
        "baseForm": "だ",
        "conjugation": null
      },
      {
        "surface": "声",
        "romaji": "koe",
        "meaning": "voice",
        "pos": "noun",
        "skip": false,
        "lookupWord": "声",
        "baseForm": "声",
        "conjugation": null
      },
      {
        "surface": "に",
        "romaji": "ni",
        "meaning": "indicates direction, destination, time, or target (to / at / in)",
        "pos": "particle",
        "skip": false
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "",
        "pos": "空白",
        "skip": true,
        "lookupWord": "",
        "baseForm": "",
        "conjugation": null
      },
      {
        "surface": "振り向け",
        "romaji": "furimuke",
        "meaning": "to turn one's face; to turn around; to look over one's shoulder",
        "pos": "verb",
        "skip": false,
        "lookupWord": "振り向く",
        "baseForm": "振り向く",
        "conjugation": null
      },
      {
        "surface": "ば",
        "romaji": "ba",
        "meaning": "place; spot; space",
        "pos": "particle",
        "skip": false,
        "lookupWord": "ば",
        "baseForm": "ば",
        "conjugation": null
      }
    ],
    "translation": "Alone in the morning sun, when I turn to the soft voice,"
  },
  {
    "id": "l14",
    "start": 135.77,
    "end": 142.97,
    "tokens": [
      {
        "surface": "眩い",
        "romaji": "mabayui",
        "meaning": "dazzling; glaring; dazzlingly beautiful",
        "pos": "adjective",
        "skip": false,
        "lookupWord": "眩い",
        "baseForm": "眩い",
        "conjugation": null
      },
      {
        "surface": "日射し",
        "romaji": "hizashi",
        "meaning": "sunlight; rays of the Sun",
        "pos": "noun",
        "skip": false,
        "lookupWord": "日射し",
        "baseForm": "日射し",
        "conjugation": null
      },
      {
        "surface": "の",
        "romaji": "no",
        "meaning": "indicates possession or noun modification (of / 's)",
        "pos": "particle",
        "skip": false
      },
      {
        "surface": "中",
        "romaji": "naka",
        "meaning": "medium (size); average (grade, level, etc.); middle",
        "pos": "noun",
        "skip": false,
        "lookupWord": "中",
        "baseForm": "中",
        "conjugation": null
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "",
        "pos": "空白",
        "skip": true,
        "lookupWord": "",
        "baseForm": "",
        "conjugation": null
      },
      {
        "surface": "ふと",
        "romaji": "futo",
        "meaning": "suddenly; casually; accidentally; incidentally; unexpectedly; unintentionally",
        "pos": "adverb",
        "skip": false,
        "lookupWord": "ふと",
        "baseForm": "ふと",
        "conjugation": null
      },
      {
        "surface": "君",
        "romaji": "kimi",
        "meaning": "you; buddy; pal",
        "pos": "noun",
        "skip": false,
        "lookupWord": "君",
        "baseForm": "君",
        "conjugation": null
      },
      {
        "surface": "が",
        "romaji": "ga",
        "meaning": "indicates subject of a sentence",
        "pos": "particle",
        "skip": false
      },
      {
        "surface": "微笑む",
        "romaji": "hohoemu",
        "meaning": "to smile",
        "pos": "verb",
        "skip": false,
        "lookupWord": "微笑む",
        "baseForm": "微笑む",
        "conjugation": null
      }
    ],
    "translation": "In the bright sunlight, you suddenly smile"
  },
  {
    "id": "l15",
    "start": 142.97,
    "end": 149.57,
    "tokens": [
      {
        "surface": "閉ざした",
        "romaji": "tozashita",
        "meaning": "to shut; to close; to fasten; to lock",
        "pos": "verb",
        "skip": false,
        "lookupWord": "閉ざす",
        "baseForm": "閉ざす",
        "conjugation": "auxiliary / conjugated"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "",
        "pos": "空白",
        "skip": true,
        "lookupWord": "",
        "baseForm": "",
        "conjugation": null
      },
      {
        "surface": "窓",
        "romaji": "mado",
        "meaning": "window",
        "pos": "noun",
        "skip": false,
        "lookupWord": "窓",
        "baseForm": "窓",
        "conjugation": null
      },
      {
        "surface": "が",
        "romaji": "ga",
        "meaning": "indicates subject of a sentence",
        "pos": "particle",
        "skip": false
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "",
        "pos": "空白",
        "skip": true,
        "lookupWord": "",
        "baseForm": "",
        "conjugation": null
      },
      {
        "surface": "開き",
        "romaji": "hiraki",
        "meaning": "to open; to undo; to unseal; to unpack",
        "pos": "verb",
        "skip": false,
        "lookupWord": "開く",
        "baseForm": "開く",
        "conjugation": null
      },
      {
        "surface": "そう",
        "romaji": "sou",
        "meaning": "monk; priest",
        "pos": "noun",
        "skip": false,
        "lookupWord": "そう",
        "baseForm": "そう",
        "conjugation": null
      },
      {
        "surface": "に",
        "romaji": "ni",
        "meaning": "indicates direction, destination, time, or target (to / at / in)",
        "pos": "particle",
        "skip": false
      },
      {
        "surface": "なる",
        "romaji": "naru",
        "meaning": "to become; to get; to grow; to turn; to reach; to attain",
        "pos": "verb",
        "skip": false,
        "lookupWord": "なる",
        "baseForm": "なる",
        "conjugation": null
      }
    ],
    "translation": "The closed window feels like it's about to open"
  },
  {
    "id": "l16",
    "start": 149.57,
    "end": 157.34,
    "tokens": [
      {
        "surface": "自分",
        "romaji": "jibun",
        "meaning": "myself; yourself; oneself; himself; herself",
        "pos": "noun",
        "skip": false,
        "lookupWord": "自分",
        "baseForm": "自分",
        "conjugation": null
      },
      {
        "surface": "を",
        "romaji": "wo",
        "meaning": "indicates direct object of an action",
        "pos": "particle",
        "skip": false
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "",
        "pos": "空白",
        "skip": true,
        "lookupWord": "",
        "baseForm": "",
        "conjugation": null
      },
      {
        "surface": "世界",
        "romaji": "sekai",
        "meaning": "the world; society; the universe",
        "pos": "noun",
        "skip": false,
        "lookupWord": "世界",
        "baseForm": "世界",
        "conjugation": null
      },
      {
        "surface": "さえ",
        "romaji": "sae",
        "meaning": "even",
        "pos": "particle",
        "skip": false,
        "lookupWord": "さえ",
        "baseForm": "さえ",
        "conjugation": null
      },
      {
        "surface": "も",
        "romaji": "mo",
        "meaning": "indicates addition or inclusion (also / too / as well)",
        "pos": "particle",
        "skip": false
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "",
        "pos": "空白",
        "skip": true,
        "lookupWord": "",
        "baseForm": "",
        "conjugation": null
      },
      {
        "surface": "変えて",
        "romaji": "kaete",
        "meaning": "to change; to alter; to transform; to convert; to turn; to vary",
        "pos": "verb",
        "skip": false,
        "lookupWord": "変える",
        "baseForm": "変える",
        "conjugation": "te-form"
      },
      {
        "surface": "しまえ",
        "romaji": "shimae",
        "meaning": "to finish; to stop; to end; to put an end to; to bring to a close",
        "pos": "verb",
        "skip": false,
        "lookupWord": "しまう",
        "baseForm": "しまう",
        "conjugation": null
      },
      {
        "surface": "そう",
        "romaji": "sou",
        "meaning": "monk; priest",
        "pos": "adverb",
        "skip": false,
        "lookupWord": "そう",
        "baseForm": "そう",
        "conjugation": null
      },
      {
        "surface": "な",
        "romaji": "na",
        "meaning": "don't",
        "pos": "particle",
        "skip": false,
        "lookupWord": "な",
        "baseForm": "な",
        "conjugation": null
      }
    ],
    "translation": "I feel like I can change myself and even the world"
  },
  {
    "id": "l17",
    "start": 157.34,
    "end": 164.21,
    "tokens": [
      {
        "surface": "存在",
        "romaji": "sonzai",
        "meaning": "existence; being; presence",
        "pos": "noun",
        "skip": false,
        "lookupWord": "存在",
        "baseForm": "存在",
        "conjugation": null
      },
      {
        "surface": "は",
        "romaji": "ha",
        "meaning": "indicates topic of a sentence",
        "pos": "particle",
        "skip": false
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "",
        "pos": "空白",
        "skip": true,
        "lookupWord": "",
        "baseForm": "",
        "conjugation": null
      },
      {
        "surface": "僕",
        "romaji": "boku",
        "meaning": "I; me",
        "pos": "noun",
        "skip": false,
        "lookupWord": "僕",
        "baseForm": "僕",
        "conjugation": null
      },
      {
        "surface": "の",
        "romaji": "no",
        "meaning": "indicates possession or noun modification (of / 's)",
        "pos": "particle",
        "skip": false
      },
      {
        "surface": "目",
        "romaji": "me",
        "meaning": "eye; eyeball",
        "pos": "noun",
        "skip": false,
        "lookupWord": "目",
        "baseForm": "目",
        "conjugation": null
      },
      {
        "surface": "の",
        "romaji": "no",
        "meaning": "indicates possession or noun modification (of / 's)",
        "pos": "particle",
        "skip": false
      },
      {
        "surface": "前",
        "romaji": "mae",
        "meaning": "last (i.e. immediately preceding); previous; ex-; former",
        "pos": "noun",
        "skip": false,
        "lookupWord": "前",
        "baseForm": "前",
        "conjugation": null
      },
      {
        "surface": "に",
        "romaji": "ni",
        "meaning": "indicates direction, destination, time, or target (to / at / in)",
        "pos": "particle",
        "skip": false
      },
      {
        "surface": "...",
        "romaji": "...",
        "meaning": "",
        "pos": "noun",
        "skip": true,
        "lookupWord": "",
        "baseForm": "",
        "conjugation": null
      }
    ],
    "translation": "Existence is right in front of my eyes.."
  },
  {
    "id": "l18",
    "start": 164.21,
    "end": 171.04,
    "tokens": [
      {
        "surface": "見上げた",
        "romaji": "miageta",
        "meaning": "to look up at; to raise one's eyes",
        "pos": "verb",
        "skip": false,
        "lookupWord": "見上げる",
        "baseForm": "見上げる",
        "conjugation": "auxiliary / conjugated"
      },
      {
        "surface": "大空",
        "romaji": "oozora",
        "meaning": "wide open sky; the blue; heavens; firmament",
        "pos": "noun",
        "skip": false,
        "lookupWord": "大空",
        "baseForm": "大空",
        "conjugation": null
      },
      {
        "surface": "が",
        "romaji": "ga",
        "meaning": "indicates subject of a sentence",
        "pos": "particle",
        "skip": false
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "",
        "pos": "空白",
        "skip": true,
        "lookupWord": "",
        "baseForm": "",
        "conjugation": null
      },
      {
        "surface": "青く",
        "romaji": "aoku",
        "meaning": "blue; azure",
        "pos": "adjective",
        "skip": false,
        "lookupWord": "青い",
        "baseForm": "青い",
        "conjugation": null
      },
      {
        "surface": "澄み切って",
        "romaji": "sumikite",
        "meaning": "to be perfectly clear (water, air, etc.); to clear up",
        "pos": "verb",
        "skip": false,
        "lookupWord": "澄み切る",
        "baseForm": "澄み切る",
        "conjugation": "te-form"
      },
      {
        "surface": "行く",
        "romaji": "iku",
        "meaning": "to go; to move (towards); to head (towards); to leave (for)",
        "pos": "verb",
        "skip": false,
        "lookupWord": "行く",
        "baseForm": "行く",
        "conjugation": null
      }
    ],
    "translation": "The sky I looked up at becomes clear and blue"
  },
  {
    "id": "l19",
    "start": 171.04,
    "end": 177.81,
    "tokens": [
      {
        "surface": "閉ざした",
        "romaji": "tozashita",
        "meaning": "to shut; to close; to fasten; to lock",
        "pos": "verb",
        "skip": false,
        "lookupWord": "閉ざす",
        "baseForm": "閉ざす",
        "conjugation": "auxiliary / conjugated"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "",
        "pos": "空白",
        "skip": true,
        "lookupWord": "",
        "baseForm": "",
        "conjugation": null
      },
      {
        "surface": "窓",
        "romaji": "mado",
        "meaning": "window",
        "pos": "noun",
        "skip": false,
        "lookupWord": "窓",
        "baseForm": "窓",
        "conjugation": null
      },
      {
        "surface": "を",
        "romaji": "wo",
        "meaning": "indicates direct object of an action",
        "pos": "particle",
        "skip": false
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "",
        "pos": "空白",
        "skip": true,
        "lookupWord": "",
        "baseForm": "",
        "conjugation": null
      },
      {
        "surface": "開く",
        "romaji": "hiraku",
        "meaning": "to open; to undo; to unseal; to unpack",
        "pos": "verb",
        "skip": false,
        "lookupWord": "開く",
        "baseForm": "開く",
        "conjugation": null
      },
      {
        "surface": "事",
        "romaji": "koto",
        "meaning": "thing; matter",
        "pos": "noun",
        "skip": false,
        "lookupWord": "事",
        "baseForm": "事",
        "conjugation": null
      },
      {
        "surface": "を",
        "romaji": "wo",
        "meaning": "indicates direct object of an action",
        "pos": "particle",
        "skip": false
      },
      {
        "surface": "決めた",
        "romaji": "kimeta",
        "meaning": "to decide; to choose; to determine; to make up one's mind; to resolve; to set one's heart on; to settle; to arrange; to set; to appoint; to fix",
        "pos": "verb",
        "skip": false,
        "lookupWord": "決める",
        "baseForm": "決める",
        "conjugation": "auxiliary / conjugated"
      }
    ],
    "translation": "I decided to open the closed window"
  },
  {
    "id": "l20",
    "start": 177.81,
    "end": 185.42,
    "tokens": [
      {
        "surface": "自分",
        "romaji": "jibun",
        "meaning": "myself; yourself; oneself; himself; herself",
        "pos": "noun",
        "skip": false,
        "lookupWord": "自分",
        "baseForm": "自分",
        "conjugation": null
      },
      {
        "surface": "を",
        "romaji": "wo",
        "meaning": "indicates direct object of an action",
        "pos": "particle",
        "skip": false
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "",
        "pos": "空白",
        "skip": true,
        "lookupWord": "",
        "baseForm": "",
        "conjugation": null
      },
      {
        "surface": "世界",
        "romaji": "sekai",
        "meaning": "the world; society; the universe",
        "pos": "noun",
        "skip": false,
        "lookupWord": "世界",
        "baseForm": "世界",
        "conjugation": null
      },
      {
        "surface": "さえ",
        "romaji": "sae",
        "meaning": "even",
        "pos": "particle",
        "skip": false,
        "lookupWord": "さえ",
        "baseForm": "さえ",
        "conjugation": null
      },
      {
        "surface": "も",
        "romaji": "mo",
        "meaning": "indicates addition or inclusion (also / too / as well)",
        "pos": "particle",
        "skip": false
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "",
        "pos": "空白",
        "skip": true,
        "lookupWord": "",
        "baseForm": "",
        "conjugation": null
      },
      {
        "surface": "変えて",
        "romaji": "kaete",
        "meaning": "to change; to alter; to transform; to convert; to turn; to vary",
        "pos": "verb",
        "skip": false,
        "lookupWord": "変える",
        "baseForm": "変える",
        "conjugation": "te-form"
      },
      {
        "surface": "しまえ",
        "romaji": "shimae",
        "meaning": "to finish; to stop; to end; to put an end to; to bring to a close",
        "pos": "verb",
        "skip": false,
        "lookupWord": "しまう",
        "baseForm": "しまう",
        "conjugation": null
      },
      {
        "surface": "そう",
        "romaji": "sou",
        "meaning": "monk; priest",
        "pos": "adverb",
        "skip": false,
        "lookupWord": "そう",
        "baseForm": "そう",
        "conjugation": null
      },
      {
        "surface": "な",
        "romaji": "na",
        "meaning": "don't",
        "pos": "particle",
        "skip": false,
        "lookupWord": "な",
        "baseForm": "な",
        "conjugation": null
      }
    ],
    "translation": "I feel like I can change myself and even the world"
  },
  {
    "id": "l21",
    "start": 185.42,
    "end": 192.24,
    "tokens": [
      {
        "surface": "瞬間",
        "romaji": "shunkan",
        "meaning": "moment; instant; second",
        "pos": "noun",
        "skip": false,
        "lookupWord": "瞬間",
        "baseForm": "瞬間",
        "conjugation": null
      },
      {
        "surface": "を",
        "romaji": "wo",
        "meaning": "indicates direct object of an action",
        "pos": "particle",
        "skip": false
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "",
        "pos": "空白",
        "skip": true,
        "lookupWord": "",
        "baseForm": "",
        "conjugation": null
      },
      {
        "surface": "感じる",
        "romaji": "kanjiru",
        "meaning": "to feel; to sense; to experience",
        "pos": "verb",
        "skip": false,
        "lookupWord": "感じる",
        "baseForm": "感じる",
        "conjugation": null
      },
      {
        "surface": "今",
        "romaji": "ima",
        "meaning": "now; the present time; just now; soon; immediately",
        "pos": "noun",
        "skip": false,
        "lookupWord": "今",
        "baseForm": "今",
        "conjugation": null
      },
      {
        "surface": "ここ",
        "romaji": "koko",
        "meaning": "individual; one by one; separate; each",
        "pos": "noun",
        "skip": false,
        "lookupWord": "ここ",
        "baseForm": "ここ",
        "conjugation": null
      },
      {
        "surface": "に",
        "romaji": "ni",
        "meaning": "indicates direction, destination, time, or target (to / at / in)",
        "pos": "particle",
        "skip": false
      },
      {
        "surface": "...",
        "romaji": "...",
        "meaning": "",
        "pos": "noun",
        "skip": true,
        "lookupWord": "",
        "baseForm": "",
        "conjugation": null
      }
    ],
    "translation": "Here I am, feeling the moment.."
  },
  {
    "id": "l22",
    "start": 192.24,
    "end": 199.94,
    "tokens": [
      {
        "surface": "光",
        "romaji": "hikari",
        "meaning": "light",
        "pos": "noun",
        "skip": false,
        "lookupWord": "光",
        "baseForm": "光",
        "conjugation": null
      },
      {
        "surface": "へ",
        "romaji": "he",
        "meaning": "indicates direction or goal (towards / to)",
        "pos": "particle",
        "skip": false
      },
      {
        "surface": "と",
        "romaji": "to",
        "meaning": "indicates togetherness or quotation (and / with)",
        "pos": "particle",
        "skip": false
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "",
        "pos": "空白",
        "skip": true,
        "lookupWord": "",
        "baseForm": "",
        "conjugation": null
      },
      {
        "surface": "両手",
        "romaji": "ryoute",
        "meaning": "both hands; both arms",
        "pos": "noun",
        "skip": false,
        "lookupWord": "両手",
        "baseForm": "両手",
        "conjugation": null
      },
      {
        "surface": "を",
        "romaji": "wo",
        "meaning": "indicates direct object of an action",
        "pos": "particle",
        "skip": false
      },
      {
        "surface": "伸ばして",
        "romaji": "nobashite",
        "meaning": "to grow long (e.g. hair, nails)",
        "pos": "verb",
        "skip": false,
        "lookupWord": "伸ばす",
        "baseForm": "伸ばす",
        "conjugation": "te-form"
      },
      {
        "surface": "...",
        "romaji": "...",
        "meaning": "",
        "pos": "noun",
        "skip": true,
        "lookupWord": "",
        "baseForm": "",
        "conjugation": null
      }
    ],
    "translation": "Reach out your hands towards the light.."
  },
  {
    "id": "l23",
    "start": 199.94,
    "end": 203.94,
    "tokens": [
      {
        "surface": "心",
        "romaji": "kokoro",
        "meaning": "mind; heart; spirit",
        "pos": "noun",
        "skip": false,
        "lookupWord": "心",
        "baseForm": "心",
        "conjugation": null
      },
      {
        "surface": "を",
        "romaji": "wo",
        "meaning": "indicates direct object of an action",
        "pos": "particle",
        "skip": false
      },
      {
        "surface": "吹き抜ける",
        "romaji": "fukinukeru",
        "meaning": "to blow through; to blow across",
        "pos": "verb",
        "skip": false,
        "lookupWord": "吹き抜ける",
        "baseForm": "吹き抜ける",
        "conjugation": null
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "",
        "pos": "空白",
        "skip": true,
        "lookupWord": "",
        "baseForm": "",
        "conjugation": null
      },
      {
        "surface": "空",
        "romaji": "sora",
        "meaning": "sky; the air; the heavens",
        "pos": "noun",
        "skip": false,
        "lookupWord": "空",
        "baseForm": "空",
        "conjugation": null
      },
      {
        "surface": "の",
        "romaji": "no",
        "meaning": "indicates possession or noun modification (of / 's)",
        "pos": "particle",
        "skip": false
      },
      {
        "surface": "色",
        "romaji": "iro",
        "meaning": "colour; color; hue; tint; tinge; shade",
        "pos": "noun",
        "skip": false,
        "lookupWord": "色",
        "baseForm": "色",
        "conjugation": null
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "",
        "pos": "空白",
        "skip": true,
        "lookupWord": "",
        "baseForm": "",
        "conjugation": null
      },
      {
        "surface": "香る",
        "romaji": "kaoru",
        "meaning": "to smell sweet; to be fragrant",
        "pos": "verb",
        "skip": false,
        "lookupWord": "香る",
        "baseForm": "香る",
        "conjugation": null
      },
      {
        "surface": "風",
        "romaji": "kaze",
        "meaning": "wind; breeze; draught; draft",
        "pos": "noun",
        "skip": false,
        "lookupWord": "風",
        "baseForm": "風",
        "conjugation": null
      }
    ],
    "translation": "The color of the sky and the fragrant wind that blows through your heart"
  }
];
