import { LyricLine } from "@/lib/types";

// Auto-generated by scripts/generate-lyrics.mjs for "groovin magic" by nino.
// Words come from kuromoji (segmentation), wanakana (romaji), and Jisho
// (dictionary meanings) — spot-check before shipping, don't trust blindly.
export const groovinMagicLyrics: LyricLine[] = [
  {
    "id": "l1",
    "start": 4.27,
    "end": 7.36,
    "tokens": [
      {
        "surface": "Groovin",
        "romaji": "Groovin",
        "meaning": "",
        "pos": "noun",
        "skip": true,
        "lookupWord": "",
        "baseForm": "",
        "conjugation": null
      },
      {
        "surface": "'",
        "romaji": "'",
        "meaning": "",
        "pos": "noun",
        "skip": true,
        "lookupWord": "",
        "baseForm": "",
        "conjugation": null
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "",
        "pos": "空白",
        "skip": true,
        "lookupWord": "",
        "baseForm": "",
        "conjugation": null
      },
      {
        "surface": "Magic",
        "romaji": "Magic",
        "meaning": "",
        "pos": "noun",
        "skip": true,
        "lookupWord": "",
        "baseForm": "",
        "conjugation": null
      }
    ],
    "translation": ""
  },
  {
    "id": "l2",
    "start": 7.36,
    "end": 10.75,
    "tokens": [
      {
        "surface": "寄り",
        "romaji": "yori",
        "meaning": "to approach; to draw near; to come near; to be close to",
        "pos": "verb",
        "skip": false,
        "lookupWord": "寄る",
        "baseForm": "寄る",
        "conjugation": null
      },
      {
        "surface": "そえ",
        "romaji": "soe",
        "meaning": "monk; priest",
        "pos": "verb",
        "skip": false,
        "lookupWord": "そう",
        "baseForm": "そう",
        "conjugation": null
      },
      {
        "surface": "ば",
        "romaji": "ba",
        "meaning": "place; spot; space",
        "pos": "particle",
        "skip": false,
        "lookupWord": "ば",
        "baseForm": "ば",
        "conjugation": null
      },
      {
        "surface": "いつ",
        "romaji": "itsu",
        "meaning": "when; at what time; how soon",
        "pos": "noun",
        "skip": false,
        "lookupWord": "いつ",
        "baseForm": "いつ",
        "conjugation": null
      },
      {
        "surface": "で",
        "romaji": "de",
        "meaning": "indicates location of action, means, or method (at / by / with)",
        "pos": "particle",
        "skip": false
      },
      {
        "surface": "も",
        "romaji": "mo",
        "meaning": "indicates addition or inclusion (also / too / as well)",
        "pos": "particle",
        "skip": false
      }
    ],
    "translation": "Whenever I get close to you"
  },
  {
    "id": "l3",
    "start": 10.75,
    "end": 14.63,
    "tokens": [
      {
        "surface": "きつく",
        "romaji": "kitsuku",
        "meaning": "tough; hard; severe; demanding; harsh",
        "pos": "adjective",
        "skip": false,
        "lookupWord": "きつい",
        "baseForm": "きつい",
        "conjugation": null
      },
      {
        "surface": "結んだ",
        "romaji": "musunda",
        "meaning": "to tie; to bind; to link",
        "pos": "verb",
        "skip": false,
        "lookupWord": "結ぶ",
        "baseForm": "結ぶ",
        "conjugation": "auxiliary / conjugated"
      },
      {
        "surface": "靴",
        "romaji": "kutsu",
        "meaning": "shoe; shoes; boots; footwear; footgear",
        "pos": "noun",
        "skip": false,
        "lookupWord": "靴",
        "baseForm": "靴",
        "conjugation": null
      },
      {
        "surface": "紐",
        "romaji": "himo",
        "meaning": "string; cord",
        "pos": "noun",
        "skip": false,
        "lookupWord": "紐",
        "baseForm": "紐",
        "conjugation": null
      },
      {
        "surface": "が",
        "romaji": "ga",
        "meaning": "indicates subject of a sentence",
        "pos": "particle",
        "skip": false
      }
    ],
    "translation": "Tightly tied shoelaces"
  },
  {
    "id": "l4",
    "start": 14.63,
    "end": 18.25,
    "tokens": [
      {
        "surface": "胸",
        "romaji": "mune",
        "meaning": "chest; breast",
        "pos": "noun",
        "skip": false,
        "lookupWord": "胸",
        "baseForm": "胸",
        "conjugation": null
      },
      {
        "surface": "を",
        "romaji": "wo",
        "meaning": "indicates direct object of an action",
        "pos": "particle",
        "skip": false
      },
      {
        "surface": "キュン",
        "romaji": "kyun",
        "meaning": "with a pitter-patter; choked up (with emotion); heart-wringing; momentary tightening of one's chest caused by powerful feelings (e.g. parting with a loved one)",
        "pos": "noun",
        "skip": false,
        "lookupWord": "キュン",
        "baseForm": "キュン",
        "conjugation": null
      },
      {
        "surface": "と",
        "romaji": "to",
        "meaning": "indicates togetherness or quotation (and / with)",
        "pos": "particle",
        "skip": false
      },
      {
        "surface": "さ",
        "romaji": "sa",
        "meaning": "to do; to carry out; to perform",
        "pos": "verb",
        "skip": false,
        "lookupWord": "する",
        "baseForm": "する",
        "conjugation": null
      },
      {
        "surface": "せる",
        "romaji": "seru",
        "meaning": "cell",
        "pos": "verb",
        "skip": false,
        "lookupWord": "せる",
        "baseForm": "せる",
        "conjugation": null
      }
    ],
    "translation": "Make my heart flutter"
  },
  {
    "id": "l5",
    "start": 18.25,
    "end": 34.94,
    "tokens": [
      {
        "surface": "Uh",
        "romaji": "Uh",
        "meaning": "",
        "pos": "noun",
        "skip": true,
        "lookupWord": "",
        "baseForm": "",
        "conjugation": null
      },
      {
        "surface": "～",
        "romaji": "～",
        "meaning": "",
        "pos": "noun",
        "skip": true,
        "lookupWord": "",
        "baseForm": "",
        "conjugation": null
      }
    ],
    "translation": ""
  },
  {
    "id": "l6",
    "start": 34.94,
    "end": 37.9,
    "tokens": [
      {
        "surface": "背",
        "romaji": "se",
        "meaning": "back",
        "pos": "noun",
        "skip": false,
        "lookupWord": "背",
        "baseForm": "背",
        "conjugation": null
      },
      {
        "surface": "の",
        "romaji": "no",
        "meaning": "indicates possession or noun modification (of / 's)",
        "pos": "particle",
        "skip": false
      },
      {
        "surface": "高い",
        "romaji": "takai",
        "meaning": "high; tall",
        "pos": "adjective",
        "skip": false,
        "lookupWord": "高い",
        "baseForm": "高い",
        "conjugation": null
      },
      {
        "surface": "あなた",
        "romaji": "anata",
        "meaning": "you",
        "pos": "noun",
        "skip": false,
        "lookupWord": "あなた",
        "baseForm": "あなた",
        "conjugation": null
      },
      {
        "surface": "が",
        "romaji": "ga",
        "meaning": "indicates subject of a sentence",
        "pos": "particle",
        "skip": false
      }
    ],
    "translation": "You are tall"
  },
  {
    "id": "l7",
    "start": 37.9,
    "end": 41.96,
    "tokens": [
      {
        "surface": "見下ろして",
        "romaji": "mioroshite",
        "meaning": "to overlook; to command a view of; to look down on",
        "pos": "verb",
        "skip": false,
        "lookupWord": "見下ろす",
        "baseForm": "見下ろす",
        "conjugation": "te-form"
      },
      {
        "surface": "いる",
        "romaji": "iru",
        "meaning": "to be (of animate objects); to exist",
        "pos": "verb",
        "skip": false,
        "lookupWord": "いる",
        "baseForm": "いる",
        "conjugation": null
      },
      {
        "surface": "の",
        "romaji": "no",
        "meaning": "indicates possession or noun modification (of / 's)",
        "pos": "particle",
        "skip": false
      },
      {
        "surface": "よ",
        "romaji": "yo",
        "meaning": "indicates new information or emphasis (you know)",
        "pos": "particle",
        "skip": false
      }
    ],
    "translation": "I'm looking down"
  },
  {
    "id": "l8",
    "start": 41.96,
    "end": 45.57,
    "tokens": [
      {
        "surface": "そっと",
        "romaji": "sotto",
        "meaning": "softly; gently; quietly; lightly",
        "pos": "adverb",
        "skip": false,
        "lookupWord": "そっと",
        "baseForm": "そっと",
        "conjugation": null
      },
      {
        "surface": "髮",
        "romaji": "髮",
        "meaning": "hair (on the head)",
        "pos": "noun",
        "skip": false,
        "lookupWord": "髮",
        "baseForm": "髮",
        "conjugation": null
      },
      {
        "surface": "を",
        "romaji": "wo",
        "meaning": "indicates direct object of an action",
        "pos": "particle",
        "skip": false
      },
      {
        "surface": "なでる",
        "romaji": "naderu",
        "meaning": "to stroke; to caress; to brush gently; to pet; to pat; to rub",
        "pos": "verb",
        "skip": false,
        "lookupWord": "なでる",
        "baseForm": "なでる",
        "conjugation": null
      },
      {
        "surface": "ふり",
        "romaji": "furi",
        "meaning": "swing; shake; sweep; wave; wag",
        "pos": "noun",
        "skip": false,
        "lookupWord": "ふり",
        "baseForm": "ふり",
        "conjugation": null
      },
      {
        "surface": "を",
        "romaji": "wo",
        "meaning": "indicates direct object of an action",
        "pos": "particle",
        "skip": false
      },
      {
        "surface": "して",
        "romaji": "shite",
        "meaning": "to do; to carry out; to perform",
        "pos": "verb",
        "skip": false,
        "lookupWord": "する",
        "baseForm": "する",
        "conjugation": "te-form"
      }
    ],
    "translation": "Pretend to gently stroke your hair"
  },
  {
    "id": "l9",
    "start": 45.57,
    "end": 51.11,
    "tokens": [
      {
        "surface": "近づいて",
        "romaji": "chikazuite",
        "meaning": "to approach; to draw near; to get close",
        "pos": "verb",
        "skip": false,
        "lookupWord": "近づく",
        "baseForm": "近づく",
        "conjugation": "te-form"
      },
      {
        "surface": "氣",
        "romaji": "氣",
        "meaning": "spirit; mind; heart",
        "pos": "noun",
        "skip": false,
        "lookupWord": "氣",
        "baseForm": "氣",
        "conjugation": null
      },
      {
        "surface": "を",
        "romaji": "wo",
        "meaning": "indicates direct object of an action",
        "pos": "particle",
        "skip": false
      },
      {
        "surface": "引きたい",
        "romaji": "hikitai",
        "meaning": "to pull; to tug; to lead (e.g. a horse)",
        "pos": "verb",
        "skip": false,
        "lookupWord": "引く",
        "baseForm": "引く",
        "conjugation": "auxiliary / conjugated"
      },
      {
        "surface": "の",
        "romaji": "no",
        "meaning": "indicates possession or noun modification (of / 's)",
        "pos": "particle",
        "skip": false
      }
    ],
    "translation": "I want to get closer and catch your attention"
  },
  {
    "id": "l10",
    "start": 51.11,
    "end": 54.38,
    "tokens": [
      {
        "surface": "どう",
        "romaji": "dou",
        "meaning": "copper (Cu)",
        "pos": "adverb",
        "skip": false,
        "lookupWord": "どう",
        "baseForm": "どう",
        "conjugation": null
      },
      {
        "surface": "した",
        "romaji": "shita",
        "meaning": "to do; to carry out; to perform",
        "pos": "verb",
        "skip": false,
        "lookupWord": "する",
        "baseForm": "する",
        "conjugation": "auxiliary / conjugated"
      },
      {
        "surface": "の",
        "romaji": "no",
        "meaning": "indicates possession or noun modification (of / 's)",
        "pos": "particle",
        "skip": false
      },
      {
        "surface": "？",
        "romaji": "?",
        "meaning": "",
        "pos": "一般",
        "skip": true,
        "lookupWord": "",
        "baseForm": "",
        "conjugation": null
      },
      {
        "surface": "って",
        "romaji": "tte",
        "meaning": "you said; he said; she said; they said",
        "pos": "particle",
        "skip": false,
        "lookupWord": "って",
        "baseForm": "って",
        "conjugation": null
      }
    ],
    "translation": "What happened? That's it"
  },
  {
    "id": "l11",
    "start": 54.38,
    "end": 56.75,
    "tokens": [
      {
        "surface": "じらさないで",
        "romaji": "jirasanaide",
        "meaning": "to tease; to irritate; to tantalize; to keep (someone) in suspense",
        "pos": "verb",
        "skip": false,
        "lookupWord": "じらす",
        "baseForm": "じらす",
        "conjugation": "te-form"
      }
    ],
    "translation": "Don't tease me"
  },
  {
    "id": "l12",
    "start": 56.75,
    "end": 59.41,
    "tokens": [
      {
        "surface": "戀",
        "romaji": "戀",
        "meaning": "(romantic) love",
        "pos": "noun",
        "skip": false,
        "lookupWord": "戀",
        "baseForm": "戀",
        "conjugation": null
      },
      {
        "surface": "の",
        "romaji": "no",
        "meaning": "indicates possession or noun modification (of / 's)",
        "pos": "particle",
        "skip": false
      },
      {
        "surface": "カウントダウン",
        "romaji": "kauntodaun",
        "meaning": "countdown",
        "pos": "noun",
        "skip": false,
        "lookupWord": "カウントダウン",
        "baseForm": "カウントダウン",
        "conjugation": null
      }
    ],
    "translation": "Countdown of love"
  },
  {
    "id": "l13",
    "start": 59.41,
    "end": 62.03,
    "tokens": [
      {
        "surface": "準備",
        "romaji": "junbi",
        "meaning": "preparation; arrangements; getting ready; provision; setup; reserving",
        "pos": "noun",
        "skip": false,
        "lookupWord": "準備",
        "baseForm": "準備",
        "conjugation": null
      },
      {
        "surface": "は",
        "romaji": "ha",
        "meaning": "indicates topic of a sentence",
        "pos": "particle",
        "skip": false
      },
      {
        "surface": "いつ",
        "romaji": "itsu",
        "meaning": "when; at what time; how soon",
        "pos": "noun",
        "skip": false,
        "lookupWord": "いつ",
        "baseForm": "いつ",
        "conjugation": null
      },
      {
        "surface": "でも",
        "romaji": "demo",
        "meaning": "but; however; though; nevertheless; still; yet; even so; also; as well",
        "pos": "particle",
        "skip": false,
        "lookupWord": "でも",
        "baseForm": "でも",
        "conjugation": null
      },
      {
        "surface": "OK",
        "romaji": "OK",
        "meaning": "",
        "pos": "noun",
        "skip": true,
        "lookupWord": "",
        "baseForm": "",
        "conjugation": null
      }
    ],
    "translation": "Ready anytime"
  },
  {
    "id": "l14",
    "start": 62.03,
    "end": 63.81,
    "tokens": [
      {
        "surface": "3",
        "romaji": "3",
        "meaning": "",
        "pos": "noun",
        "skip": true,
        "lookupWord": "",
        "baseForm": "",
        "conjugation": null
      },
      {
        "surface": "．",
        "romaji": "．",
        "meaning": "",
        "pos": "noun",
        "skip": true,
        "lookupWord": "",
        "baseForm": "",
        "conjugation": null
      },
      {
        "surface": "2",
        "romaji": "2",
        "meaning": "",
        "pos": "noun",
        "skip": true,
        "lookupWord": "",
        "baseForm": "",
        "conjugation": null
      },
      {
        "surface": "．",
        "romaji": "．",
        "meaning": "",
        "pos": "noun",
        "skip": true,
        "lookupWord": "",
        "baseForm": "",
        "conjugation": null
      },
      {
        "surface": "1",
        "romaji": "1",
        "meaning": "",
        "pos": "noun",
        "skip": true,
        "lookupWord": "",
        "baseForm": "",
        "conjugation": null
      },
      {
        "surface": "二",
        "romaji": "ni",
        "meaning": "two; 2",
        "pos": "noun",
        "skip": false,
        "lookupWord": "二",
        "baseForm": "二",
        "conjugation": null
      },
      {
        "surface": "人",
        "romaji": "nin",
        "meaning": "person; someone; somebody",
        "pos": "noun",
        "skip": false,
        "lookupWord": "人",
        "baseForm": "人",
        "conjugation": null
      },
      {
        "surface": "は",
        "romaji": "ha",
        "meaning": "indicates topic of a sentence",
        "pos": "particle",
        "skip": false
      }
    ],
    "translation": "3.2.1 The two of them"
  },
  {
    "id": "l15",
    "start": 63.81,
    "end": 66.47,
    "tokens": [
      {
        "surface": "Groovin",
        "romaji": "Groovin",
        "meaning": "",
        "pos": "noun",
        "skip": true,
        "lookupWord": "",
        "baseForm": "",
        "conjugation": null
      },
      {
        "surface": "'",
        "romaji": "'",
        "meaning": "",
        "pos": "noun",
        "skip": true,
        "lookupWord": "",
        "baseForm": "",
        "conjugation": null
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "",
        "pos": "空白",
        "skip": true,
        "lookupWord": "",
        "baseForm": "",
        "conjugation": null
      },
      {
        "surface": "Magic",
        "romaji": "Magic",
        "meaning": "",
        "pos": "noun",
        "skip": true,
        "lookupWord": "",
        "baseForm": "",
        "conjugation": null
      }
    ],
    "translation": ""
  },
  {
    "id": "l16",
    "start": 66.47,
    "end": 69.89,
    "tokens": [
      {
        "surface": "ソーダ",
        "romaji": "sooda",
        "meaning": "soda",
        "pos": "noun",
        "skip": false,
        "lookupWord": "ソーダ",
        "baseForm": "ソーダ",
        "conjugation": null
      },
      {
        "surface": "水",
        "romaji": "sui",
        "meaning": "water (esp. cool or cold)",
        "pos": "noun",
        "skip": false,
        "lookupWord": "水",
        "baseForm": "水",
        "conjugation": null
      },
      {
        "surface": "に",
        "romaji": "ni",
        "meaning": "indicates direction, destination, time, or target (to / at / in)",
        "pos": "particle",
        "skip": false
      },
      {
        "surface": "とける",
        "romaji": "tokeru",
        "meaning": "to be solved; to be worked out",
        "pos": "verb",
        "skip": false,
        "lookupWord": "とける",
        "baseForm": "とける",
        "conjugation": null
      }
    ],
    "translation": "Dissolves in soda water"
  },
  {
    "id": "l17",
    "start": 69.89,
    "end": 73.79,
    "tokens": [
      {
        "surface": "甘く",
        "romaji": "amaku",
        "meaning": "sweet-tasting; sweet; sugary; sugared",
        "pos": "adjective",
        "skip": false,
        "lookupWord": "甘い",
        "baseForm": "甘い",
        "conjugation": null
      },
      {
        "surface": "切ない",
        "romaji": "setsunai",
        "meaning": "painful; heartrending; trying",
        "pos": "adjective",
        "skip": false,
        "lookupWord": "切ない",
        "baseForm": "切ない",
        "conjugation": null
      },
      {
        "surface": "戀",
        "romaji": "戀",
        "meaning": "(romantic) love",
        "pos": "noun",
        "skip": false,
        "lookupWord": "戀",
        "baseForm": "戀",
        "conjugation": null
      },
      {
        "surface": "の",
        "romaji": "no",
        "meaning": "indicates possession or noun modification (of / 's)",
        "pos": "particle",
        "skip": false
      },
      {
        "surface": "色",
        "romaji": "iro",
        "meaning": "colour; color; hue; tint; tinge; shade",
        "pos": "noun",
        "skip": false,
        "lookupWord": "色",
        "baseForm": "色",
        "conjugation": null
      }
    ],
    "translation": "The sweet and painful color of love"
  },
  {
    "id": "l18",
    "start": 73.79,
    "end": 76.79,
    "tokens": [
      {
        "surface": "胸",
        "romaji": "mune",
        "meaning": "chest; breast",
        "pos": "noun",
        "skip": false,
        "lookupWord": "胸",
        "baseForm": "胸",
        "conjugation": null
      },
      {
        "surface": "を",
        "romaji": "wo",
        "meaning": "indicates direct object of an action",
        "pos": "particle",
        "skip": false
      },
      {
        "surface": "キュン",
        "romaji": "kyun",
        "meaning": "with a pitter-patter; choked up (with emotion); heart-wringing; momentary tightening of one's chest caused by powerful feelings (e.g. parting with a loved one)",
        "pos": "noun",
        "skip": false,
        "lookupWord": "キュン",
        "baseForm": "キュン",
        "conjugation": null
      },
      {
        "surface": "と",
        "romaji": "to",
        "meaning": "indicates togetherness or quotation (and / with)",
        "pos": "particle",
        "skip": false
      },
      {
        "surface": "さ",
        "romaji": "sa",
        "meaning": "to do; to carry out; to perform",
        "pos": "verb",
        "skip": false,
        "lookupWord": "する",
        "baseForm": "する",
        "conjugation": null
      },
      {
        "surface": "せる",
        "romaji": "seru",
        "meaning": "cell",
        "pos": "verb",
        "skip": false,
        "lookupWord": "せる",
        "baseForm": "せる",
        "conjugation": null
      }
    ],
    "translation": "Make my heart flutter"
  },
  {
    "id": "l19",
    "start": 76.79,
    "end": 93.32,
    "tokens": [
      {
        "surface": "Uh",
        "romaji": "Uh",
        "meaning": "",
        "pos": "noun",
        "skip": true,
        "lookupWord": "",
        "baseForm": "",
        "conjugation": null
      },
      {
        "surface": "～",
        "romaji": "～",
        "meaning": "",
        "pos": "noun",
        "skip": true,
        "lookupWord": "",
        "baseForm": "",
        "conjugation": null
      }
    ],
    "translation": ""
  },
  {
    "id": "l20",
    "start": 93.32,
    "end": 96.43,
    "tokens": [
      {
        "surface": "ぎゅっと",
        "romaji": "gyutto",
        "meaning": "tightly (hold, squeeze, etc.); firmly; forcefully (e.g. push); hard",
        "pos": "adverb",
        "skip": false,
        "lookupWord": "ぎゅっと",
        "baseForm": "ぎゅっと",
        "conjugation": null
      },
      {
        "surface": "抱きしめる",
        "romaji": "dakishimeru",
        "meaning": "to hug (someone) tight; to embrace; to give (someone) a tight hug; to cuddle",
        "pos": "verb",
        "skip": false,
        "lookupWord": "抱きしめる",
        "baseForm": "抱きしめる",
        "conjugation": null
      },
      {
        "surface": "と",
        "romaji": "to",
        "meaning": "indicates togetherness or quotation (and / with)",
        "pos": "particle",
        "skip": false
      },
      {
        "surface": "か",
        "romaji": "ka",
        "meaning": "indicates a question or alternative (or)",
        "pos": "particle",
        "skip": false
      }
    ],
    "translation": "Hug me tightly"
  },
  {
    "id": "l21",
    "start": 96.43,
    "end": 100.58,
    "tokens": [
      {
        "surface": "色いろ",
        "romaji": "iroiro",
        "meaning": "various; a variety of; all sorts of; many (different)",
        "pos": "adverb",
        "skip": false,
        "lookupWord": "色いろ",
        "baseForm": "色いろ",
        "conjugation": null
      },
      {
        "surface": "して",
        "romaji": "shite",
        "meaning": "to do; to carry out; to perform",
        "pos": "verb",
        "skip": false,
        "lookupWord": "する",
        "baseForm": "する",
        "conjugation": "te-form"
      },
      {
        "surface": "たい",
        "romaji": "tai",
        "meaning": "sea bream (esp. Pagrus major); porgy",
        "pos": "noun",
        "skip": false,
        "lookupWord": "たい",
        "baseForm": "たい",
        "conjugation": null
      },
      {
        "surface": "の",
        "romaji": "no",
        "meaning": "indicates possession or noun modification (of / 's)",
        "pos": "particle",
        "skip": false
      }
    ],
    "translation": "I want it to be colorful"
  },
  {
    "id": "l22",
    "start": 100.58,
    "end": 104.05,
    "tokens": [
      {
        "surface": "女の子",
        "romaji": "onnanoko",
        "meaning": "girl; daughter; baby girl",
        "pos": "noun",
        "skip": false,
        "lookupWord": "女の子",
        "baseForm": "女の子",
        "conjugation": null
      },
      {
        "surface": "上手",
        "romaji": "jouzu",
        "meaning": "skillful; skilled; proficient; good (at); adept; clever",
        "pos": "noun",
        "skip": false,
        "lookupWord": "上手",
        "baseForm": "上手",
        "conjugation": null
      },
      {
        "surface": "に",
        "romaji": "ni",
        "meaning": "indicates direction, destination, time, or target (to / at / in)",
        "pos": "particle",
        "skip": false
      },
      {
        "surface": "扱う",
        "romaji": "atsukau",
        "meaning": "to deal with (a person); to treat; to handle; to take care of; to entertain",
        "pos": "verb",
        "skip": false,
        "lookupWord": "扱う",
        "baseForm": "扱う",
        "conjugation": null
      },
      {
        "surface": "の",
        "romaji": "no",
        "meaning": "indicates possessive",
        "pos": "noun",
        "skip": false,
        "lookupWord": "の",
        "baseForm": "の",
        "conjugation": null
      },
      {
        "surface": "は",
        "romaji": "ha",
        "meaning": "indicates topic of a sentence",
        "pos": "particle",
        "skip": false
      }
    ],
    "translation": "How to treat girls well"
  },
  {
    "id": "l23",
    "start": 104.05,
    "end": 107.24,
    "tokens": [
      {
        "surface": "男の子",
        "romaji": "otokonoko",
        "meaning": "boy; son; baby boy",
        "pos": "noun",
        "skip": false,
        "lookupWord": "男の子",
        "baseForm": "男の子",
        "conjugation": null
      },
      {
        "surface": "次第",
        "romaji": "shidai",
        "meaning": "depending on",
        "pos": "noun",
        "skip": false,
        "lookupWord": "次第",
        "baseForm": "次第",
        "conjugation": null
      }
    ],
    "translation": "It's up to the boy"
  },
  {
    "id": "l24",
    "start": 107.24,
    "end": 110.4,
    "tokens": [
      {
        "surface": "Once",
        "romaji": "Once",
        "meaning": "",
        "pos": "noun",
        "skip": true,
        "lookupWord": "",
        "baseForm": "",
        "conjugation": null
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "",
        "pos": "空白",
        "skip": true,
        "lookupWord": "",
        "baseForm": "",
        "conjugation": null
      },
      {
        "surface": "again",
        "romaji": "again",
        "meaning": "",
        "pos": "noun",
        "skip": true,
        "lookupWord": "",
        "baseForm": "",
        "conjugation": null
      }
    ],
    "translation": ""
  },
  {
    "id": "l25",
    "start": 110.4,
    "end": 113.69,
    "tokens": [
      {
        "surface": "勉強",
        "romaji": "benkyou",
        "meaning": "study",
        "pos": "noun",
        "skip": false,
        "lookupWord": "勉強",
        "baseForm": "勉強",
        "conjugation": null
      },
      {
        "surface": "して",
        "romaji": "shite",
        "meaning": "to do; to carry out; to perform",
        "pos": "verb",
        "skip": false,
        "lookupWord": "する",
        "baseForm": "する",
        "conjugation": "te-form"
      },
      {
        "surface": "よ",
        "romaji": "yo",
        "meaning": "indicates new information or emphasis (you know)",
        "pos": "particle",
        "skip": false
      }
    ],
    "translation": "Study"
  },
  {
    "id": "l26",
    "start": 113.69,
    "end": 116.12,
    "tokens": [
      {
        "surface": "學",
        "romaji": "manabu",
        "meaning": "school",
        "pos": "noun",
        "skip": false,
        "lookupWord": "學",
        "baseForm": "學",
        "conjugation": null
      },
      {
        "surface": "校",
        "romaji": "kou",
        "meaning": "school",
        "pos": "noun",
        "skip": false,
        "lookupWord": "校",
        "baseForm": "校",
        "conjugation": null
      },
      {
        "surface": "じゃ",
        "romaji": "ja",
        "meaning": "then; well; so; well then",
        "pos": "particle",
        "skip": false,
        "lookupWord": "じゃ",
        "baseForm": "じゃ",
        "conjugation": null
      },
      {
        "surface": "きっと",
        "romaji": "kitto",
        "meaning": "surely; undoubtedly; almost certainly; most likely (e.g. 90 percent)",
        "pos": "adverb",
        "skip": false,
        "lookupWord": "きっと",
        "baseForm": "きっと",
        "conjugation": null
      }
    ],
    "translation": "I guess it's school"
  },
  {
    "id": "l27",
    "start": 116.12,
    "end": 118.68,
    "tokens": [
      {
        "surface": "教えて",
        "romaji": "oshiete",
        "meaning": "to teach; to instruct",
        "pos": "verb",
        "skip": false,
        "lookupWord": "教える",
        "baseForm": "教える",
        "conjugation": "te-form"
      },
      {
        "surface": "くれない",
        "romaji": "kurenai",
        "meaning": "to get dark; to grow dark",
        "pos": "verb",
        "skip": false,
        "lookupWord": "くれる",
        "baseForm": "くれる",
        "conjugation": "auxiliary / conjugated"
      }
    ],
    "translation": "Won't tell me"
  },
  {
    "id": "l28",
    "start": 118.68,
    "end": 121.45,
    "tokens": [
      {
        "surface": "秘密",
        "romaji": "himitsu",
        "meaning": "secret; secrecy; confidentiality; privacy",
        "pos": "noun",
        "skip": false,
        "lookupWord": "秘密",
        "baseForm": "秘密",
        "conjugation": null
      },
      {
        "surface": "の",
        "romaji": "no",
        "meaning": "indicates possession or noun modification (of / 's)",
        "pos": "particle",
        "skip": false
      },
      {
        "surface": "やり方",
        "romaji": "yarikata",
        "meaning": "way (of doing); manner; method; means",
        "pos": "noun",
        "skip": false,
        "lookupWord": "やり方",
        "baseForm": "やり方",
        "conjugation": null
      },
      {
        "surface": "を",
        "romaji": "wo",
        "meaning": "indicates direct object of an action",
        "pos": "particle",
        "skip": false
      }
    ],
    "translation": "Secret way"
  },
  {
    "id": "l29",
    "start": 121.45,
    "end": 123.02,
    "tokens": [
      {
        "surface": "打ちあける",
        "romaji": "uchiakeru",
        "meaning": "to confide; to reveal; to disclose; to lay bare; to speak frankly; to open (one's heart)",
        "pos": "verb",
        "skip": false,
        "lookupWord": "打ちあける",
        "baseForm": "打ちあける",
        "conjugation": null
      },
      {
        "surface": "から",
        "romaji": "kara",
        "meaning": "indicates starting point or cause (from / because)",
        "pos": "particle",
        "skip": false
      }
    ],
    "translation": "I'll open up to you"
  },
  {
    "id": "l30",
    "start": 123.02,
    "end": 126.21,
    "tokens": [
      {
        "surface": "Groovin",
        "romaji": "Groovin",
        "meaning": "",
        "pos": "noun",
        "skip": true,
        "lookupWord": "",
        "baseForm": "",
        "conjugation": null
      },
      {
        "surface": "'",
        "romaji": "'",
        "meaning": "",
        "pos": "noun",
        "skip": true,
        "lookupWord": "",
        "baseForm": "",
        "conjugation": null
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "",
        "pos": "空白",
        "skip": true,
        "lookupWord": "",
        "baseForm": "",
        "conjugation": null
      },
      {
        "surface": "Magic",
        "romaji": "Magic",
        "meaning": "",
        "pos": "noun",
        "skip": true,
        "lookupWord": "",
        "baseForm": "",
        "conjugation": null
      }
    ],
    "translation": ""
  },
  {
    "id": "l31",
    "start": 126.21,
    "end": 129.63,
    "tokens": [
      {
        "surface": "寄り",
        "romaji": "yori",
        "meaning": "to approach; to draw near; to come near; to be close to",
        "pos": "verb",
        "skip": false,
        "lookupWord": "寄る",
        "baseForm": "寄る",
        "conjugation": null
      },
      {
        "surface": "そえ",
        "romaji": "soe",
        "meaning": "monk; priest",
        "pos": "verb",
        "skip": false,
        "lookupWord": "そう",
        "baseForm": "そう",
        "conjugation": null
      },
      {
        "surface": "ば",
        "romaji": "ba",
        "meaning": "place; spot; space",
        "pos": "particle",
        "skip": false,
        "lookupWord": "ば",
        "baseForm": "ば",
        "conjugation": null
      },
      {
        "surface": "いつ",
        "romaji": "itsu",
        "meaning": "when; at what time; how soon",
        "pos": "noun",
        "skip": false,
        "lookupWord": "いつ",
        "baseForm": "いつ",
        "conjugation": null
      },
      {
        "surface": "で",
        "romaji": "de",
        "meaning": "indicates location of action, means, or method (at / by / with)",
        "pos": "particle",
        "skip": false
      },
      {
        "surface": "も",
        "romaji": "mo",
        "meaning": "indicates addition or inclusion (also / too / as well)",
        "pos": "particle",
        "skip": false
      }
    ],
    "translation": "Whenever I get close to you"
  },
  {
    "id": "l32",
    "start": 129.63,
    "end": 133.59,
    "tokens": [
      {
        "surface": "きつく",
        "romaji": "kitsuku",
        "meaning": "tough; hard; severe; demanding; harsh",
        "pos": "adjective",
        "skip": false,
        "lookupWord": "きつい",
        "baseForm": "きつい",
        "conjugation": null
      },
      {
        "surface": "結んだ",
        "romaji": "musunda",
        "meaning": "to tie; to bind; to link",
        "pos": "verb",
        "skip": false,
        "lookupWord": "結ぶ",
        "baseForm": "結ぶ",
        "conjugation": "auxiliary / conjugated"
      },
      {
        "surface": "靴",
        "romaji": "kutsu",
        "meaning": "shoe; shoes; boots; footwear; footgear",
        "pos": "noun",
        "skip": false,
        "lookupWord": "靴",
        "baseForm": "靴",
        "conjugation": null
      },
      {
        "surface": "紐",
        "romaji": "himo",
        "meaning": "string; cord",
        "pos": "noun",
        "skip": false,
        "lookupWord": "紐",
        "baseForm": "紐",
        "conjugation": null
      },
      {
        "surface": "が",
        "romaji": "ga",
        "meaning": "indicates subject of a sentence",
        "pos": "particle",
        "skip": false
      }
    ],
    "translation": "Tightly tied shoelaces"
  },
  {
    "id": "l33",
    "start": 133.59,
    "end": 137.47,
    "tokens": [
      {
        "surface": "胸",
        "romaji": "mune",
        "meaning": "chest; breast",
        "pos": "noun",
        "skip": false,
        "lookupWord": "胸",
        "baseForm": "胸",
        "conjugation": null
      },
      {
        "surface": "を",
        "romaji": "wo",
        "meaning": "indicates direct object of an action",
        "pos": "particle",
        "skip": false
      },
      {
        "surface": "キュン",
        "romaji": "kyun",
        "meaning": "with a pitter-patter; choked up (with emotion); heart-wringing; momentary tightening of one's chest caused by powerful feelings (e.g. parting with a loved one)",
        "pos": "noun",
        "skip": false,
        "lookupWord": "キュン",
        "baseForm": "キュン",
        "conjugation": null
      },
      {
        "surface": "と",
        "romaji": "to",
        "meaning": "indicates togetherness or quotation (and / with)",
        "pos": "particle",
        "skip": false
      },
      {
        "surface": "さ",
        "romaji": "sa",
        "meaning": "to do; to carry out; to perform",
        "pos": "verb",
        "skip": false,
        "lookupWord": "する",
        "baseForm": "する",
        "conjugation": null
      },
      {
        "surface": "せる",
        "romaji": "seru",
        "meaning": "cell",
        "pos": "verb",
        "skip": false,
        "lookupWord": "せる",
        "baseForm": "せる",
        "conjugation": null
      }
    ],
    "translation": "Make my heart flutter"
  },
  {
    "id": "l34",
    "start": 137.47,
    "end": 139.85,
    "tokens": [
      {
        "surface": "Uh",
        "romaji": "Uh",
        "meaning": "",
        "pos": "noun",
        "skip": true,
        "lookupWord": "",
        "baseForm": "",
        "conjugation": null
      },
      {
        "surface": "～",
        "romaji": "～",
        "meaning": "",
        "pos": "noun",
        "skip": true,
        "lookupWord": "",
        "baseForm": "",
        "conjugation": null
      },
      {
        "surface": "La",
        "romaji": "La",
        "meaning": "",
        "pos": "noun",
        "skip": true,
        "lookupWord": "",
        "baseForm": "",
        "conjugation": null
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "",
        "pos": "空白",
        "skip": true,
        "lookupWord": "",
        "baseForm": "",
        "conjugation": null
      },
      {
        "surface": "La",
        "romaji": "La",
        "meaning": "",
        "pos": "noun",
        "skip": true,
        "lookupWord": "",
        "baseForm": "",
        "conjugation": null
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "",
        "pos": "空白",
        "skip": true,
        "lookupWord": "",
        "baseForm": "",
        "conjugation": null
      },
      {
        "surface": "La",
        "romaji": "La",
        "meaning": "",
        "pos": "noun",
        "skip": true,
        "lookupWord": "",
        "baseForm": "",
        "conjugation": null
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "",
        "pos": "空白",
        "skip": true,
        "lookupWord": "",
        "baseForm": "",
        "conjugation": null
      },
      {
        "surface": "La",
        "romaji": "La",
        "meaning": "",
        "pos": "noun",
        "skip": true,
        "lookupWord": "",
        "baseForm": "",
        "conjugation": null
      }
    ],
    "translation": ""
  },
  {
    "id": "l35",
    "start": 139.85,
    "end": 140.74,
    "tokens": [
      {
        "surface": "Mmm",
        "romaji": "Mmm",
        "meaning": "",
        "pos": "noun",
        "skip": true,
        "lookupWord": "",
        "baseForm": "",
        "conjugation": null
      },
      {
        "surface": "～",
        "romaji": "～",
        "meaning": "",
        "pos": "noun",
        "skip": true,
        "lookupWord": "",
        "baseForm": "",
        "conjugation": null
      }
    ],
    "translation": ""
  },
  {
    "id": "l36",
    "start": 140.74,
    "end": 144.91,
    "tokens": [
      {
        "surface": "淚",
        "romaji": "淚",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "noun",
        "skip": false,
        "lookupWord": "淚",
        "baseForm": "淚",
        "conjugation": null
      },
      {
        "surface": "が",
        "romaji": "ga",
        "meaning": "indicates subject of a sentence",
        "pos": "particle",
        "skip": false
      },
      {
        "surface": "あふれる",
        "romaji": "afureru",
        "meaning": "to overflow; to brim over; to flood",
        "pos": "verb",
        "skip": false,
        "lookupWord": "あふれる",
        "baseForm": "あふれる",
        "conjugation": null
      },
      {
        "surface": "時",
        "romaji": "toki",
        "meaning": "time; hour; moment",
        "pos": "noun",
        "skip": false,
        "lookupWord": "時",
        "baseForm": "時",
        "conjugation": null
      },
      {
        "surface": "は",
        "romaji": "ha",
        "meaning": "indicates topic of a sentence",
        "pos": "particle",
        "skip": false
      }
    ],
    "translation": "When tears overflow"
  },
  {
    "id": "l37",
    "start": 144.91,
    "end": 149.75,
    "tokens": [
      {
        "surface": "頑張って",
        "romaji": "ganbate",
        "meaning": "to persevere; to persist; to keep at it; to hang on; to hold out; to do one's best",
        "pos": "verb",
        "skip": false,
        "lookupWord": "頑張る",
        "baseForm": "頑張る",
        "conjugation": "te-form"
      },
      {
        "surface": "とびきり",
        "romaji": "tobikiri",
        "meaning": "best; extra-fine; superfine; unequalled",
        "pos": "adverb",
        "skip": false,
        "lookupWord": "とびきり",
        "baseForm": "とびきり",
        "conjugation": null
      },
      {
        "surface": "の",
        "romaji": "no",
        "meaning": "indicates possession or noun modification (of / 's)",
        "pos": "particle",
        "skip": false
      },
      {
        "surface": "Cute",
        "romaji": "cute",
        "meaning": "",
        "pos": "noun",
        "skip": true,
        "lookupWord": "",
        "baseForm": "",
        "conjugation": null
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "",
        "pos": "空白",
        "skip": true,
        "lookupWord": "",
        "baseForm": "",
        "conjugation": null
      },
      {
        "surface": "smile",
        "romaji": "smile",
        "meaning": "",
        "pos": "noun",
        "skip": true,
        "lookupWord": "",
        "baseForm": "",
        "conjugation": null
      }
    ],
    "translation": "Do your best and have a super cute smile"
  },
  {
    "id": "l38",
    "start": 149.75,
    "end": 151.7,
    "tokens": [
      {
        "surface": "瞳",
        "romaji": "hitomi",
        "meaning": "pupil (of the eye)",
        "pos": "noun",
        "skip": false,
        "lookupWord": "瞳",
        "baseForm": "瞳",
        "conjugation": null
      },
      {
        "surface": "の",
        "romaji": "no",
        "meaning": "indicates possession or noun modification (of / 's)",
        "pos": "particle",
        "skip": false
      },
      {
        "surface": "中",
        "romaji": "naka",
        "meaning": "medium (size); average (grade, level, etc.); middle",
        "pos": "noun",
        "skip": false,
        "lookupWord": "中",
        "baseForm": "中",
        "conjugation": null
      },
      {
        "surface": "に",
        "romaji": "ni",
        "meaning": "indicates direction, destination, time, or target (to / at / in)",
        "pos": "particle",
        "skip": false
      }
    ],
    "translation": "In your eyes"
  },
  {
    "id": "l39",
    "start": 151.7,
    "end": 184.08,
    "tokens": [
      {
        "surface": "心",
        "romaji": "kokoro",
        "meaning": "mind; heart; spirit",
        "pos": "noun",
        "skip": false,
        "lookupWord": "心",
        "baseForm": "心",
        "conjugation": null
      },
      {
        "surface": "の",
        "romaji": "no",
        "meaning": "indicates possession or noun modification (of / 's)",
        "pos": "particle",
        "skip": false
      },
      {
        "surface": "奧",
        "romaji": "奧",
        "meaning": "inner part; interior; back (of a drawer, one's throat, etc.); depths (e.g. of a forest); recesses (e.g. of a cave); heart; end (of a road, garden, etc.)",
        "pos": "noun",
        "skip": false,
        "lookupWord": "奧",
        "baseForm": "奧",
        "conjugation": null
      },
      {
        "surface": "に",
        "romaji": "ni",
        "meaning": "indicates direction, destination, time, or target (to / at / in)",
        "pos": "particle",
        "skip": false
      }
    ],
    "translation": "Deep in my heart"
  },
  {
    "id": "l40",
    "start": 184.08,
    "end": 187.06,
    "tokens": [
      {
        "surface": "Groovin",
        "romaji": "Groovin",
        "meaning": "",
        "pos": "noun",
        "skip": true,
        "lookupWord": "",
        "baseForm": "",
        "conjugation": null
      },
      {
        "surface": "'",
        "romaji": "'",
        "meaning": "",
        "pos": "noun",
        "skip": true,
        "lookupWord": "",
        "baseForm": "",
        "conjugation": null
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "",
        "pos": "空白",
        "skip": true,
        "lookupWord": "",
        "baseForm": "",
        "conjugation": null
      },
      {
        "surface": "Magic",
        "romaji": "Magic",
        "meaning": "",
        "pos": "noun",
        "skip": true,
        "lookupWord": "",
        "baseForm": "",
        "conjugation": null
      }
    ],
    "translation": ""
  },
  {
    "id": "l41",
    "start": 187.06,
    "end": 190.58,
    "tokens": [
      {
        "surface": "ソーダ",
        "romaji": "sooda",
        "meaning": "soda",
        "pos": "noun",
        "skip": false,
        "lookupWord": "ソーダ",
        "baseForm": "ソーダ",
        "conjugation": null
      },
      {
        "surface": "水",
        "romaji": "sui",
        "meaning": "water (esp. cool or cold)",
        "pos": "noun",
        "skip": false,
        "lookupWord": "水",
        "baseForm": "水",
        "conjugation": null
      },
      {
        "surface": "に",
        "romaji": "ni",
        "meaning": "indicates direction, destination, time, or target (to / at / in)",
        "pos": "particle",
        "skip": false
      },
      {
        "surface": "とける",
        "romaji": "tokeru",
        "meaning": "to be solved; to be worked out",
        "pos": "verb",
        "skip": false,
        "lookupWord": "とける",
        "baseForm": "とける",
        "conjugation": null
      }
    ],
    "translation": "Dissolves in soda water"
  },
  {
    "id": "l42",
    "start": 190.58,
    "end": 194.54,
    "tokens": [
      {
        "surface": "甘く",
        "romaji": "amaku",
        "meaning": "sweet-tasting; sweet; sugary; sugared",
        "pos": "adjective",
        "skip": false,
        "lookupWord": "甘い",
        "baseForm": "甘い",
        "conjugation": null
      },
      {
        "surface": "切ない",
        "romaji": "setsunai",
        "meaning": "painful; heartrending; trying",
        "pos": "adjective",
        "skip": false,
        "lookupWord": "切ない",
        "baseForm": "切ない",
        "conjugation": null
      },
      {
        "surface": "戀",
        "romaji": "戀",
        "meaning": "(romantic) love",
        "pos": "noun",
        "skip": false,
        "lookupWord": "戀",
        "baseForm": "戀",
        "conjugation": null
      },
      {
        "surface": "の",
        "romaji": "no",
        "meaning": "indicates possession or noun modification (of / 's)",
        "pos": "particle",
        "skip": false
      },
      {
        "surface": "色",
        "romaji": "iro",
        "meaning": "colour; color; hue; tint; tinge; shade",
        "pos": "noun",
        "skip": false,
        "lookupWord": "色",
        "baseForm": "色",
        "conjugation": null
      }
    ],
    "translation": "The sweet and painful color of love"
  },
  {
    "id": "l43",
    "start": 194.54,
    "end": 198.78,
    "tokens": [
      {
        "surface": "胸",
        "romaji": "mune",
        "meaning": "chest; breast",
        "pos": "noun",
        "skip": false,
        "lookupWord": "胸",
        "baseForm": "胸",
        "conjugation": null
      },
      {
        "surface": "を",
        "romaji": "wo",
        "meaning": "indicates direct object of an action",
        "pos": "particle",
        "skip": false
      },
      {
        "surface": "キュン",
        "romaji": "kyun",
        "meaning": "with a pitter-patter; choked up (with emotion); heart-wringing; momentary tightening of one's chest caused by powerful feelings (e.g. parting with a loved one)",
        "pos": "noun",
        "skip": false,
        "lookupWord": "キュン",
        "baseForm": "キュン",
        "conjugation": null
      },
      {
        "surface": "と",
        "romaji": "to",
        "meaning": "indicates togetherness or quotation (and / with)",
        "pos": "particle",
        "skip": false
      },
      {
        "surface": "さ",
        "romaji": "sa",
        "meaning": "to do; to carry out; to perform",
        "pos": "verb",
        "skip": false,
        "lookupWord": "する",
        "baseForm": "する",
        "conjugation": null
      },
      {
        "surface": "せる",
        "romaji": "seru",
        "meaning": "cell",
        "pos": "verb",
        "skip": false,
        "lookupWord": "せる",
        "baseForm": "せる",
        "conjugation": null
      }
    ],
    "translation": "Make my heart flutter"
  },
  {
    "id": "l44",
    "start": 198.78,
    "end": 201.72,
    "tokens": [
      {
        "surface": "Groovin",
        "romaji": "Groovin",
        "meaning": "",
        "pos": "noun",
        "skip": true,
        "lookupWord": "",
        "baseForm": "",
        "conjugation": null
      },
      {
        "surface": "'",
        "romaji": "'",
        "meaning": "",
        "pos": "noun",
        "skip": true,
        "lookupWord": "",
        "baseForm": "",
        "conjugation": null
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "",
        "pos": "空白",
        "skip": true,
        "lookupWord": "",
        "baseForm": "",
        "conjugation": null
      },
      {
        "surface": "Magic",
        "romaji": "Magic",
        "meaning": "",
        "pos": "noun",
        "skip": true,
        "lookupWord": "",
        "baseForm": "",
        "conjugation": null
      }
    ],
    "translation": ""
  },
  {
    "id": "l45",
    "start": 201.72,
    "end": 205.55,
    "tokens": [
      {
        "surface": "寄り",
        "romaji": "yori",
        "meaning": "to approach; to draw near; to come near; to be close to",
        "pos": "verb",
        "skip": false,
        "lookupWord": "寄る",
        "baseForm": "寄る",
        "conjugation": null
      },
      {
        "surface": "そえ",
        "romaji": "soe",
        "meaning": "monk; priest",
        "pos": "verb",
        "skip": false,
        "lookupWord": "そう",
        "baseForm": "そう",
        "conjugation": null
      },
      {
        "surface": "ば",
        "romaji": "ba",
        "meaning": "place; spot; space",
        "pos": "particle",
        "skip": false,
        "lookupWord": "ば",
        "baseForm": "ば",
        "conjugation": null
      },
      {
        "surface": "いつ",
        "romaji": "itsu",
        "meaning": "when; at what time; how soon",
        "pos": "noun",
        "skip": false,
        "lookupWord": "いつ",
        "baseForm": "いつ",
        "conjugation": null
      },
      {
        "surface": "で",
        "romaji": "de",
        "meaning": "indicates location of action, means, or method (at / by / with)",
        "pos": "particle",
        "skip": false
      },
      {
        "surface": "も",
        "romaji": "mo",
        "meaning": "indicates addition or inclusion (also / too / as well)",
        "pos": "particle",
        "skip": false
      }
    ],
    "translation": "Whenever I get close to you"
  },
  {
    "id": "l46",
    "start": 205.55,
    "end": 208.96,
    "tokens": [
      {
        "surface": "きつく",
        "romaji": "kitsuku",
        "meaning": "tough; hard; severe; demanding; harsh",
        "pos": "adjective",
        "skip": false,
        "lookupWord": "きつい",
        "baseForm": "きつい",
        "conjugation": null
      },
      {
        "surface": "結んだ",
        "romaji": "musunda",
        "meaning": "to tie; to bind; to link",
        "pos": "verb",
        "skip": false,
        "lookupWord": "結ぶ",
        "baseForm": "結ぶ",
        "conjugation": "auxiliary / conjugated"
      },
      {
        "surface": "靴",
        "romaji": "kutsu",
        "meaning": "shoe; shoes; boots; footwear; footgear",
        "pos": "noun",
        "skip": false,
        "lookupWord": "靴",
        "baseForm": "靴",
        "conjugation": null
      },
      {
        "surface": "紐",
        "romaji": "himo",
        "meaning": "string; cord",
        "pos": "noun",
        "skip": false,
        "lookupWord": "紐",
        "baseForm": "紐",
        "conjugation": null
      },
      {
        "surface": "が",
        "romaji": "ga",
        "meaning": "indicates subject of a sentence",
        "pos": "particle",
        "skip": false
      }
    ],
    "translation": "Tightly tied shoelaces"
  },
  {
    "id": "l47",
    "start": 208.96,
    "end": 211.61,
    "tokens": [
      {
        "surface": "胸",
        "romaji": "mune",
        "meaning": "chest; breast",
        "pos": "noun",
        "skip": false,
        "lookupWord": "胸",
        "baseForm": "胸",
        "conjugation": null
      },
      {
        "surface": "を",
        "romaji": "wo",
        "meaning": "indicates direct object of an action",
        "pos": "particle",
        "skip": false
      },
      {
        "surface": "キュン",
        "romaji": "kyun",
        "meaning": "with a pitter-patter; choked up (with emotion); heart-wringing; momentary tightening of one's chest caused by powerful feelings (e.g. parting with a loved one)",
        "pos": "noun",
        "skip": false,
        "lookupWord": "キュン",
        "baseForm": "キュン",
        "conjugation": null
      },
      {
        "surface": "と",
        "romaji": "to",
        "meaning": "indicates togetherness or quotation (and / with)",
        "pos": "particle",
        "skip": false
      },
      {
        "surface": "さ",
        "romaji": "sa",
        "meaning": "to do; to carry out; to perform",
        "pos": "verb",
        "skip": false,
        "lookupWord": "する",
        "baseForm": "する",
        "conjugation": null
      },
      {
        "surface": "せる",
        "romaji": "seru",
        "meaning": "cell",
        "pos": "verb",
        "skip": false,
        "lookupWord": "せる",
        "baseForm": "せる",
        "conjugation": null
      }
    ],
    "translation": "Make my heart flutter"
  },
  {
    "id": "l48",
    "start": 211.61,
    "end": 227.75,
    "tokens": [
      {
        "surface": "Uh",
        "romaji": "Uh",
        "meaning": "",
        "pos": "noun",
        "skip": true,
        "lookupWord": "",
        "baseForm": "",
        "conjugation": null
      },
      {
        "surface": "～",
        "romaji": "～",
        "meaning": "",
        "pos": "noun",
        "skip": true,
        "lookupWord": "",
        "baseForm": "",
        "conjugation": null
      }
    ],
    "translation": ""
  },
  {
    "id": "l49",
    "start": 227.75,
    "end": 235.15,
    "tokens": [
      {
        "surface": "Groovin",
        "romaji": "Groovin",
        "meaning": "",
        "pos": "noun",
        "skip": true,
        "lookupWord": "",
        "baseForm": "",
        "conjugation": null
      },
      {
        "surface": "'",
        "romaji": "'",
        "meaning": "",
        "pos": "noun",
        "skip": true,
        "lookupWord": "",
        "baseForm": "",
        "conjugation": null
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "",
        "pos": "空白",
        "skip": true,
        "lookupWord": "",
        "baseForm": "",
        "conjugation": null
      },
      {
        "surface": "Magic",
        "romaji": "Magic",
        "meaning": "",
        "pos": "noun",
        "skip": true,
        "lookupWord": "",
        "baseForm": "",
        "conjugation": null
      }
    ],
    "translation": ""
  },
  {
    "id": "l50",
    "start": 235.15,
    "end": 242.43,
    "tokens": [
      {
        "surface": "Groovin",
        "romaji": "Groovin",
        "meaning": "",
        "pos": "noun",
        "skip": true,
        "lookupWord": "",
        "baseForm": "",
        "conjugation": null
      },
      {
        "surface": "'",
        "romaji": "'",
        "meaning": "",
        "pos": "noun",
        "skip": true,
        "lookupWord": "",
        "baseForm": "",
        "conjugation": null
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "",
        "pos": "空白",
        "skip": true,
        "lookupWord": "",
        "baseForm": "",
        "conjugation": null
      },
      {
        "surface": "Magic",
        "romaji": "Magic",
        "meaning": "",
        "pos": "noun",
        "skip": true,
        "lookupWord": "",
        "baseForm": "",
        "conjugation": null
      }
    ],
    "translation": ""
  },
  {
    "id": "l51",
    "start": 242.43,
    "end": 249.98,
    "tokens": [
      {
        "surface": "Groovin",
        "romaji": "Groovin",
        "meaning": "",
        "pos": "noun",
        "skip": true,
        "lookupWord": "",
        "baseForm": "",
        "conjugation": null
      },
      {
        "surface": "'",
        "romaji": "'",
        "meaning": "",
        "pos": "noun",
        "skip": true,
        "lookupWord": "",
        "baseForm": "",
        "conjugation": null
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "",
        "pos": "空白",
        "skip": true,
        "lookupWord": "",
        "baseForm": "",
        "conjugation": null
      },
      {
        "surface": "Magic",
        "romaji": "Magic",
        "meaning": "",
        "pos": "noun",
        "skip": true,
        "lookupWord": "",
        "baseForm": "",
        "conjugation": null
      }
    ],
    "translation": ""
  },
  {
    "id": "l52",
    "start": 249.98,
    "end": 253.98,
    "tokens": [
      {
        "surface": "Groovin",
        "romaji": "Groovin",
        "meaning": "",
        "pos": "noun",
        "skip": true,
        "lookupWord": "",
        "baseForm": "",
        "conjugation": null
      },
      {
        "surface": "'",
        "romaji": "'",
        "meaning": "",
        "pos": "noun",
        "skip": true,
        "lookupWord": "",
        "baseForm": "",
        "conjugation": null
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "",
        "pos": "空白",
        "skip": true,
        "lookupWord": "",
        "baseForm": "",
        "conjugation": null
      },
      {
        "surface": "Magic",
        "romaji": "Magic",
        "meaning": "",
        "pos": "noun",
        "skip": true,
        "lookupWord": "",
        "baseForm": "",
        "conjugation": null
      }
    ],
    "translation": ""
  }
];
