import { LyricLine } from "@/lib/types";

// Auto-generated by scripts/generate-lyrics.mjs for "iris out" by Kenshi.
// Words come from kuromoji (segmentation), wanakana (romaji), and Jisho
// (dictionary meanings) — spot-check before shipping, don't trust blindly.
export const irisOutLyrics: LyricLine[] = [
  {
    "id": "l1",
    "start": 18.39,
    "end": 19.87,
    "tokens": [
      {
        "surface": "駄目",
        "romaji": "dame",
        "meaning": "no good; not serving its purpose; useless; broken",
        "pos": "noun",
        "skip": false,
        "lookupWord": "駄目",
        "baseForm": "駄目",
        "conjugation": null
      },
      {
        "surface": "駄目",
        "romaji": "dame",
        "meaning": "no good; not serving its purpose; useless; broken",
        "pos": "noun",
        "skip": false,
        "lookupWord": "駄目",
        "baseForm": "駄目",
        "conjugation": null
      },
      {
        "surface": "駄目",
        "romaji": "dame",
        "meaning": "no good; not serving its purpose; useless; broken",
        "pos": "noun",
        "skip": false,
        "lookupWord": "駄目",
        "baseForm": "駄目",
        "conjugation": null
      }
    ],
    "translation": "No, no, no"
  },
  {
    "id": "l2",
    "start": 19.87,
    "end": 21.98,
    "tokens": [
      {
        "surface": "脳みそ",
        "romaji": "noumiso",
        "meaning": "brains; brain tissue",
        "pos": "noun",
        "skip": false,
        "lookupWord": "脳みそ",
        "baseForm": "脳みそ",
        "conjugation": null
      },
      {
        "surface": "の",
        "romaji": "no",
        "meaning": "indicates possession or noun modification (of / 's)",
        "pos": "particle",
        "skip": false
      },
      {
        "surface": "中",
        "romaji": "naka",
        "meaning": "medium (size); average (grade, level, etc.); middle",
        "pos": "noun",
        "skip": false,
        "lookupWord": "中",
        "baseForm": "中",
        "conjugation": null
      },
      {
        "surface": "から",
        "romaji": "kara",
        "meaning": "indicates starting point or cause (from / because)",
        "pos": "particle",
        "skip": false
      }
    ],
    "translation": "From inside the brain"
  },
  {
    "id": "l3",
    "start": 21.98,
    "end": 25.55,
    "tokens": [
      {
        "surface": "「",
        "romaji": "‘",
        "meaning": "",
        "pos": "括弧開",
        "skip": true,
        "lookupWord": "",
        "baseForm": "",
        "conjugation": null
      },
      {
        "surface": "やめろ",
        "romaji": "yamero",
        "meaning": "to resign; to retire; to quit; to leave (one's job, etc.)",
        "pos": "verb",
        "skip": false,
        "lookupWord": "やめる",
        "baseForm": "やめる",
        "conjugation": null
      },
      {
        "surface": "馬鹿",
        "romaji": "baka",
        "meaning": "idiot; moron; fool",
        "pos": "noun",
        "skip": false,
        "lookupWord": "馬鹿",
        "baseForm": "馬鹿",
        "conjugation": null
      },
      {
        "surface": "」",
        "romaji": "’",
        "meaning": "",
        "pos": "括弧閉",
        "skip": true,
        "lookupWord": "",
        "baseForm": "",
        "conjugation": null
      },
      {
        "surface": "と",
        "romaji": "to",
        "meaning": "indicates togetherness or quotation (and / with)",
        "pos": "particle",
        "skip": false
      },
      {
        "surface": "喚く",
        "romaji": "wameku",
        "meaning": "to shout; to cry (out); to yell; to scream; to clamour",
        "pos": "verb",
        "skip": false,
        "lookupWord": "喚く",
        "baseForm": "喚く",
        "conjugation": null
      },
      {
        "surface": "モラリティ",
        "romaji": "moraritei",
        "meaning": "morality",
        "pos": "noun",
        "skip": false,
        "lookupWord": "モラリティ",
        "baseForm": "モラリティ",
        "conjugation": null
      }
    ],
    "translation": "Morality screams, “Stop it, you idiot!”"
  },
  {
    "id": "l4",
    "start": 25.55,
    "end": 27.19,
    "tokens": [
      {
        "surface": "ダーリンベイビーダーリン",
        "romaji": "daarinbeibiidaarin",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "noun",
        "skip": false,
        "lookupWord": "ダーリンベイビーダーリン",
        "baseForm": "ダーリンベイビーダーリン",
        "conjugation": null
      }
    ],
    "translation": "Darling baby darling"
  },
  {
    "id": "l5",
    "start": 27.19,
    "end": 28.71,
    "tokens": [
      {
        "surface": "半端",
        "romaji": "hanpa",
        "meaning": "remnant; fragment; incomplete set; incompleteness",
        "pos": "noun",
        "skip": false,
        "lookupWord": "半端",
        "baseForm": "半端",
        "conjugation": null
      },
      {
        "surface": "なく",
        "romaji": "naku",
        "meaning": "nonexistent; not being (there)",
        "pos": "adjective",
        "skip": false,
        "lookupWord": "ない",
        "baseForm": "ない",
        "conjugation": null
      },
      {
        "surface": "ラブ",
        "romaji": "rabu",
        "meaning": "love",
        "pos": "noun",
        "skip": false,
        "lookupWord": "ラブ",
        "baseForm": "ラブ",
        "conjugation": null
      },
      {
        "surface": "！",
        "romaji": "!",
        "meaning": "",
        "pos": "一般",
        "skip": true,
        "lookupWord": "",
        "baseForm": "",
        "conjugation": null
      },
      {
        "surface": "と",
        "romaji": "to",
        "meaning": "indicates togetherness or quotation (and / with)",
        "pos": "particle",
        "skip": false
      }
    ],
    "translation": "Absolute love! and"
  },
  {
    "id": "l6",
    "start": 28.71,
    "end": 32.22,
    "tokens": [
      {
        "surface": "きらめき",
        "romaji": "kirameki",
        "meaning": "to glitter; to sparkle; to twinkle; to glisten; to gleam; to glint",
        "pos": "verb",
        "skip": false,
        "lookupWord": "きらめく",
        "baseForm": "きらめく",
        "conjugation": null
      },
      {
        "surface": "浮き足立つ",
        "romaji": "ukiashidatsu",
        "meaning": "to be prepared to flee; to become restless; to become agitated",
        "pos": "verb",
        "skip": false,
        "lookupWord": "浮き足立つ",
        "baseForm": "浮き足立つ",
        "conjugation": null
      },
      {
        "surface": "フィロソフィ",
        "romaji": "fyirosofyi",
        "meaning": "philosophy",
        "pos": "noun",
        "skip": false,
        "lookupWord": "フィロソフィ",
        "baseForm": "フィロソフィ",
        "conjugation": null
      }
    ],
    "translation": "A sparkling philosophy that stands out"
  },
  {
    "id": "l7",
    "start": 32.22,
    "end": 33.91,
    "tokens": [
      {
        "surface": "死ぬ",
        "romaji": "shinu",
        "meaning": "to die; to pass away",
        "pos": "verb",
        "skip": false,
        "lookupWord": "死ぬ",
        "baseForm": "死ぬ",
        "conjugation": null
      },
      {
        "surface": "ほど",
        "romaji": "hodo",
        "meaning": "extent; degree; measure",
        "pos": "particle",
        "skip": false,
        "lookupWord": "ほど",
        "baseForm": "ほど",
        "conjugation": null
      },
      {
        "surface": "可愛い",
        "romaji": "kawaii",
        "meaning": "cute; adorable; charming; lovely; pretty",
        "pos": "adjective",
        "skip": false,
        "lookupWord": "可愛い",
        "baseForm": "可愛い",
        "conjugation": null
      },
      {
        "surface": "上目遣い",
        "romaji": "uwamezukai",
        "meaning": "looking at someone (with upturned eyes); glancing upwards (at someone)",
        "pos": "noun",
        "skip": false,
        "lookupWord": "上目遣い",
        "baseForm": "上目遣い",
        "conjugation": null
      }
    ],
    "translation": "Deadly cute look"
  },
  {
    "id": "l8",
    "start": 33.91,
    "end": 35.87,
    "tokens": [
      {
        "surface": "なにがし",
        "romaji": "nanigashi",
        "meaning": "certain amount; some",
        "pos": "noun",
        "skip": false,
        "lookupWord": "なにがし",
        "baseForm": "なにがし",
        "conjugation": null
      },
      {
        "surface": "法",
        "romaji": "hou",
        "meaning": "law; act; principle",
        "pos": "noun",
        "skip": false,
        "lookupWord": "法",
        "baseForm": "法",
        "conjugation": null
      },
      {
        "surface": "に",
        "romaji": "ni",
        "meaning": "indicates direction, destination, time, or target (to / at / in)",
        "pos": "particle",
        "skip": false
      },
      {
        "surface": "触れる",
        "romaji": "fureru",
        "meaning": "to touch; to feel",
        "pos": "verb",
        "skip": false,
        "lookupWord": "触れる",
        "baseForm": "触れる",
        "conjugation": null
      },
      {
        "surface": "くらい",
        "romaji": "kurai",
        "meaning": "dark; gloomy; murky",
        "pos": "particle",
        "skip": false,
        "lookupWord": "くらい",
        "baseForm": "くらい",
        "conjugation": null
      }
    ],
    "translation": "It's almost like breaking the law"
  },
  {
    "id": "l9",
    "start": 35.87,
    "end": 37.54,
    "tokens": [
      {
        "surface": "ばら",
        "romaji": "bara",
        "meaning": "rose",
        "pos": "noun",
        "skip": false,
        "lookupWord": "ばら",
        "baseForm": "ばら",
        "conjugation": null
      },
      {
        "surface": "撒く",
        "romaji": "maku",
        "meaning": "to scatter; to sprinkle; to strew",
        "pos": "verb",
        "skip": false,
        "lookupWord": "撒く",
        "baseForm": "撒く",
        "conjugation": null
      },
      {
        "surface": "乱心",
        "romaji": "ranshin",
        "meaning": "mental derangement; madness; insanity",
        "pos": "noun",
        "skip": false,
        "lookupWord": "乱心",
        "baseForm": "乱心",
        "conjugation": null
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "",
        "pos": "空白",
        "skip": true,
        "lookupWord": "",
        "baseForm": "",
        "conjugation": null
      },
      {
        "surface": "気づけ",
        "romaji": "kizuke",
        "meaning": "to notice; to realize; to realise; to become aware (of); to perceive; to sense; to suspect",
        "pos": "verb",
        "skip": false,
        "lookupWord": "気づく",
        "baseForm": "気づく",
        "conjugation": null
      },
      {
        "surface": "ば",
        "romaji": "ba",
        "meaning": "place; spot; space",
        "pos": "particle",
        "skip": false,
        "lookupWord": "ば",
        "baseForm": "ば",
        "conjugation": null
      },
      {
        "surface": "蕩尽",
        "romaji": "toujin",
        "meaning": "squandering; dissipation",
        "pos": "noun",
        "skip": false,
        "lookupWord": "蕩尽",
        "baseForm": "蕩尽",
        "conjugation": null
      }
    ],
    "translation": "Spreading madness, before you know it, you've exhausted yourself"
  },
  {
    "id": "l10",
    "start": 37.54,
    "end": 39.34,
    "tokens": [
      {
        "surface": "この世",
        "romaji": "konoyo",
        "meaning": "this world; this life; world of the living",
        "pos": "noun",
        "skip": false,
        "lookupWord": "この世",
        "baseForm": "この世",
        "conjugation": null
      },
      {
        "surface": "に",
        "romaji": "ni",
        "meaning": "indicates direction, destination, time, or target (to / at / in)",
        "pos": "particle",
        "skip": false
      },
      {
        "surface": "生まれた",
        "romaji": "umareta",
        "meaning": "to be born",
        "pos": "verb",
        "skip": false,
        "lookupWord": "生まれる",
        "baseForm": "生まれる",
        "conjugation": "auxiliary / conjugated"
      },
      {
        "surface": "君",
        "romaji": "kimi",
        "meaning": "you; buddy; pal",
        "pos": "noun",
        "skip": false,
        "lookupWord": "君",
        "baseForm": "君",
        "conjugation": null
      },
      {
        "surface": "が",
        "romaji": "ga",
        "meaning": "indicates subject of a sentence",
        "pos": "particle",
        "skip": false
      },
      {
        "surface": "悪い",
        "romaji": "warui",
        "meaning": "bad; poor; undesirable",
        "pos": "adjective",
        "skip": false,
        "lookupWord": "悪い",
        "baseForm": "悪い",
        "conjugation": null
      }
    ],
    "translation": "It's your fault for being born into this world"
  },
  {
    "id": "l11",
    "start": 39.34,
    "end": 40.94,
    "tokens": [
      {
        "surface": "やたら",
        "romaji": "yatara",
        "meaning": "indiscriminately; blindly; at random; recklessly; thoughtlessly; excessively; profusely",
        "pos": "adverb",
        "skip": false,
        "lookupWord": "やたら",
        "baseForm": "やたら",
        "conjugation": null
      },
      {
        "surface": "と",
        "romaji": "to",
        "meaning": "indicates togetherness or quotation (and / with)",
        "pos": "particle",
        "skip": false
      },
      {
        "surface": "しんどい",
        "romaji": "shindoi",
        "meaning": "tired; frazzled",
        "pos": "adjective",
        "skip": false,
        "lookupWord": "しんどい",
        "baseForm": "しんどい",
        "conjugation": null
      },
      {
        "surface": "恋煩い",
        "romaji": "koiwazurai",
        "meaning": "lovesickness",
        "pos": "noun",
        "skip": false,
        "lookupWord": "恋煩い",
        "baseForm": "恋煩い",
        "conjugation": null
      }
    ],
    "translation": "Extremely painful lovesickness"
  },
  {
    "id": "l12",
    "start": 40.94,
    "end": 42.87,
    "tokens": [
      {
        "surface": "バラバラ",
        "romaji": "barabara",
        "meaning": "scattered; disperse; loose; disconnected; in pieces; in drops; rustling",
        "pos": "adverb",
        "skip": false,
        "lookupWord": "バラバラ",
        "baseForm": "バラバラ",
        "conjugation": null
      },
      {
        "surface": "ん",
        "romaji": "n",
        "meaning": "yes; yeah; uh huh",
        "pos": "particle",
        "skip": false,
        "lookupWord": "ん",
        "baseForm": "ん",
        "conjugation": null
      },
      {
        "surface": "なる",
        "romaji": "naru",
        "meaning": "to become; to get; to grow; to turn; to reach; to attain",
        "pos": "verb",
        "skip": false,
        "lookupWord": "なる",
        "baseForm": "なる",
        "conjugation": null
      },
      {
        "surface": "頭",
        "romaji": "atama",
        "meaning": "head",
        "pos": "noun",
        "skip": false,
        "lookupWord": "頭",
        "baseForm": "頭",
        "conjugation": null
      },
      {
        "surface": "と",
        "romaji": "to",
        "meaning": "indicates togetherness or quotation (and / with)",
        "pos": "particle",
        "skip": false
      },
      {
        "surface": "この",
        "romaji": "kono",
        "meaning": "this",
        "pos": "adjectival",
        "skip": false,
        "lookupWord": "この",
        "baseForm": "この",
        "conjugation": null
      },
      {
        "surface": "身体",
        "romaji": "shintai",
        "meaning": "body",
        "pos": "noun",
        "skip": false,
        "lookupWord": "身体",
        "baseForm": "身体",
        "conjugation": null
      }
    ],
    "translation": "This head and this body are falling apart"
  },
  {
    "id": "l13",
    "start": 42.87,
    "end": 45.03,
    "tokens": [
      {
        "surface": "頸",
        "romaji": "頸",
        "meaning": "neck",
        "pos": "noun",
        "skip": false,
        "lookupWord": "頸",
        "baseForm": "頸",
        "conjugation": null
      },
      {
        "surface": "動脈",
        "romaji": "doumyaku",
        "meaning": "artery",
        "pos": "noun",
        "skip": false,
        "lookupWord": "動脈",
        "baseForm": "動脈",
        "conjugation": null
      },
      {
        "surface": "から",
        "romaji": "kara",
        "meaning": "indicates starting point or cause (from / because)",
        "pos": "particle",
        "skip": false
      },
      {
        "surface": "アイラブユー",
        "romaji": "airabuyuu",
        "meaning": "I love you",
        "pos": "noun",
        "skip": false,
        "lookupWord": "アイラブユー",
        "baseForm": "アイラブユー",
        "conjugation": null
      },
      {
        "surface": "が",
        "romaji": "ga",
        "meaning": "indicates subject of a sentence",
        "pos": "particle",
        "skip": false
      },
      {
        "surface": "噴き",
        "romaji": "fuki",
        "meaning": "to emit; to spout; to spurt; to boil over",
        "pos": "verb",
        "skip": false,
        "lookupWord": "噴く",
        "baseForm": "噴く",
        "conjugation": null
      },
      {
        "surface": "出て",
        "romaji": "dete",
        "meaning": "to leave; to exit; to go out; to come out; to get out",
        "pos": "verb",
        "skip": false,
        "lookupWord": "出る",
        "baseForm": "出る",
        "conjugation": "te-form"
      }
    ],
    "translation": "I love you is gushing out from my carotid artery"
  },
  {
    "id": "l14",
    "start": 45.03,
    "end": 46.5,
    "tokens": [
      {
        "surface": "アイリス",
        "romaji": "airisu",
        "meaning": "iris",
        "pos": "noun",
        "skip": false,
        "lookupWord": "アイリス",
        "baseForm": "アイリス",
        "conjugation": null
      },
      {
        "surface": "アウト",
        "romaji": "auto",
        "meaning": "out (of a ball; in tennis, etc.); outside the line",
        "pos": "noun",
        "skip": false,
        "lookupWord": "アウト",
        "baseForm": "アウト",
        "conjugation": null
      }
    ],
    "translation": "Iris out"
  },
  {
    "id": "l15",
    "start": 46.5,
    "end": 48.58,
    "tokens": [
      {
        "surface": "一体",
        "romaji": "ittai",
        "meaning": "(what) the heck; (why) in the world; (who) on earth; (where) the hell; (how) the hell",
        "pos": "adverb",
        "skip": false,
        "lookupWord": "一体",
        "baseForm": "一体",
        "conjugation": null
      },
      {
        "surface": "どう",
        "romaji": "dou",
        "meaning": "copper (Cu)",
        "pos": "adverb",
        "skip": false,
        "lookupWord": "どう",
        "baseForm": "どう",
        "conjugation": null
      },
      {
        "surface": "しよう",
        "romaji": "shiyou",
        "meaning": "to do; to carry out; to perform",
        "pos": "verb",
        "skip": false,
        "lookupWord": "する",
        "baseForm": "する",
        "conjugation": "auxiliary / conjugated"
      },
      {
        "surface": "この",
        "romaji": "kono",
        "meaning": "this",
        "pos": "adjectival",
        "skip": false,
        "lookupWord": "この",
        "baseForm": "この",
        "conjugation": null
      },
      {
        "surface": "想い",
        "romaji": "omoi",
        "meaning": "thought",
        "pos": "noun",
        "skip": false,
        "lookupWord": "想い",
        "baseForm": "想い",
        "conjugation": null
      },
      {
        "surface": "を",
        "romaji": "wo",
        "meaning": "indicates direct object of an action",
        "pos": "particle",
        "skip": false
      }
    ],
    "translation": "What should I do with these feelings?"
  },
  {
    "id": "l16",
    "start": 48.58,
    "end": 50.27,
    "tokens": [
      {
        "surface": "どう",
        "romaji": "dou",
        "meaning": "copper (Cu)",
        "pos": "adverb",
        "skip": false,
        "lookupWord": "どう",
        "baseForm": "どう",
        "conjugation": null
      },
      {
        "surface": "しよう",
        "romaji": "shiyou",
        "meaning": "to do; to carry out; to perform",
        "pos": "verb",
        "skip": false,
        "lookupWord": "する",
        "baseForm": "する",
        "conjugation": "auxiliary / conjugated"
      },
      {
        "surface": "あ",
        "romaji": "a",
        "meaning": "sub-; second-rate; inferior",
        "pos": "フィラー",
        "skip": false,
        "lookupWord": "あ",
        "baseForm": "あ",
        "conjugation": null
      },
      {
        "surface": "ばら",
        "romaji": "bara",
        "meaning": "rose",
        "pos": "noun",
        "skip": false,
        "lookupWord": "ばら",
        "baseForm": "ばら",
        "conjugation": null
      },
      {
        "surface": "の",
        "romaji": "no",
        "meaning": "indicates possession or noun modification (of / 's)",
        "pos": "particle",
        "skip": false
      },
      {
        "surface": "奥",
        "romaji": "oku",
        "meaning": "inner part; interior; back (of a drawer, one's throat, etc.); depths (e.g. of a forest); recesses (e.g. of a cave); heart; end (of a road, garden, etc.)",
        "pos": "noun",
        "skip": false,
        "lookupWord": "奥",
        "baseForm": "奥",
        "conjugation": null
      },
      {
        "surface": "を",
        "romaji": "wo",
        "meaning": "indicates direct object of an action",
        "pos": "particle",
        "skip": false
      }
    ],
    "translation": "What should I do inside the ribs?"
  },
  {
    "id": "l17",
    "start": 50.27,
    "end": 53.4,
    "tokens": [
      {
        "surface": "ザラメ",
        "romaji": "zarame",
        "meaning": "granulated sugar; brown sugar",
        "pos": "noun",
        "skip": false,
        "lookupWord": "ザラメ",
        "baseForm": "ザラメ",
        "conjugation": null
      },
      {
        "surface": "が",
        "romaji": "ga",
        "meaning": "indicates subject of a sentence",
        "pos": "particle",
        "skip": false
      },
      {
        "surface": "溶けて",
        "romaji": "tokete",
        "meaning": "to melt; to liquefy; to soften (e.g. through heat); to thaw",
        "pos": "verb",
        "skip": false,
        "lookupWord": "溶ける",
        "baseForm": "溶ける",
        "conjugation": "te-form"
      },
      {
        "surface": "ゲロ",
        "romaji": "gero",
        "meaning": "vomit; spew; puke; vomiting",
        "pos": "noun",
        "skip": false,
        "lookupWord": "ゲロ",
        "baseForm": "ゲロ",
        "conjugation": null
      },
      {
        "surface": "に",
        "romaji": "ni",
        "meaning": "indicates direction, destination, time, or target (to / at / in)",
        "pos": "particle",
        "skip": false
      },
      {
        "surface": "なり",
        "romaji": "nari",
        "meaning": "to become; to get; to grow; to turn; to reach; to attain",
        "pos": "verb",
        "skip": false,
        "lookupWord": "なる",
        "baseForm": "なる",
        "conjugation": null
      },
      {
        "surface": "そう",
        "romaji": "sou",
        "meaning": "monk; priest",
        "pos": "noun",
        "skip": false,
        "lookupWord": "そう",
        "baseForm": "そう",
        "conjugation": null
      }
    ],
    "translation": "The grains will melt and turn into vomit"
  },
  {
    "id": "l18",
    "start": 53.4,
    "end": 54.03,
    "tokens": [
      {
        "surface": "BOOM",
        "romaji": "BOOM",
        "meaning": "",
        "pos": "noun",
        "skip": true,
        "lookupWord": "",
        "baseForm": "",
        "conjugation": null
      }
    ],
    "translation": ""
  },
  {
    "id": "l19",
    "start": 54.03,
    "end": 57.05,
    "tokens": [
      {
        "surface": "瞳孔",
        "romaji": "doukou",
        "meaning": "pupil (of the eye)",
        "pos": "noun",
        "skip": false,
        "lookupWord": "瞳孔",
        "baseForm": "瞳孔",
        "conjugation": null
      },
      {
        "surface": "バチ",
        "romaji": "bachi",
        "meaning": "plectrum (for a shamisen, biwa, etc.); pick",
        "pos": "noun",
        "skip": false,
        "lookupWord": "バチ",
        "baseForm": "バチ",
        "conjugation": null
      },
      {
        "surface": "開いて",
        "romaji": "hiraite",
        "meaning": "to open; to undo; to unseal; to unpack",
        "pos": "verb",
        "skip": false,
        "lookupWord": "開く",
        "baseForm": "開く",
        "conjugation": "te-form"
      },
      {
        "surface": "溺れ死",
        "romaji": "oborejini",
        "meaning": "to die by drowning; to drown",
        "pos": "noun",
        "skip": false,
        "lookupWord": "溺れ死",
        "baseForm": "溺れ死",
        "conjugation": null
      },
      {
        "surface": "に",
        "romaji": "ni",
        "meaning": "indicates direction, destination, time, or target (to / at / in)",
        "pos": "particle",
        "skip": false
      },
      {
        "surface": "そう",
        "romaji": "sou",
        "meaning": "monk; priest",
        "pos": "adverb",
        "skip": false,
        "lookupWord": "そう",
        "baseForm": "そう",
        "conjugation": null
      }
    ],
    "translation": "My pupils are dilated and I feel like I'm drowning"
  },
  {
    "id": "l20",
    "start": 57.05,
    "end": 61.06,
    "tokens": [
      {
        "surface": "今",
        "romaji": "kon",
        "meaning": "now; the present time; just now; soon; immediately",
        "pos": "名詞接続",
        "skip": false,
        "lookupWord": "今",
        "baseForm": "今",
        "conjugation": null
      },
      {
        "surface": "この世",
        "romaji": "konoyo",
        "meaning": "this world; this life; world of the living",
        "pos": "noun",
        "skip": false,
        "lookupWord": "この世",
        "baseForm": "この世",
        "conjugation": null
      },
      {
        "surface": "で",
        "romaji": "de",
        "meaning": "indicates location of action, means, or method (at / by / with)",
        "pos": "particle",
        "skip": false
      },
      {
        "surface": "君",
        "romaji": "kimi",
        "meaning": "you; buddy; pal",
        "pos": "noun",
        "skip": false,
        "lookupWord": "君",
        "baseForm": "君",
        "conjugation": null
      },
      {
        "surface": "だけ",
        "romaji": "dake",
        "meaning": "only; just; merely; simply; no more than; nothing but; alone",
        "pos": "particle",
        "skip": false,
        "lookupWord": "だけ",
        "baseForm": "だけ",
        "conjugation": null
      },
      {
        "surface": "大",
        "romaji": "dai",
        "meaning": "large; big; great; huge; vast; major; important; serious; severe",
        "pos": "名詞接続",
        "skip": false,
        "lookupWord": "大",
        "baseForm": "大",
        "conjugation": null
      },
      {
        "surface": "正解",
        "romaji": "seikai",
        "meaning": "correct answer; right solution; correct interpretation",
        "pos": "noun",
        "skip": false,
        "lookupWord": "正解",
        "baseForm": "正解",
        "conjugation": null
      }
    ],
    "translation": "You are the only one who is right in this world"
  },
  {
    "id": "l21",
    "start": 61.06,
    "end": 64.46,
    "tokens": [
      {
        "surface": "Darlin",
        "romaji": "Darlin",
        "meaning": "",
        "pos": "noun",
        "skip": true,
        "lookupWord": "",
        "baseForm": "",
        "conjugation": null
      },
      {
        "surface": "',",
        "romaji": "',",
        "meaning": "",
        "pos": "noun",
        "skip": true,
        "lookupWord": "",
        "baseForm": "",
        "conjugation": null
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "",
        "pos": "空白",
        "skip": true,
        "lookupWord": "",
        "baseForm": "",
        "conjugation": null
      },
      {
        "surface": "darlin",
        "romaji": "darlin",
        "meaning": "",
        "pos": "noun",
        "skip": true,
        "lookupWord": "",
        "baseForm": "",
        "conjugation": null
      },
      {
        "surface": "',",
        "romaji": "',",
        "meaning": "",
        "pos": "noun",
        "skip": true,
        "lookupWord": "",
        "baseForm": "",
        "conjugation": null
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "",
        "pos": "空白",
        "skip": true,
        "lookupWord": "",
        "baseForm": "",
        "conjugation": null
      },
      {
        "surface": "darlin",
        "romaji": "darlin",
        "meaning": "",
        "pos": "noun",
        "skip": true,
        "lookupWord": "",
        "baseForm": "",
        "conjugation": null
      },
      {
        "surface": "',",
        "romaji": "',",
        "meaning": "",
        "pos": "noun",
        "skip": true,
        "lookupWord": "",
        "baseForm": "",
        "conjugation": null
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "",
        "pos": "空白",
        "skip": true,
        "lookupWord": "",
        "baseForm": "",
        "conjugation": null
      },
      {
        "surface": "darlin",
        "romaji": "darlin",
        "meaning": "",
        "pos": "noun",
        "skip": true,
        "lookupWord": "",
        "baseForm": "",
        "conjugation": null
      },
      {
        "surface": "'",
        "romaji": "'",
        "meaning": "",
        "pos": "noun",
        "skip": true,
        "lookupWord": "",
        "baseForm": "",
        "conjugation": null
      }
    ],
    "translation": ""
  },
  {
    "id": "l22",
    "start": 64.46,
    "end": 74.67,
    "tokens": [
      {
        "surface": "Darlin",
        "romaji": "Darlin",
        "meaning": "",
        "pos": "noun",
        "skip": true,
        "lookupWord": "",
        "baseForm": "",
        "conjugation": null
      },
      {
        "surface": "',",
        "romaji": "',",
        "meaning": "",
        "pos": "noun",
        "skip": true,
        "lookupWord": "",
        "baseForm": "",
        "conjugation": null
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "",
        "pos": "空白",
        "skip": true,
        "lookupWord": "",
        "baseForm": "",
        "conjugation": null
      },
      {
        "surface": "darlin",
        "romaji": "darlin",
        "meaning": "",
        "pos": "noun",
        "skip": true,
        "lookupWord": "",
        "baseForm": "",
        "conjugation": null
      },
      {
        "surface": "',",
        "romaji": "',",
        "meaning": "",
        "pos": "noun",
        "skip": true,
        "lookupWord": "",
        "baseForm": "",
        "conjugation": null
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "",
        "pos": "空白",
        "skip": true,
        "lookupWord": "",
        "baseForm": "",
        "conjugation": null
      },
      {
        "surface": "darlin",
        "romaji": "darlin",
        "meaning": "",
        "pos": "noun",
        "skip": true,
        "lookupWord": "",
        "baseForm": "",
        "conjugation": null
      },
      {
        "surface": "',",
        "romaji": "',",
        "meaning": "",
        "pos": "noun",
        "skip": true,
        "lookupWord": "",
        "baseForm": "",
        "conjugation": null
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "",
        "pos": "空白",
        "skip": true,
        "lookupWord": "",
        "baseForm": "",
        "conjugation": null
      },
      {
        "surface": "darlin",
        "romaji": "darlin",
        "meaning": "",
        "pos": "noun",
        "skip": true,
        "lookupWord": "",
        "baseForm": "",
        "conjugation": null
      },
      {
        "surface": "'",
        "romaji": "'",
        "meaning": "",
        "pos": "noun",
        "skip": true,
        "lookupWord": "",
        "baseForm": "",
        "conjugation": null
      }
    ],
    "translation": ""
  },
  {
    "id": "l23",
    "start": 74.67,
    "end": 76.55,
    "tokens": [
      {
        "surface": "ひっくり返って",
        "romaji": "hikkurikaete",
        "meaning": "to be overturned; to be reversed; to turn over; to capsize",
        "pos": "verb",
        "skip": false,
        "lookupWord": "ひっくり返る",
        "baseForm": "ひっくり返る",
        "conjugation": "te-form"
      },
      {
        "surface": "も",
        "romaji": "mo",
        "meaning": "indicates addition or inclusion (also / too / as well)",
        "pos": "particle",
        "skip": false
      },
      {
        "surface": "勝ち",
        "romaji": "kachi",
        "meaning": "win; victory",
        "pos": "noun",
        "skip": false,
        "lookupWord": "勝ち",
        "baseForm": "勝ち",
        "conjugation": null
      },
      {
        "surface": "よう",
        "romaji": "you",
        "meaning": "appearing ...; looking ...",
        "pos": "noun",
        "skip": false,
        "lookupWord": "よう",
        "baseForm": "よう",
        "conjugation": null
      },
      {
        "surface": "ない",
        "romaji": "nai",
        "meaning": "nonexistent; not being (there)",
        "pos": "adjective",
        "skip": false,
        "lookupWord": "ない",
        "baseForm": "ない",
        "conjugation": null
      }
    ],
    "translation": "Even if I turn over, I can't win"
  },
  {
    "id": "l24",
    "start": 76.55,
    "end": 78.39,
    "tokens": [
      {
        "surface": "君",
        "romaji": "kimi",
        "meaning": "you; buddy; pal",
        "pos": "noun",
        "skip": false,
        "lookupWord": "君",
        "baseForm": "君",
        "conjugation": null
      },
      {
        "surface": "だけ",
        "romaji": "dake",
        "meaning": "only; just; merely; simply; no more than; nothing but; alone",
        "pos": "particle",
        "skip": false,
        "lookupWord": "だけ",
        "baseForm": "だけ",
        "conjugation": null
      },
      {
        "surface": "ルール",
        "romaji": "ruuru",
        "meaning": "rule",
        "pos": "noun",
        "skip": false,
        "lookupWord": "ルール",
        "baseForm": "ルール",
        "conjugation": null
      },
      {
        "surface": "は",
        "romaji": "ha",
        "meaning": "indicates topic of a sentence",
        "pos": "particle",
        "skip": false
      },
      {
        "surface": "適用",
        "romaji": "tekiyou",
        "meaning": "application (of a rule, law, method, etc.)",
        "pos": "noun",
        "skip": false,
        "lookupWord": "適用",
        "baseForm": "適用",
        "conjugation": null
      },
      {
        "surface": "外",
        "romaji": "gai",
        "meaning": "outside; exterior",
        "pos": "noun",
        "skip": false,
        "lookupWord": "外",
        "baseForm": "外",
        "conjugation": null
      }
    ],
    "translation": "Only you rule doesn't apply"
  },
  {
    "id": "l25",
    "start": 78.39,
    "end": 82,
    "tokens": [
      {
        "surface": "四つ",
        "romaji": "yottsu",
        "meaning": "four; 4",
        "pos": "noun",
        "skip": false,
        "lookupWord": "四つ",
        "baseForm": "四つ",
        "conjugation": null
      },
      {
        "surface": "とも",
        "romaji": "tomo",
        "meaning": "friend; companion; comrade; pal",
        "pos": "particle",
        "skip": false,
        "lookupWord": "とも",
        "baseForm": "とも",
        "conjugation": null
      },
      {
        "surface": "オセロ",
        "romaji": "osero",
        "meaning": "Oslo",
        "pos": "noun",
        "skip": false,
        "lookupWord": "オセロ",
        "baseForm": "オセロ",
        "conjugation": null
      },
      {
        "surface": "は",
        "romaji": "ha",
        "meaning": "indicates topic of a sentence",
        "pos": "particle",
        "skip": false
      },
      {
        "surface": "黒",
        "romaji": "kuro",
        "meaning": "black",
        "pos": "noun",
        "skip": false,
        "lookupWord": "黒",
        "baseForm": "黒",
        "conjugation": null
      },
      {
        "surface": "しか",
        "romaji": "shika",
        "meaning": "deer (esp. the sika deer, Cervus nippon); cervid",
        "pos": "particle",
        "skip": false,
        "lookupWord": "しか",
        "baseForm": "しか",
        "conjugation": null
      },
      {
        "surface": "ない",
        "romaji": "nai",
        "meaning": "nonexistent; not being (there)",
        "pos": "adjective",
        "skip": false,
        "lookupWord": "ない",
        "baseForm": "ない",
        "conjugation": null
      }
    ],
    "translation": "All four Othellos are only black"
  },
  {
    "id": "l26",
    "start": 82,
    "end": 84.13,
    "tokens": [
      {
        "surface": "君",
        "romaji": "kimi",
        "meaning": "you; buddy; pal",
        "pos": "noun",
        "skip": false,
        "lookupWord": "君",
        "baseForm": "君",
        "conjugation": null
      },
      {
        "surface": "が",
        "romaji": "ga",
        "meaning": "indicates subject of a sentence",
        "pos": "particle",
        "skip": false
      },
      {
        "surface": "笑顔",
        "romaji": "egao",
        "meaning": "smiling face; smile",
        "pos": "noun",
        "skip": false,
        "lookupWord": "笑顔",
        "baseForm": "笑顔",
        "conjugation": null
      },
      {
        "surface": "で",
        "romaji": "de",
        "meaning": "indicates location of action, means, or method (at / by / with)",
        "pos": "particle",
        "skip": false
      },
      {
        "surface": "放った",
        "romaji": "hanata",
        "meaning": "to fire (gun, arrow, questions, etc.); to shoot; to hit (e.g. baseball); to break wind",
        "pos": "verb",
        "skip": false,
        "lookupWord": "放つ",
        "baseForm": "放つ",
        "conjugation": "auxiliary / conjugated"
      },
      {
        "surface": "アバダケダブラ",
        "romaji": "abadakedabura",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "noun",
        "skip": false,
        "lookupWord": "アバダケダブラ",
        "baseForm": "アバダケダブラ",
        "conjugation": null
      }
    ],
    "translation": "The Avada Kedabura you released with a smile"
  },
  {
    "id": "l27",
    "start": 84.13,
    "end": 86.08,
    "tokens": [
      {
        "surface": "デコ",
        "romaji": "deko",
        "meaning": "decoration; ornamental item",
        "pos": "noun",
        "skip": false,
        "lookupWord": "デコ",
        "baseForm": "デコ",
        "conjugation": null
      },
      {
        "surface": "に",
        "romaji": "ni",
        "meaning": "indicates direction, destination, time, or target (to / at / in)",
        "pos": "particle",
        "skip": false
      },
      {
        "surface": "スティグマ",
        "romaji": "suteiguma",
        "meaning": "stigma",
        "pos": "noun",
        "skip": false,
        "lookupWord": "スティグマ",
        "baseForm": "スティグマ",
        "conjugation": null
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "",
        "pos": "空白",
        "skip": true,
        "lookupWord": "",
        "baseForm": "",
        "conjugation": null
      },
      {
        "surface": "申し訳",
        "romaji": "moushiwake",
        "meaning": "apology; excuse",
        "pos": "noun",
        "skip": false,
        "lookupWord": "申し訳",
        "baseForm": "申し訳",
        "conjugation": null
      },
      {
        "surface": "ねえ",
        "romaji": "nee",
        "meaning": "nonexistent; not being (there)",
        "pos": "auxiliary verb",
        "skip": false,
        "lookupWord": "ない",
        "baseForm": "ない",
        "conjugation": null
      },
      {
        "surface": "な",
        "romaji": "na",
        "meaning": "don't",
        "pos": "particle",
        "skip": false,
        "lookupWord": "な",
        "baseForm": "な",
        "conjugation": null
      }
    ],
    "translation": "I'm sorry for the stigma on the deco"
  },
  {
    "id": "l28",
    "start": 86.08,
    "end": 87.92,
    "tokens": [
      {
        "surface": "矢",
        "romaji": "ya",
        "meaning": "arrow",
        "pos": "noun",
        "skip": false,
        "lookupWord": "矢",
        "baseForm": "矢",
        "conjugation": null
      },
      {
        "surface": "を",
        "romaji": "wo",
        "meaning": "indicates direct object of an action",
        "pos": "particle",
        "skip": false
      },
      {
        "surface": "刺して",
        "romaji": "sashite",
        "meaning": "to pierce; to stab; to prick; to stick; to thrust",
        "pos": "verb",
        "skip": false,
        "lookupWord": "刺す",
        "baseForm": "刺す",
        "conjugation": "te-form"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "",
        "pos": "空白",
        "skip": true,
        "lookupWord": "",
        "baseForm": "",
        "conjugation": null
      },
      {
        "surface": "貫いて",
        "romaji": "tsuranuite",
        "meaning": "to go through; to pierce; to penetrate",
        "pos": "verb",
        "skip": false,
        "lookupWord": "貫く",
        "baseForm": "貫く",
        "conjugation": "te-form"
      }
    ],
    "translation": "Pierce with an arrow"
  },
  {
    "id": "l29",
    "start": 87.92,
    "end": 89.04,
    "tokens": [
      {
        "surface": "ここ",
        "romaji": "koko",
        "meaning": "individual; one by one; separate; each",
        "pos": "noun",
        "skip": false,
        "lookupWord": "ここ",
        "baseForm": "ここ",
        "conjugation": null
      },
      {
        "surface": "弱点",
        "romaji": "jakuten",
        "meaning": "weak point; weakness; shortcoming; defect; flaw; sore spot; tender spot",
        "pos": "noun",
        "skip": false,
        "lookupWord": "弱点",
        "baseForm": "弱点",
        "conjugation": null
      }
    ],
    "translation": "This is the weak point"
  },
  {
    "id": "l30",
    "start": 89.04,
    "end": 90.84,
    "tokens": [
      {
        "surface": "死ぬ",
        "romaji": "shinu",
        "meaning": "to die; to pass away",
        "pos": "verb",
        "skip": false,
        "lookupWord": "死ぬ",
        "baseForm": "死ぬ",
        "conjugation": null
      },
      {
        "surface": "ほど",
        "romaji": "hodo",
        "meaning": "extent; degree; measure",
        "pos": "particle",
        "skip": false,
        "lookupWord": "ほど",
        "baseForm": "ほど",
        "conjugation": null
      },
      {
        "surface": "可愛い",
        "romaji": "kawaii",
        "meaning": "cute; adorable; charming; lovely; pretty",
        "pos": "adjective",
        "skip": false,
        "lookupWord": "可愛い",
        "baseForm": "可愛い",
        "conjugation": null
      },
      {
        "surface": "上目遣い",
        "romaji": "uwamezukai",
        "meaning": "looking at someone (with upturned eyes); glancing upwards (at someone)",
        "pos": "noun",
        "skip": false,
        "lookupWord": "上目遣い",
        "baseForm": "上目遣い",
        "conjugation": null
      }
    ],
    "translation": "Deadly cute look"
  },
  {
    "id": "l31",
    "start": 90.84,
    "end": 92.6,
    "tokens": [
      {
        "surface": "なにがし",
        "romaji": "nanigashi",
        "meaning": "certain amount; some",
        "pos": "noun",
        "skip": false,
        "lookupWord": "なにがし",
        "baseForm": "なにがし",
        "conjugation": null
      },
      {
        "surface": "法",
        "romaji": "hou",
        "meaning": "law; act; principle",
        "pos": "noun",
        "skip": false,
        "lookupWord": "法",
        "baseForm": "法",
        "conjugation": null
      },
      {
        "surface": "に",
        "romaji": "ni",
        "meaning": "indicates direction, destination, time, or target (to / at / in)",
        "pos": "particle",
        "skip": false
      },
      {
        "surface": "触れる",
        "romaji": "fureru",
        "meaning": "to touch; to feel",
        "pos": "verb",
        "skip": false,
        "lookupWord": "触れる",
        "baseForm": "触れる",
        "conjugation": null
      },
      {
        "surface": "くらい",
        "romaji": "kurai",
        "meaning": "dark; gloomy; murky",
        "pos": "particle",
        "skip": false,
        "lookupWord": "くらい",
        "baseForm": "くらい",
        "conjugation": null
      }
    ],
    "translation": "It's almost like breaking the law"
  },
  {
    "id": "l32",
    "start": 92.6,
    "end": 94.36,
    "tokens": [
      {
        "surface": "ばら",
        "romaji": "bara",
        "meaning": "rose",
        "pos": "noun",
        "skip": false,
        "lookupWord": "ばら",
        "baseForm": "ばら",
        "conjugation": null
      },
      {
        "surface": "撒く",
        "romaji": "maku",
        "meaning": "to scatter; to sprinkle; to strew",
        "pos": "verb",
        "skip": false,
        "lookupWord": "撒く",
        "baseForm": "撒く",
        "conjugation": null
      },
      {
        "surface": "乱心",
        "romaji": "ranshin",
        "meaning": "mental derangement; madness; insanity",
        "pos": "noun",
        "skip": false,
        "lookupWord": "乱心",
        "baseForm": "乱心",
        "conjugation": null
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "",
        "pos": "空白",
        "skip": true,
        "lookupWord": "",
        "baseForm": "",
        "conjugation": null
      },
      {
        "surface": "気づけ",
        "romaji": "kizuke",
        "meaning": "to notice; to realize; to realise; to become aware (of); to perceive; to sense; to suspect",
        "pos": "verb",
        "skip": false,
        "lookupWord": "気づく",
        "baseForm": "気づく",
        "conjugation": null
      },
      {
        "surface": "ば",
        "romaji": "ba",
        "meaning": "place; spot; space",
        "pos": "particle",
        "skip": false,
        "lookupWord": "ば",
        "baseForm": "ば",
        "conjugation": null
      },
      {
        "surface": "蕩尽",
        "romaji": "toujin",
        "meaning": "squandering; dissipation",
        "pos": "noun",
        "skip": false,
        "lookupWord": "蕩尽",
        "baseForm": "蕩尽",
        "conjugation": null
      }
    ],
    "translation": "Spreading madness, before you know it, you've exhausted yourself"
  },
  {
    "id": "l33",
    "start": 94.36,
    "end": 96.12,
    "tokens": [
      {
        "surface": "この世",
        "romaji": "konoyo",
        "meaning": "this world; this life; world of the living",
        "pos": "noun",
        "skip": false,
        "lookupWord": "この世",
        "baseForm": "この世",
        "conjugation": null
      },
      {
        "surface": "に",
        "romaji": "ni",
        "meaning": "indicates direction, destination, time, or target (to / at / in)",
        "pos": "particle",
        "skip": false
      },
      {
        "surface": "生まれた",
        "romaji": "umareta",
        "meaning": "to be born",
        "pos": "verb",
        "skip": false,
        "lookupWord": "生まれる",
        "baseForm": "生まれる",
        "conjugation": "auxiliary / conjugated"
      },
      {
        "surface": "君",
        "romaji": "kimi",
        "meaning": "you; buddy; pal",
        "pos": "noun",
        "skip": false,
        "lookupWord": "君",
        "baseForm": "君",
        "conjugation": null
      },
      {
        "surface": "が",
        "romaji": "ga",
        "meaning": "indicates subject of a sentence",
        "pos": "particle",
        "skip": false
      },
      {
        "surface": "悪い",
        "romaji": "warui",
        "meaning": "bad; poor; undesirable",
        "pos": "adjective",
        "skip": false,
        "lookupWord": "悪い",
        "baseForm": "悪い",
        "conjugation": null
      }
    ],
    "translation": "It's your fault for being born into this world"
  },
  {
    "id": "l34",
    "start": 96.12,
    "end": 97.76,
    "tokens": [
      {
        "surface": "パチ",
        "romaji": "pachi",
        "meaning": "snapping (e.g. book shut); clapping; crackling; sputtering",
        "pos": "adverb",
        "skip": false,
        "lookupWord": "パチ",
        "baseForm": "パチ",
        "conjugation": null
      },
      {
        "surface": "モン",
        "romaji": "mon",
        "meaning": "monster; monstrosity",
        "pos": "noun",
        "skip": false,
        "lookupWord": "モン",
        "baseForm": "モン",
        "conjugation": null
      },
      {
        "surface": "で",
        "romaji": "de",
        "meaning": "indicates location of action, means, or method (at / by / with)",
        "pos": "particle",
        "skip": false
      },
      {
        "surface": "も",
        "romaji": "mo",
        "meaning": "indicates addition or inclusion (also / too / as well)",
        "pos": "particle",
        "skip": false
      },
      {
        "surface": "いい",
        "romaji": "ii",
        "meaning": "good; excellent; fine; nice; pleasant; agreeable",
        "pos": "adjective",
        "skip": false,
        "lookupWord": "いい",
        "baseForm": "いい",
        "conjugation": null
      },
      {
        "surface": "何",
        "romaji": "nani",
        "meaning": "what",
        "pos": "noun",
        "skip": false,
        "lookupWord": "何",
        "baseForm": "何",
        "conjugation": null
      },
      {
        "surface": "でも",
        "romaji": "demo",
        "meaning": "but; however; though; nevertheless; still; yet; even so; also; as well",
        "pos": "particle",
        "skip": false,
        "lookupWord": "でも",
        "baseForm": "でも",
        "conjugation": null
      },
      {
        "surface": "いい",
        "romaji": "ii",
        "meaning": "to say; to utter; to declare",
        "pos": "verb",
        "skip": false,
        "lookupWord": "いう",
        "baseForm": "いう",
        "conjugation": null
      }
    ],
    "translation": "Pachimon or anything is fine"
  },
  {
    "id": "l35",
    "start": 97.76,
    "end": 99.6,
    "tokens": [
      {
        "surface": "今",
        "romaji": "ima",
        "meaning": "now; the present time; just now; soon; immediately",
        "pos": "noun",
        "skip": false,
        "lookupWord": "今",
        "baseForm": "今",
        "conjugation": null
      },
      {
        "surface": "君",
        "romaji": "kun",
        "meaning": "you; buddy; pal",
        "pos": "noun",
        "skip": false,
        "lookupWord": "君",
        "baseForm": "君",
        "conjugation": null
      },
      {
        "surface": "と",
        "romaji": "to",
        "meaning": "indicates togetherness or quotation (and / with)",
        "pos": "particle",
        "skip": false
      },
      {
        "surface": "名付",
        "romaji": "nazuke",
        "meaning": "to name; to call; to christen; to term",
        "pos": "noun",
        "skip": false,
        "lookupWord": "名付",
        "baseForm": "名付",
        "conjugation": null
      },
      {
        "surface": "いてる",
        "romaji": "iteru",
        "meaning": "to freeze; to freeze over",
        "pos": "verb",
        "skip": false,
        "lookupWord": "いてる",
        "baseForm": "いてる",
        "conjugation": null
      },
      {
        "surface": "全て",
        "romaji": "subete",
        "meaning": "everything; all; the whole",
        "pos": "noun",
        "skip": false,
        "lookupWord": "全て",
        "baseForm": "全て",
        "conjugation": null
      },
      {
        "surface": "欲しい",
        "romaji": "hoshii",
        "meaning": "wanting (to have); desiring; wishing for",
        "pos": "adjective",
        "skip": false,
        "lookupWord": "欲しい",
        "baseForm": "欲しい",
        "conjugation": null
      }
    ],
    "translation": "I want everything that has your name on it right now"
  },
  {
    "id": "l36",
    "start": 99.6,
    "end": 102.04,
    "tokens": [
      {
        "surface": "頸",
        "romaji": "頸",
        "meaning": "neck",
        "pos": "noun",
        "skip": false,
        "lookupWord": "頸",
        "baseForm": "頸",
        "conjugation": null
      },
      {
        "surface": "動脈",
        "romaji": "doumyaku",
        "meaning": "artery",
        "pos": "noun",
        "skip": false,
        "lookupWord": "動脈",
        "baseForm": "動脈",
        "conjugation": null
      },
      {
        "surface": "から",
        "romaji": "kara",
        "meaning": "indicates starting point or cause (from / because)",
        "pos": "particle",
        "skip": false
      },
      {
        "surface": "アイラブユー",
        "romaji": "airabuyuu",
        "meaning": "I love you",
        "pos": "noun",
        "skip": false,
        "lookupWord": "アイラブユー",
        "baseForm": "アイラブユー",
        "conjugation": null
      },
      {
        "surface": "が",
        "romaji": "ga",
        "meaning": "indicates subject of a sentence",
        "pos": "particle",
        "skip": false
      },
      {
        "surface": "噴き",
        "romaji": "fuki",
        "meaning": "to emit; to spout; to spurt; to boil over",
        "pos": "verb",
        "skip": false,
        "lookupWord": "噴く",
        "baseForm": "噴く",
        "conjugation": null
      },
      {
        "surface": "出て",
        "romaji": "dete",
        "meaning": "to leave; to exit; to go out; to come out; to get out",
        "pos": "verb",
        "skip": false,
        "lookupWord": "出る",
        "baseForm": "出る",
        "conjugation": "te-form"
      }
    ],
    "translation": "I love you is gushing out from my carotid artery"
  },
  {
    "id": "l37",
    "start": 102.04,
    "end": 102.88,
    "tokens": [
      {
        "surface": "ア",
        "romaji": "a",
        "meaning": "ah; oh",
        "pos": "noun",
        "skip": false,
        "lookupWord": "ア",
        "baseForm": "ア",
        "conjugation": null
      },
      {
        "surface": "、",
        "romaji": ",",
        "meaning": "",
        "pos": "読点",
        "skip": true,
        "lookupWord": "",
        "baseForm": "",
        "conjugation": null
      },
      {
        "surface": "ア",
        "romaji": "a",
        "meaning": "ah; oh",
        "pos": "noun",
        "skip": false,
        "lookupWord": "ア",
        "baseForm": "ア",
        "conjugation": null
      },
      {
        "surface": "、",
        "romaji": ",",
        "meaning": "",
        "pos": "読点",
        "skip": true,
        "lookupWord": "",
        "baseForm": "",
        "conjugation": null
      },
      {
        "surface": "ア",
        "romaji": "a",
        "meaning": "ah; oh",
        "pos": "noun",
        "skip": false,
        "lookupWord": "ア",
        "baseForm": "ア",
        "conjugation": null
      },
      {
        "surface": "、",
        "romaji": ",",
        "meaning": "",
        "pos": "読点",
        "skip": true,
        "lookupWord": "",
        "baseForm": "",
        "conjugation": null
      },
      {
        "surface": "ア",
        "romaji": "a",
        "meaning": "ah; oh",
        "pos": "noun",
        "skip": false,
        "lookupWord": "ア",
        "baseForm": "ア",
        "conjugation": null
      }
    ],
    "translation": ""
  },
  {
    "id": "l38",
    "start": 102.88,
    "end": 109.17,
    "tokens": [
      {
        "surface": "アイリス",
        "romaji": "airisu",
        "meaning": "iris",
        "pos": "noun",
        "skip": false,
        "lookupWord": "アイリス",
        "baseForm": "アイリス",
        "conjugation": null
      },
      {
        "surface": "アウト",
        "romaji": "auto",
        "meaning": "out (of a ball; in tennis, etc.); outside the line",
        "pos": "noun",
        "skip": false,
        "lookupWord": "アウト",
        "baseForm": "アウト",
        "conjugation": null
      }
    ],
    "translation": "Iris out"
  },
  {
    "id": "l39",
    "start": 109.17,
    "end": 110.04,
    "tokens": [
      {
        "surface": "ア",
        "romaji": "a",
        "meaning": "ah; oh",
        "pos": "noun",
        "skip": false,
        "lookupWord": "ア",
        "baseForm": "ア",
        "conjugation": null
      },
      {
        "surface": "、",
        "romaji": ",",
        "meaning": "",
        "pos": "読点",
        "skip": true,
        "lookupWord": "",
        "baseForm": "",
        "conjugation": null
      },
      {
        "surface": "ア",
        "romaji": "a",
        "meaning": "ah; oh",
        "pos": "noun",
        "skip": false,
        "lookupWord": "ア",
        "baseForm": "ア",
        "conjugation": null
      },
      {
        "surface": "、",
        "romaji": ",",
        "meaning": "",
        "pos": "読点",
        "skip": true,
        "lookupWord": "",
        "baseForm": "",
        "conjugation": null
      },
      {
        "surface": "ア",
        "romaji": "a",
        "meaning": "ah; oh",
        "pos": "noun",
        "skip": false,
        "lookupWord": "ア",
        "baseForm": "ア",
        "conjugation": null
      },
      {
        "surface": "、",
        "romaji": ",",
        "meaning": "",
        "pos": "読点",
        "skip": true,
        "lookupWord": "",
        "baseForm": "",
        "conjugation": null
      },
      {
        "surface": "ア",
        "romaji": "a",
        "meaning": "ah; oh",
        "pos": "noun",
        "skip": false,
        "lookupWord": "ア",
        "baseForm": "ア",
        "conjugation": null
      }
    ],
    "translation": ""
  },
  {
    "id": "l40",
    "start": 110.04,
    "end": 115.17,
    "tokens": [
      {
        "surface": "アイリス",
        "romaji": "airisu",
        "meaning": "iris",
        "pos": "noun",
        "skip": false,
        "lookupWord": "アイリス",
        "baseForm": "アイリス",
        "conjugation": null
      },
      {
        "surface": "アウト",
        "romaji": "auto",
        "meaning": "out (of a ball; in tennis, etc.); outside the line",
        "pos": "noun",
        "skip": false,
        "lookupWord": "アウト",
        "baseForm": "アウト",
        "conjugation": null
      }
    ],
    "translation": "Iris out"
  },
  {
    "id": "l41",
    "start": 115.17,
    "end": 116.25,
    "tokens": [
      {
        "surface": "ア",
        "romaji": "a",
        "meaning": "ah; oh",
        "pos": "noun",
        "skip": false,
        "lookupWord": "ア",
        "baseForm": "ア",
        "conjugation": null
      },
      {
        "surface": "、",
        "romaji": ",",
        "meaning": "",
        "pos": "読点",
        "skip": true,
        "lookupWord": "",
        "baseForm": "",
        "conjugation": null
      },
      {
        "surface": "ア",
        "romaji": "a",
        "meaning": "ah; oh",
        "pos": "noun",
        "skip": false,
        "lookupWord": "ア",
        "baseForm": "ア",
        "conjugation": null
      },
      {
        "surface": "、",
        "romaji": ",",
        "meaning": "",
        "pos": "読点",
        "skip": true,
        "lookupWord": "",
        "baseForm": "",
        "conjugation": null
      },
      {
        "surface": "ア",
        "romaji": "a",
        "meaning": "ah; oh",
        "pos": "noun",
        "skip": false,
        "lookupWord": "ア",
        "baseForm": "ア",
        "conjugation": null
      },
      {
        "surface": "、",
        "romaji": ",",
        "meaning": "",
        "pos": "読点",
        "skip": true,
        "lookupWord": "",
        "baseForm": "",
        "conjugation": null
      },
      {
        "surface": "ア",
        "romaji": "a",
        "meaning": "ah; oh",
        "pos": "noun",
        "skip": false,
        "lookupWord": "ア",
        "baseForm": "ア",
        "conjugation": null
      }
    ],
    "translation": ""
  },
  {
    "id": "l42",
    "start": 116.25,
    "end": 117.57,
    "tokens": [
      {
        "surface": "アイリス",
        "romaji": "airisu",
        "meaning": "iris",
        "pos": "noun",
        "skip": false,
        "lookupWord": "アイリス",
        "baseForm": "アイリス",
        "conjugation": null
      },
      {
        "surface": "アウト",
        "romaji": "auto",
        "meaning": "out (of a ball; in tennis, etc.); outside the line",
        "pos": "noun",
        "skip": false,
        "lookupWord": "アウト",
        "baseForm": "アウト",
        "conjugation": null
      }
    ],
    "translation": "Iris out"
  },
  {
    "id": "l43",
    "start": 117.57,
    "end": 119.73,
    "tokens": [
      {
        "surface": "一体",
        "romaji": "ittai",
        "meaning": "(what) the heck; (why) in the world; (who) on earth; (where) the hell; (how) the hell",
        "pos": "adverb",
        "skip": false,
        "lookupWord": "一体",
        "baseForm": "一体",
        "conjugation": null
      },
      {
        "surface": "どう",
        "romaji": "dou",
        "meaning": "copper (Cu)",
        "pos": "adverb",
        "skip": false,
        "lookupWord": "どう",
        "baseForm": "どう",
        "conjugation": null
      },
      {
        "surface": "しよう",
        "romaji": "shiyou",
        "meaning": "to do; to carry out; to perform",
        "pos": "verb",
        "skip": false,
        "lookupWord": "する",
        "baseForm": "する",
        "conjugation": "auxiliary / conjugated"
      },
      {
        "surface": "この",
        "romaji": "kono",
        "meaning": "this",
        "pos": "adjectival",
        "skip": false,
        "lookupWord": "この",
        "baseForm": "この",
        "conjugation": null
      },
      {
        "surface": "想い",
        "romaji": "omoi",
        "meaning": "thought",
        "pos": "noun",
        "skip": false,
        "lookupWord": "想い",
        "baseForm": "想い",
        "conjugation": null
      },
      {
        "surface": "を",
        "romaji": "wo",
        "meaning": "indicates direct object of an action",
        "pos": "particle",
        "skip": false
      }
    ],
    "translation": "What should I do with these feelings?"
  },
  {
    "id": "l44",
    "start": 119.73,
    "end": 121.45,
    "tokens": [
      {
        "surface": "どう",
        "romaji": "dou",
        "meaning": "copper (Cu)",
        "pos": "adverb",
        "skip": false,
        "lookupWord": "どう",
        "baseForm": "どう",
        "conjugation": null
      },
      {
        "surface": "しよう",
        "romaji": "shiyou",
        "meaning": "to do; to carry out; to perform",
        "pos": "verb",
        "skip": false,
        "lookupWord": "する",
        "baseForm": "する",
        "conjugation": "auxiliary / conjugated"
      },
      {
        "surface": "あ",
        "romaji": "a",
        "meaning": "sub-; second-rate; inferior",
        "pos": "フィラー",
        "skip": false,
        "lookupWord": "あ",
        "baseForm": "あ",
        "conjugation": null
      },
      {
        "surface": "ばら",
        "romaji": "bara",
        "meaning": "rose",
        "pos": "noun",
        "skip": false,
        "lookupWord": "ばら",
        "baseForm": "ばら",
        "conjugation": null
      },
      {
        "surface": "の",
        "romaji": "no",
        "meaning": "indicates possession or noun modification (of / 's)",
        "pos": "particle",
        "skip": false
      },
      {
        "surface": "奥",
        "romaji": "oku",
        "meaning": "inner part; interior; back (of a drawer, one's throat, etc.); depths (e.g. of a forest); recesses (e.g. of a cave); heart; end (of a road, garden, etc.)",
        "pos": "noun",
        "skip": false,
        "lookupWord": "奥",
        "baseForm": "奥",
        "conjugation": null
      },
      {
        "surface": "を",
        "romaji": "wo",
        "meaning": "indicates direct object of an action",
        "pos": "particle",
        "skip": false
      }
    ],
    "translation": "What should I do inside the ribs?"
  },
  {
    "id": "l45",
    "start": 121.45,
    "end": 124.56,
    "tokens": [
      {
        "surface": "ザラメ",
        "romaji": "zarame",
        "meaning": "granulated sugar; brown sugar",
        "pos": "noun",
        "skip": false,
        "lookupWord": "ザラメ",
        "baseForm": "ザラメ",
        "conjugation": null
      },
      {
        "surface": "が",
        "romaji": "ga",
        "meaning": "indicates subject of a sentence",
        "pos": "particle",
        "skip": false
      },
      {
        "surface": "溶けて",
        "romaji": "tokete",
        "meaning": "to melt; to liquefy; to soften (e.g. through heat); to thaw",
        "pos": "verb",
        "skip": false,
        "lookupWord": "溶ける",
        "baseForm": "溶ける",
        "conjugation": "te-form"
      },
      {
        "surface": "ゲロ",
        "romaji": "gero",
        "meaning": "vomit; spew; puke; vomiting",
        "pos": "noun",
        "skip": false,
        "lookupWord": "ゲロ",
        "baseForm": "ゲロ",
        "conjugation": null
      },
      {
        "surface": "に",
        "romaji": "ni",
        "meaning": "indicates direction, destination, time, or target (to / at / in)",
        "pos": "particle",
        "skip": false
      },
      {
        "surface": "なり",
        "romaji": "nari",
        "meaning": "to become; to get; to grow; to turn; to reach; to attain",
        "pos": "verb",
        "skip": false,
        "lookupWord": "なる",
        "baseForm": "なる",
        "conjugation": null
      },
      {
        "surface": "そう",
        "romaji": "sou",
        "meaning": "monk; priest",
        "pos": "noun",
        "skip": false,
        "lookupWord": "そう",
        "baseForm": "そう",
        "conjugation": null
      }
    ],
    "translation": "The grains will melt and turn into vomit"
  },
  {
    "id": "l46",
    "start": 124.56,
    "end": 125.17,
    "tokens": [
      {
        "surface": "BUM",
        "romaji": "BUM",
        "meaning": "",
        "pos": "noun",
        "skip": true,
        "lookupWord": "",
        "baseForm": "",
        "conjugation": null
      }
    ],
    "translation": ""
  },
  {
    "id": "l47",
    "start": 125.17,
    "end": 128.09,
    "tokens": [
      {
        "surface": "瞳孔",
        "romaji": "doukou",
        "meaning": "pupil (of the eye)",
        "pos": "noun",
        "skip": false,
        "lookupWord": "瞳孔",
        "baseForm": "瞳孔",
        "conjugation": null
      },
      {
        "surface": "バチ",
        "romaji": "bachi",
        "meaning": "plectrum (for a shamisen, biwa, etc.); pick",
        "pos": "noun",
        "skip": false,
        "lookupWord": "バチ",
        "baseForm": "バチ",
        "conjugation": null
      },
      {
        "surface": "開いて",
        "romaji": "hiraite",
        "meaning": "to open; to undo; to unseal; to unpack",
        "pos": "verb",
        "skip": false,
        "lookupWord": "開く",
        "baseForm": "開く",
        "conjugation": "te-form"
      },
      {
        "surface": "溺れ死",
        "romaji": "oborejini",
        "meaning": "to die by drowning; to drown",
        "pos": "noun",
        "skip": false,
        "lookupWord": "溺れ死",
        "baseForm": "溺れ死",
        "conjugation": null
      },
      {
        "surface": "に",
        "romaji": "ni",
        "meaning": "indicates direction, destination, time, or target (to / at / in)",
        "pos": "particle",
        "skip": false
      },
      {
        "surface": "そう",
        "romaji": "sou",
        "meaning": "monk; priest",
        "pos": "adverb",
        "skip": false,
        "lookupWord": "そう",
        "baseForm": "そう",
        "conjugation": null
      }
    ],
    "translation": "My pupils are dilated and I feel like I'm drowning"
  },
  {
    "id": "l48",
    "start": 128.09,
    "end": 132.13,
    "tokens": [
      {
        "surface": "今",
        "romaji": "kon",
        "meaning": "now; the present time; just now; soon; immediately",
        "pos": "名詞接続",
        "skip": false,
        "lookupWord": "今",
        "baseForm": "今",
        "conjugation": null
      },
      {
        "surface": "この世",
        "romaji": "konoyo",
        "meaning": "this world; this life; world of the living",
        "pos": "noun",
        "skip": false,
        "lookupWord": "この世",
        "baseForm": "この世",
        "conjugation": null
      },
      {
        "surface": "で",
        "romaji": "de",
        "meaning": "indicates location of action, means, or method (at / by / with)",
        "pos": "particle",
        "skip": false
      },
      {
        "surface": "君",
        "romaji": "kimi",
        "meaning": "you; buddy; pal",
        "pos": "noun",
        "skip": false,
        "lookupWord": "君",
        "baseForm": "君",
        "conjugation": null
      },
      {
        "surface": "だけ",
        "romaji": "dake",
        "meaning": "only; just; merely; simply; no more than; nothing but; alone",
        "pos": "particle",
        "skip": false,
        "lookupWord": "だけ",
        "baseForm": "だけ",
        "conjugation": null
      },
      {
        "surface": "大",
        "romaji": "dai",
        "meaning": "large; big; great; huge; vast; major; important; serious; severe",
        "pos": "名詞接続",
        "skip": false,
        "lookupWord": "大",
        "baseForm": "大",
        "conjugation": null
      },
      {
        "surface": "正解",
        "romaji": "seikai",
        "meaning": "correct answer; right solution; correct interpretation",
        "pos": "noun",
        "skip": false,
        "lookupWord": "正解",
        "baseForm": "正解",
        "conjugation": null
      }
    ],
    "translation": "You are the only one who is right in this world"
  },
  {
    "id": "l49",
    "start": 132.13,
    "end": 135.73,
    "tokens": [
      {
        "surface": "Darlin",
        "romaji": "Darlin",
        "meaning": "",
        "pos": "noun",
        "skip": true,
        "lookupWord": "",
        "baseForm": "",
        "conjugation": null
      },
      {
        "surface": "',",
        "romaji": "',",
        "meaning": "",
        "pos": "noun",
        "skip": true,
        "lookupWord": "",
        "baseForm": "",
        "conjugation": null
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "",
        "pos": "空白",
        "skip": true,
        "lookupWord": "",
        "baseForm": "",
        "conjugation": null
      },
      {
        "surface": "darlin",
        "romaji": "darlin",
        "meaning": "",
        "pos": "noun",
        "skip": true,
        "lookupWord": "",
        "baseForm": "",
        "conjugation": null
      },
      {
        "surface": "',",
        "romaji": "',",
        "meaning": "",
        "pos": "noun",
        "skip": true,
        "lookupWord": "",
        "baseForm": "",
        "conjugation": null
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "",
        "pos": "空白",
        "skip": true,
        "lookupWord": "",
        "baseForm": "",
        "conjugation": null
      },
      {
        "surface": "darlin",
        "romaji": "darlin",
        "meaning": "",
        "pos": "noun",
        "skip": true,
        "lookupWord": "",
        "baseForm": "",
        "conjugation": null
      },
      {
        "surface": "',",
        "romaji": "',",
        "meaning": "",
        "pos": "noun",
        "skip": true,
        "lookupWord": "",
        "baseForm": "",
        "conjugation": null
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "",
        "pos": "空白",
        "skip": true,
        "lookupWord": "",
        "baseForm": "",
        "conjugation": null
      },
      {
        "surface": "darlin",
        "romaji": "darlin",
        "meaning": "",
        "pos": "noun",
        "skip": true,
        "lookupWord": "",
        "baseForm": "",
        "conjugation": null
      },
      {
        "surface": "'",
        "romaji": "'",
        "meaning": "",
        "pos": "noun",
        "skip": true,
        "lookupWord": "",
        "baseForm": "",
        "conjugation": null
      }
    ],
    "translation": ""
  },
  {
    "id": "l50",
    "start": 135.73,
    "end": 139.73,
    "tokens": [
      {
        "surface": "Darlin",
        "romaji": "Darlin",
        "meaning": "",
        "pos": "noun",
        "skip": true,
        "lookupWord": "",
        "baseForm": "",
        "conjugation": null
      },
      {
        "surface": "',",
        "romaji": "',",
        "meaning": "",
        "pos": "noun",
        "skip": true,
        "lookupWord": "",
        "baseForm": "",
        "conjugation": null
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "",
        "pos": "空白",
        "skip": true,
        "lookupWord": "",
        "baseForm": "",
        "conjugation": null
      },
      {
        "surface": "darlin",
        "romaji": "darlin",
        "meaning": "",
        "pos": "noun",
        "skip": true,
        "lookupWord": "",
        "baseForm": "",
        "conjugation": null
      },
      {
        "surface": "',",
        "romaji": "',",
        "meaning": "",
        "pos": "noun",
        "skip": true,
        "lookupWord": "",
        "baseForm": "",
        "conjugation": null
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "",
        "pos": "空白",
        "skip": true,
        "lookupWord": "",
        "baseForm": "",
        "conjugation": null
      },
      {
        "surface": "darlin",
        "romaji": "darlin",
        "meaning": "",
        "pos": "noun",
        "skip": true,
        "lookupWord": "",
        "baseForm": "",
        "conjugation": null
      },
      {
        "surface": "',",
        "romaji": "',",
        "meaning": "",
        "pos": "noun",
        "skip": true,
        "lookupWord": "",
        "baseForm": "",
        "conjugation": null
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "",
        "pos": "空白",
        "skip": true,
        "lookupWord": "",
        "baseForm": "",
        "conjugation": null
      },
      {
        "surface": "darlin",
        "romaji": "darlin",
        "meaning": "",
        "pos": "noun",
        "skip": true,
        "lookupWord": "",
        "baseForm": "",
        "conjugation": null
      },
      {
        "surface": "'",
        "romaji": "'",
        "meaning": "",
        "pos": "noun",
        "skip": true,
        "lookupWord": "",
        "baseForm": "",
        "conjugation": null
      }
    ],
    "translation": ""
  }
];
