import { LyricLine } from "@/lib/types";

// Auto-generated by scripts/generate-lyrics.mjs for "new genesis" by ado.
// Words come from kuromoji (segmentation), wanakana (romaji), and Jisho
// (dictionary meanings) — spot-check before shipping, don't trust blindly.
export const newGenesisLyrics: LyricLine[] = [
  {
    "id": "l1",
    "start": 0.42,
    "end": 4.42,
    "text": "新時代はこの未来だ",
    "tokens": [
      {
        "surface": "新",
        "romaji": "shin",
        "meaning": "new; neo-",
        "pos": "名詞接続",
        "skip": false,
        "lookupWord": "新",
        "baseForm": "新",
        "conjugation": null
      },
      {
        "surface": "時代",
        "romaji": "jidai",
        "meaning": "period; epoch; era; age",
        "pos": "noun",
        "skip": false,
        "lookupWord": "時代",
        "baseForm": "時代",
        "conjugation": null
      },
      {
        "surface": "は",
        "romaji": "ha",
        "meaning": "indicates topic of a sentence",
        "pos": "particle",
        "skip": false
      },
      {
        "surface": "この",
        "romaji": "kono",
        "meaning": "this",
        "pos": "adjectival",
        "skip": false,
        "lookupWord": "この",
        "baseForm": "この",
        "conjugation": null
      },
      {
        "surface": "未来",
        "romaji": "mirai",
        "meaning": "(distant) future",
        "pos": "noun",
        "skip": false,
        "lookupWord": "未来",
        "baseForm": "未来",
        "conjugation": null
      },
      {
        "surface": "だ",
        "romaji": "da",
        "meaning": "be; is",
        "pos": "auxiliary verb",
        "skip": false,
        "lookupWord": "だ",
        "baseForm": "だ",
        "conjugation": null
      }
    ],
    "translation": "The new era is this future"
  },
  {
    "id": "l2",
    "start": 4.42,
    "end": 7.41,
    "text": "世界中全部",
    "tokens": [
      {
        "surface": "世界中",
        "romaji": "sekaijuu",
        "meaning": "around the world; throughout the world",
        "pos": "noun",
        "skip": false,
        "lookupWord": "世界中",
        "baseForm": "世界中",
        "conjugation": null
      },
      {
        "surface": "全部",
        "romaji": "zenbu",
        "meaning": "all; entire; whole; altogether",
        "pos": "noun",
        "skip": false,
        "lookupWord": "全部",
        "baseForm": "全部",
        "conjugation": null
      }
    ],
    "translation": "All over the world"
  },
  {
    "id": "l3",
    "start": 7.41,
    "end": 12.18,
    "text": "変えてしまえば",
    "tokens": [
      {
        "surface": "変えて",
        "romaji": "kaete",
        "meaning": "to change; to alter; to transform; to convert; to turn; to vary",
        "pos": "verb",
        "skip": false,
        "lookupWord": "変える",
        "baseForm": "変える",
        "conjugation": "te-form"
      },
      {
        "surface": "しまえ",
        "romaji": "shimae",
        "meaning": "to finish; to stop; to end; to put an end to; to bring to a close",
        "pos": "verb",
        "skip": false,
        "lookupWord": "しまう",
        "baseForm": "しまう",
        "conjugation": null
      },
      {
        "surface": "ば",
        "romaji": "ba",
        "meaning": "place; spot; space",
        "pos": "particle",
        "skip": false,
        "lookupWord": "ば",
        "baseForm": "ば",
        "conjugation": null
      }
    ],
    "translation": "If you change it"
  },
  {
    "id": "l4",
    "start": 12.18,
    "end": 22.64,
    "text": "変えてしまえば",
    "tokens": [
      {
        "surface": "変えて",
        "romaji": "kaete",
        "meaning": "to change; to alter; to transform; to convert; to turn; to vary",
        "pos": "verb",
        "skip": false,
        "lookupWord": "変える",
        "baseForm": "変える",
        "conjugation": "te-form"
      },
      {
        "surface": "しまえ",
        "romaji": "shimae",
        "meaning": "to finish; to stop; to end; to put an end to; to bring to a close",
        "pos": "verb",
        "skip": false,
        "lookupWord": "しまう",
        "baseForm": "しまう",
        "conjugation": null
      },
      {
        "surface": "ば",
        "romaji": "ba",
        "meaning": "place; spot; space",
        "pos": "particle",
        "skip": false,
        "lookupWord": "ば",
        "baseForm": "ば",
        "conjugation": null
      }
    ],
    "translation": "If you change it"
  },
  {
    "id": "l5",
    "start": 22.64,
    "end": 44.08,
    "text": "♪",
    "tokens": [
      {
        "surface": "♪",
        "romaji": "♪",
        "meaning": "",
        "pos": "noun",
        "skip": true,
        "lookupWord": "",
        "baseForm": "",
        "conjugation": null
      }
    ],
    "translation": ""
  },
  {
    "id": "l6",
    "start": 44.08,
    "end": 44.91,
    "text": "ジャマモノ",
    "tokens": [
      {
        "surface": "ジャマモノ",
        "romaji": "jamamono",
        "meaning": "obstacle; hindrance; impediment; obstruction",
        "pos": "noun",
        "skip": false,
        "lookupWord": "ジャマモノ",
        "baseForm": "ジャマモノ",
        "conjugation": null
      }
    ],
    "translation": "Obstacle"
  },
  {
    "id": "l7",
    "start": 44.91,
    "end": 45.67,
    "text": "やなもの",
    "tokens": [
      {
        "surface": "や",
        "romaji": "ya",
        "meaning": "arrow",
        "pos": "noun",
        "skip": false,
        "lookupWord": "や",
        "baseForm": "や",
        "conjugation": null
      },
      {
        "surface": "な",
        "romaji": "na",
        "meaning": "be; is",
        "pos": "auxiliary verb",
        "skip": false,
        "lookupWord": "だ",
        "baseForm": "だ",
        "conjugation": null
      },
      {
        "surface": "もの",
        "romaji": "mono",
        "meaning": "thing; object; article; stuff; substance",
        "pos": "noun",
        "skip": false,
        "lookupWord": "もの",
        "baseForm": "もの",
        "conjugation": null
      }
    ],
    "translation": "Yamono"
  },
  {
    "id": "l8",
    "start": 45.67,
    "end": 46.97,
    "text": "なんて消して",
    "tokens": [
      {
        "surface": "なんて",
        "romaji": "nante",
        "meaning": "how ...!; what ...!",
        "pos": "particle",
        "skip": false,
        "lookupWord": "なんて",
        "baseForm": "なんて",
        "conjugation": null
      },
      {
        "surface": "消して",
        "romaji": "keshite",
        "meaning": "to erase; to rub out; to rub off; to cross out; to delete",
        "pos": "verb",
        "skip": false,
        "lookupWord": "消す",
        "baseForm": "消す",
        "conjugation": "te-form"
      }
    ],
    "translation": "Please erase it"
  },
  {
    "id": "l9",
    "start": 46.97,
    "end": 49.54,
    "text": "この世とメタモルフォーゼしようぜ",
    "tokens": [
      {
        "surface": "この世",
        "romaji": "konoyo",
        "meaning": "this world; this life; world of the living",
        "pos": "noun",
        "skip": false,
        "lookupWord": "この世",
        "baseForm": "この世",
        "conjugation": null
      },
      {
        "surface": "と",
        "romaji": "to",
        "meaning": "indicates togetherness or quotation (and / with)",
        "pos": "particle",
        "skip": false
      },
      {
        "surface": "メタモルフォーゼ",
        "romaji": "metamorufuooze",
        "meaning": "metamorphosis",
        "pos": "noun",
        "skip": false,
        "lookupWord": "メタモルフォーゼ",
        "baseForm": "メタモルフォーゼ",
        "conjugation": null
      },
      {
        "surface": "しよう",
        "romaji": "shiyou",
        "meaning": "to do; to carry out; to perform",
        "pos": "verb",
        "skip": false,
        "lookupWord": "する",
        "baseForm": "する",
        "conjugation": "auxiliary / conjugated"
      },
      {
        "surface": "ぜ",
        "romaji": "ze",
        "meaning": "I can tell you",
        "pos": "particle",
        "skip": false,
        "lookupWord": "ぜ",
        "baseForm": "ぜ",
        "conjugation": null
      }
    ],
    "translation": "Let's metamorphose with this world"
  },
  {
    "id": "l10",
    "start": 49.54,
    "end": 51.34,
    "text": "ミュージック",
    "tokens": [
      {
        "surface": "ミュージック",
        "romaji": "myuujikku",
        "meaning": "music",
        "pos": "noun",
        "skip": false,
        "lookupWord": "ミュージック",
        "baseForm": "ミュージック",
        "conjugation": null
      }
    ],
    "translation": "Music"
  },
  {
    "id": "l11",
    "start": 51.34,
    "end": 52.43,
    "text": "キミが起こす",
    "tokens": [
      {
        "surface": "キミ",
        "romaji": "kimi",
        "meaning": "you; buddy; pal",
        "pos": "noun",
        "skip": false,
        "lookupWord": "キミ",
        "baseForm": "キミ",
        "conjugation": null
      },
      {
        "surface": "が",
        "romaji": "ga",
        "meaning": "indicates subject of a sentence",
        "pos": "particle",
        "skip": false
      },
      {
        "surface": "起こす",
        "romaji": "okosu",
        "meaning": "to raise; to raise up; to set up; to pick up; to stand (something) up",
        "pos": "verb",
        "skip": false,
        "lookupWord": "起こす",
        "baseForm": "起こす",
        "conjugation": null
      }
    ],
    "translation": "You wake me up"
  },
  {
    "id": "l12",
    "start": 52.43,
    "end": 53.54,
    "text": "マジック",
    "tokens": [
      {
        "surface": "マジック",
        "romaji": "majikku",
        "meaning": "magic",
        "pos": "noun",
        "skip": false,
        "lookupWord": "マジック",
        "baseForm": "マジック",
        "conjugation": null
      }
    ],
    "translation": "Magic"
  },
  {
    "id": "l13",
    "start": 53.54,
    "end": 55.06,
    "text": "♪",
    "tokens": [
      {
        "surface": "♪",
        "romaji": "♪",
        "meaning": "",
        "pos": "noun",
        "skip": true,
        "lookupWord": "",
        "baseForm": "",
        "conjugation": null
      }
    ],
    "translation": ""
  },
  {
    "id": "l14",
    "start": 55.06,
    "end": 57.75,
    "text": "目を閉じれば未来が開いて",
    "tokens": [
      {
        "surface": "目",
        "romaji": "me",
        "meaning": "eye; eyeball",
        "pos": "noun",
        "skip": false,
        "lookupWord": "目",
        "baseForm": "目",
        "conjugation": null
      },
      {
        "surface": "を",
        "romaji": "wo",
        "meaning": "indicates direct object of an action",
        "pos": "particle",
        "skip": false
      },
      {
        "surface": "閉じれ",
        "romaji": "tojire",
        "meaning": "to close (e.g. book, eyes, meeting, etc.); to shut",
        "pos": "verb",
        "skip": false,
        "lookupWord": "閉じる",
        "baseForm": "閉じる",
        "conjugation": null
      },
      {
        "surface": "ば",
        "romaji": "ba",
        "meaning": "place; spot; space",
        "pos": "particle",
        "skip": false,
        "lookupWord": "ば",
        "baseForm": "ば",
        "conjugation": null
      },
      {
        "surface": "未来",
        "romaji": "mirai",
        "meaning": "(distant) future",
        "pos": "noun",
        "skip": false,
        "lookupWord": "未来",
        "baseForm": "未来",
        "conjugation": null
      },
      {
        "surface": "が",
        "romaji": "ga",
        "meaning": "indicates subject of a sentence",
        "pos": "particle",
        "skip": false
      },
      {
        "surface": "開いて",
        "romaji": "hiraite",
        "meaning": "to open; to undo; to unseal; to unpack",
        "pos": "verb",
        "skip": false,
        "lookupWord": "開く",
        "baseForm": "開く",
        "conjugation": "te-form"
      }
    ],
    "translation": "When I close my eyes, the future opens"
  },
  {
    "id": "l15",
    "start": 57.75,
    "end": 62.14,
    "text": "いつまでも終わりが来ないようにって",
    "tokens": [
      {
        "surface": "いつ",
        "romaji": "itsu",
        "meaning": "when; at what time; how soon",
        "pos": "noun",
        "skip": false,
        "lookupWord": "いつ",
        "baseForm": "いつ",
        "conjugation": null
      },
      {
        "surface": "まで",
        "romaji": "made",
        "meaning": "indicates endpoint or limit (until / as far as)",
        "pos": "particle",
        "skip": false
      },
      {
        "surface": "も",
        "romaji": "mo",
        "meaning": "indicates addition or inclusion (also / too / as well)",
        "pos": "particle",
        "skip": false
      },
      {
        "surface": "終わり",
        "romaji": "owari",
        "meaning": "to end; to come to an end; to finish; to close; to be over",
        "pos": "verb",
        "skip": false,
        "lookupWord": "終わる",
        "baseForm": "終わる",
        "conjugation": null
      },
      {
        "surface": "が",
        "romaji": "ga",
        "meaning": "indicates subject of a sentence",
        "pos": "particle",
        "skip": false
      },
      {
        "surface": "来ない",
        "romaji": "konai",
        "meaning": "to come (spatially or temporally); to approach; to arrive",
        "pos": "verb",
        "skip": false,
        "lookupWord": "来る",
        "baseForm": "来る",
        "conjugation": "auxiliary / conjugated"
      },
      {
        "surface": "よう",
        "romaji": "you",
        "meaning": "appearing ...; looking ...",
        "pos": "noun",
        "skip": false,
        "lookupWord": "よう",
        "baseForm": "よう",
        "conjugation": null
      },
      {
        "surface": "に",
        "romaji": "ni",
        "meaning": "indicates direction, destination, time, or target (to / at / in)",
        "pos": "particle",
        "skip": false
      },
      {
        "surface": "って",
        "romaji": "tte",
        "meaning": "you said; he said; she said; they said",
        "pos": "particle",
        "skip": false,
        "lookupWord": "って",
        "baseForm": "って",
        "conjugation": null
      }
    ],
    "translation": "As if the end would never come"
  },
  {
    "id": "l16",
    "start": 62.14,
    "end": 64.66,
    "text": "この歌を歌うよ",
    "tokens": [
      {
        "surface": "この",
        "romaji": "kono",
        "meaning": "this",
        "pos": "adjectival",
        "skip": false,
        "lookupWord": "この",
        "baseForm": "この",
        "conjugation": null
      },
      {
        "surface": "歌",
        "romaji": "uta",
        "meaning": "song; singing",
        "pos": "noun",
        "skip": false,
        "lookupWord": "歌",
        "baseForm": "歌",
        "conjugation": null
      },
      {
        "surface": "を",
        "romaji": "wo",
        "meaning": "indicates direct object of an action",
        "pos": "particle",
        "skip": false
      },
      {
        "surface": "歌う",
        "romaji": "utau",
        "meaning": "to sing",
        "pos": "verb",
        "skip": false,
        "lookupWord": "歌う",
        "baseForm": "歌う",
        "conjugation": null
      },
      {
        "surface": "よ",
        "romaji": "yo",
        "meaning": "indicates new information or emphasis (you know)",
        "pos": "particle",
        "skip": false
      }
    ],
    "translation": "I'll sing this song"
  },
  {
    "id": "l17",
    "start": 64.66,
    "end": 66.3,
    "text": "Ooh",
    "tokens": [
      {
        "surface": "Ooh",
        "romaji": "Ooh",
        "meaning": "",
        "pos": "noun",
        "skip": true,
        "lookupWord": "",
        "baseForm": "",
        "conjugation": null
      }
    ],
    "translation": ""
  },
  {
    "id": "l18",
    "start": 66.3,
    "end": 67.24,
    "text": "Do you wanna play?",
    "tokens": [
      {
        "surface": "Do",
        "romaji": "Do",
        "meaning": "",
        "pos": "noun",
        "skip": true,
        "lookupWord": "",
        "baseForm": "",
        "conjugation": null
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "",
        "pos": "空白",
        "skip": true,
        "lookupWord": "",
        "baseForm": "",
        "conjugation": null
      },
      {
        "surface": "you",
        "romaji": "you",
        "meaning": "",
        "pos": "noun",
        "skip": true,
        "lookupWord": "",
        "baseForm": "",
        "conjugation": null
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "",
        "pos": "空白",
        "skip": true,
        "lookupWord": "",
        "baseForm": "",
        "conjugation": null
      },
      {
        "surface": "wanna",
        "romaji": "wanna",
        "meaning": "",
        "pos": "noun",
        "skip": true,
        "lookupWord": "",
        "baseForm": "",
        "conjugation": null
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "",
        "pos": "空白",
        "skip": true,
        "lookupWord": "",
        "baseForm": "",
        "conjugation": null
      },
      {
        "surface": "play",
        "romaji": "play",
        "meaning": "",
        "pos": "noun",
        "skip": true,
        "lookupWord": "",
        "baseForm": "",
        "conjugation": null
      },
      {
        "surface": "?",
        "romaji": "?",
        "meaning": "",
        "pos": "noun",
        "skip": true,
        "lookupWord": "",
        "baseForm": "",
        "conjugation": null
      }
    ],
    "translation": ""
  },
  {
    "id": "l19",
    "start": 67.24,
    "end": 68.97,
    "text": "リアルゲーム ギリギリ",
    "tokens": [
      {
        "surface": "リアル",
        "romaji": "riaru",
        "meaning": "real; realistic; true to life",
        "pos": "noun",
        "skip": false,
        "lookupWord": "リアル",
        "baseForm": "リアル",
        "conjugation": null
      },
      {
        "surface": "ゲーム",
        "romaji": "geemu",
        "meaning": "game",
        "pos": "noun",
        "skip": false,
        "lookupWord": "ゲーム",
        "baseForm": "ゲーム",
        "conjugation": null
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "",
        "pos": "空白",
        "skip": true,
        "lookupWord": "",
        "baseForm": "",
        "conjugation": null
      },
      {
        "surface": "ギリギリ",
        "romaji": "girigiri",
        "meaning": "just barely; only just; at the very limit; at the last moment",
        "pos": "noun",
        "skip": false,
        "lookupWord": "ギリギリ",
        "baseForm": "ギリギリ",
        "conjugation": null
      }
    ],
    "translation": "Real game last minute"
  },
  {
    "id": "l20",
    "start": 68.97,
    "end": 71.97,
    "text": "綱渡りみたいな旋律",
    "tokens": [
      {
        "surface": "綱渡り",
        "romaji": "tsunawatari",
        "meaning": "tightrope walking; high-wire act; funambulism",
        "pos": "noun",
        "skip": false,
        "lookupWord": "綱渡り",
        "baseForm": "綱渡り",
        "conjugation": null
      },
      {
        "surface": "みたい",
        "romaji": "mitai",
        "meaning": "-like; sort of; similar to; resembling",
        "pos": "noun",
        "skip": false,
        "lookupWord": "みたい",
        "baseForm": "みたい",
        "conjugation": null
      },
      {
        "surface": "な",
        "romaji": "na",
        "meaning": "be; is",
        "pos": "auxiliary verb",
        "skip": false,
        "lookupWord": "だ",
        "baseForm": "だ",
        "conjugation": null
      },
      {
        "surface": "旋律",
        "romaji": "senritsu",
        "meaning": "melody; tune",
        "pos": "noun",
        "skip": false,
        "lookupWord": "旋律",
        "baseForm": "旋律",
        "conjugation": null
      }
    ],
    "translation": "A melody like a tightrope walk"
  },
  {
    "id": "l21",
    "start": 71.97,
    "end": 74.48,
    "text": "認めない戻れない忘れたい",
    "tokens": [
      {
        "surface": "認めない",
        "romaji": "mitomenai",
        "meaning": "to recognize; to recognise; to observe; to notice",
        "pos": "verb",
        "skip": false,
        "lookupWord": "認める",
        "baseForm": "認める",
        "conjugation": "auxiliary / conjugated"
      },
      {
        "surface": "戻れない",
        "romaji": "modorenai",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "verb",
        "skip": false,
        "lookupWord": "戻れる",
        "baseForm": "戻れる",
        "conjugation": "auxiliary / conjugated"
      },
      {
        "surface": "忘れたい",
        "romaji": "wasuretai",
        "meaning": "to forget; to leave carelessly; to be forgetful of; to forget about; to forget (an article)",
        "pos": "verb",
        "skip": false,
        "lookupWord": "忘れる",
        "baseForm": "忘れる",
        "conjugation": "auxiliary / conjugated"
      }
    ],
    "translation": "I don't accept it, I can't go back, I want to forget it"
  },
  {
    "id": "l22",
    "start": 74.48,
    "end": 76.65,
    "text": "夢の中に居させて",
    "tokens": [
      {
        "surface": "夢",
        "romaji": "yume",
        "meaning": "dream",
        "pos": "noun",
        "skip": false,
        "lookupWord": "夢",
        "baseForm": "夢",
        "conjugation": null
      },
      {
        "surface": "の",
        "romaji": "no",
        "meaning": "indicates possession or noun modification (of / 's)",
        "pos": "particle",
        "skip": false
      },
      {
        "surface": "中",
        "romaji": "naka",
        "meaning": "medium (size); average (grade, level, etc.); middle",
        "pos": "noun",
        "skip": false,
        "lookupWord": "中",
        "baseForm": "中",
        "conjugation": null
      },
      {
        "surface": "に",
        "romaji": "ni",
        "meaning": "indicates direction, destination, time, or target (to / at / in)",
        "pos": "particle",
        "skip": false
      },
      {
        "surface": "居",
        "romaji": "i",
        "meaning": "to be (of animate objects); to exist",
        "pos": "verb",
        "skip": false,
        "lookupWord": "居る",
        "baseForm": "居る",
        "conjugation": null
      },
      {
        "surface": "させて",
        "romaji": "sasete",
        "meaning": "(any) particular; notable; noteworthy; significant; considerable",
        "pos": "verb",
        "skip": false,
        "lookupWord": "させる",
        "baseForm": "させる",
        "conjugation": "te-form"
      }
    ],
    "translation": "Let me stay in my dreams"
  },
  {
    "id": "l23",
    "start": 76.65,
    "end": 78.87,
    "text": "I wanna be free",
    "tokens": [
      {
        "surface": "I",
        "romaji": "I",
        "meaning": "",
        "pos": "noun",
        "skip": true,
        "lookupWord": "",
        "baseForm": "",
        "conjugation": null
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "",
        "pos": "空白",
        "skip": true,
        "lookupWord": "",
        "baseForm": "",
        "conjugation": null
      },
      {
        "surface": "wanna",
        "romaji": "wanna",
        "meaning": "",
        "pos": "noun",
        "skip": true,
        "lookupWord": "",
        "baseForm": "",
        "conjugation": null
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "",
        "pos": "空白",
        "skip": true,
        "lookupWord": "",
        "baseForm": "",
        "conjugation": null
      },
      {
        "surface": "be",
        "romaji": "be",
        "meaning": "",
        "pos": "noun",
        "skip": true,
        "lookupWord": "",
        "baseForm": "",
        "conjugation": null
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "",
        "pos": "空白",
        "skip": true,
        "lookupWord": "",
        "baseForm": "",
        "conjugation": null
      },
      {
        "surface": "free",
        "romaji": "free",
        "meaning": "",
        "pos": "noun",
        "skip": true,
        "lookupWord": "",
        "baseForm": "",
        "conjugation": null
      }
    ],
    "translation": ""
  },
  {
    "id": "l24",
    "start": 78.87,
    "end": 81.75,
    "text": "見えるよ新時代が",
    "tokens": [
      {
        "surface": "見える",
        "romaji": "mieru",
        "meaning": "to be seen; to be visible; to be in sight",
        "pos": "verb",
        "skip": false,
        "lookupWord": "見える",
        "baseForm": "見える",
        "conjugation": null
      },
      {
        "surface": "よ",
        "romaji": "yo",
        "meaning": "indicates new information or emphasis (you know)",
        "pos": "particle",
        "skip": false
      },
      {
        "surface": "新",
        "romaji": "shin",
        "meaning": "new; neo-",
        "pos": "名詞接続",
        "skip": false,
        "lookupWord": "新",
        "baseForm": "新",
        "conjugation": null
      },
      {
        "surface": "時代",
        "romaji": "jidai",
        "meaning": "period; epoch; era; age",
        "pos": "noun",
        "skip": false,
        "lookupWord": "時代",
        "baseForm": "時代",
        "conjugation": null
      },
      {
        "surface": "が",
        "romaji": "ga",
        "meaning": "indicates subject of a sentence",
        "pos": "particle",
        "skip": false
      }
    ],
    "translation": "I can see a new era"
  },
  {
    "id": "l25",
    "start": 81.75,
    "end": 84.5,
    "text": "世界の向こうへ",
    "tokens": [
      {
        "surface": "世界",
        "romaji": "sekai",
        "meaning": "the world; society; the universe",
        "pos": "noun",
        "skip": false,
        "lookupWord": "世界",
        "baseForm": "世界",
        "conjugation": null
      },
      {
        "surface": "の",
        "romaji": "no",
        "meaning": "indicates possession or noun modification (of / 's)",
        "pos": "particle",
        "skip": false
      },
      {
        "surface": "向こう",
        "romaji": "mukou",
        "meaning": "opposite side; other side",
        "pos": "noun",
        "skip": false,
        "lookupWord": "向こう",
        "baseForm": "向こう",
        "conjugation": null
      },
      {
        "surface": "へ",
        "romaji": "he",
        "meaning": "indicates direction or goal (towards / to)",
        "pos": "particle",
        "skip": false
      }
    ],
    "translation": "To the other side of the world"
  },
  {
    "id": "l26",
    "start": 84.5,
    "end": 85.3,
    "text": "さあ行くよ",
    "tokens": [
      {
        "surface": "さあ",
        "romaji": "saa",
        "meaning": "come (on); come now; come along; here",
        "pos": "interjection",
        "skip": false,
        "lookupWord": "さあ",
        "baseForm": "さあ",
        "conjugation": null
      },
      {
        "surface": "行く",
        "romaji": "iku",
        "meaning": "to go; to move (towards); to head (towards); to leave (for)",
        "pos": "verb",
        "skip": false,
        "lookupWord": "行く",
        "baseForm": "行く",
        "conjugation": null
      },
      {
        "surface": "よ",
        "romaji": "yo",
        "meaning": "indicates new information or emphasis (you know)",
        "pos": "particle",
        "skip": false
      }
    ],
    "translation": "Let's go"
  },
  {
    "id": "l27",
    "start": 85.3,
    "end": 87.24,
    "text": "New world",
    "tokens": [
      {
        "surface": "new",
        "romaji": "new",
        "meaning": "",
        "pos": "noun",
        "skip": true,
        "lookupWord": "",
        "baseForm": "",
        "conjugation": null
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "",
        "pos": "空白",
        "skip": true,
        "lookupWord": "",
        "baseForm": "",
        "conjugation": null
      },
      {
        "surface": "world",
        "romaji": "world",
        "meaning": "",
        "pos": "noun",
        "skip": true,
        "lookupWord": "",
        "baseForm": "",
        "conjugation": null
      }
    ],
    "translation": ""
  },
  {
    "id": "l28",
    "start": 87.24,
    "end": 88.18,
    "text": "♪",
    "tokens": [
      {
        "surface": "♪",
        "romaji": "♪",
        "meaning": "",
        "pos": "noun",
        "skip": true,
        "lookupWord": "",
        "baseForm": "",
        "conjugation": null
      }
    ],
    "translation": ""
  },
  {
    "id": "l29",
    "start": 88.18,
    "end": 90.51,
    "text": "新時代はこの未来だ",
    "tokens": [
      {
        "surface": "新",
        "romaji": "shin",
        "meaning": "new; neo-",
        "pos": "名詞接続",
        "skip": false,
        "lookupWord": "新",
        "baseForm": "新",
        "conjugation": null
      },
      {
        "surface": "時代",
        "romaji": "jidai",
        "meaning": "period; epoch; era; age",
        "pos": "noun",
        "skip": false,
        "lookupWord": "時代",
        "baseForm": "時代",
        "conjugation": null
      },
      {
        "surface": "は",
        "romaji": "ha",
        "meaning": "indicates topic of a sentence",
        "pos": "particle",
        "skip": false
      },
      {
        "surface": "この",
        "romaji": "kono",
        "meaning": "this",
        "pos": "adjectival",
        "skip": false,
        "lookupWord": "この",
        "baseForm": "この",
        "conjugation": null
      },
      {
        "surface": "未来",
        "romaji": "mirai",
        "meaning": "(distant) future",
        "pos": "noun",
        "skip": false,
        "lookupWord": "未来",
        "baseForm": "未来",
        "conjugation": null
      },
      {
        "surface": "だ",
        "romaji": "da",
        "meaning": "be; is",
        "pos": "auxiliary verb",
        "skip": false,
        "lookupWord": "だ",
        "baseForm": "だ",
        "conjugation": null
      }
    ],
    "translation": "The new era is this future"
  },
  {
    "id": "l30",
    "start": 90.51,
    "end": 92.65,
    "text": "世界中全部",
    "tokens": [
      {
        "surface": "世界中",
        "romaji": "sekaijuu",
        "meaning": "around the world; throughout the world",
        "pos": "noun",
        "skip": false,
        "lookupWord": "世界中",
        "baseForm": "世界中",
        "conjugation": null
      },
      {
        "surface": "全部",
        "romaji": "zenbu",
        "meaning": "all; entire; whole; altogether",
        "pos": "noun",
        "skip": false,
        "lookupWord": "全部",
        "baseForm": "全部",
        "conjugation": null
      }
    ],
    "translation": "All over the world"
  },
  {
    "id": "l31",
    "start": 92.65,
    "end": 95.49,
    "text": "変えてしまえば",
    "tokens": [
      {
        "surface": "変えて",
        "romaji": "kaete",
        "meaning": "to change; to alter; to transform; to convert; to turn; to vary",
        "pos": "verb",
        "skip": false,
        "lookupWord": "変える",
        "baseForm": "変える",
        "conjugation": "te-form"
      },
      {
        "surface": "しまえ",
        "romaji": "shimae",
        "meaning": "to finish; to stop; to end; to put an end to; to bring to a close",
        "pos": "verb",
        "skip": false,
        "lookupWord": "しまう",
        "baseForm": "しまう",
        "conjugation": null
      },
      {
        "surface": "ば",
        "romaji": "ba",
        "meaning": "place; spot; space",
        "pos": "particle",
        "skip": false,
        "lookupWord": "ば",
        "baseForm": "ば",
        "conjugation": null
      }
    ],
    "translation": "If you change it"
  },
  {
    "id": "l32",
    "start": 95.49,
    "end": 99.15,
    "text": "変えてしまえば",
    "tokens": [
      {
        "surface": "変えて",
        "romaji": "kaete",
        "meaning": "to change; to alter; to transform; to convert; to turn; to vary",
        "pos": "verb",
        "skip": false,
        "lookupWord": "変える",
        "baseForm": "変える",
        "conjugation": "te-form"
      },
      {
        "surface": "しまえ",
        "romaji": "shimae",
        "meaning": "to finish; to stop; to end; to put an end to; to bring to a close",
        "pos": "verb",
        "skip": false,
        "lookupWord": "しまう",
        "baseForm": "しまう",
        "conjugation": null
      },
      {
        "surface": "ば",
        "romaji": "ba",
        "meaning": "place; spot; space",
        "pos": "particle",
        "skip": false,
        "lookupWord": "ば",
        "baseForm": "ば",
        "conjugation": null
      }
    ],
    "translation": "If you change it"
  },
  {
    "id": "l33",
    "start": 99.15,
    "end": 103.62,
    "text": "果てしない音楽がもっと届くように",
    "tokens": [
      {
        "surface": "果てしない",
        "romaji": "hateshinai",
        "meaning": "endless; boundless; everlasting",
        "pos": "adjective",
        "skip": false,
        "lookupWord": "果てしない",
        "baseForm": "果てしない",
        "conjugation": null
      },
      {
        "surface": "音楽",
        "romaji": "ongaku",
        "meaning": "music",
        "pos": "noun",
        "skip": false,
        "lookupWord": "音楽",
        "baseForm": "音楽",
        "conjugation": null
      },
      {
        "surface": "が",
        "romaji": "ga",
        "meaning": "indicates subject of a sentence",
        "pos": "particle",
        "skip": false
      },
      {
        "surface": "もっと",
        "romaji": "motto",
        "meaning": "(some) more; even more; longer; further",
        "pos": "adverb",
        "skip": false,
        "lookupWord": "もっと",
        "baseForm": "もっと",
        "conjugation": null
      },
      {
        "surface": "届く",
        "romaji": "todoku",
        "meaning": "to reach; to touch; to get to; to carry (of sound)",
        "pos": "verb",
        "skip": false,
        "lookupWord": "届く",
        "baseForm": "届く",
        "conjugation": null
      },
      {
        "surface": "よう",
        "romaji": "you",
        "meaning": "appearing ...; looking ...",
        "pos": "noun",
        "skip": false,
        "lookupWord": "よう",
        "baseForm": "よう",
        "conjugation": null
      },
      {
        "surface": "に",
        "romaji": "ni",
        "meaning": "indicates direction, destination, time, or target (to / at / in)",
        "pos": "particle",
        "skip": false
      }
    ],
    "translation": "May more endless music reach you"
  },
  {
    "id": "l34",
    "start": 103.62,
    "end": 106.29,
    "text": "夢は見ないわ",
    "tokens": [
      {
        "surface": "夢",
        "romaji": "yume",
        "meaning": "dream",
        "pos": "noun",
        "skip": false,
        "lookupWord": "夢",
        "baseForm": "夢",
        "conjugation": null
      },
      {
        "surface": "は",
        "romaji": "ha",
        "meaning": "indicates topic of a sentence",
        "pos": "particle",
        "skip": false
      },
      {
        "surface": "見ない",
        "romaji": "minai",
        "meaning": "to see; to look; to watch; to view; to observe",
        "pos": "verb",
        "skip": false,
        "lookupWord": "見る",
        "baseForm": "見る",
        "conjugation": "auxiliary / conjugated"
      },
      {
        "surface": "わ",
        "romaji": "wa",
        "meaning": "ring; circle; loop",
        "pos": "particle",
        "skip": false,
        "lookupWord": "わ",
        "baseForm": "わ",
        "conjugation": null
      }
    ],
    "translation": "I don't dream"
  },
  {
    "id": "l35",
    "start": 106.29,
    "end": 110.44,
    "text": "キミが話した 「ボクを信じて」",
    "tokens": [
      {
        "surface": "キミ",
        "romaji": "kimi",
        "meaning": "you; buddy; pal",
        "pos": "noun",
        "skip": false,
        "lookupWord": "キミ",
        "baseForm": "キミ",
        "conjugation": null
      },
      {
        "surface": "が",
        "romaji": "ga",
        "meaning": "indicates subject of a sentence",
        "pos": "particle",
        "skip": false
      },
      {
        "surface": "話した",
        "romaji": "hanashita",
        "meaning": "to talk; to speak; to converse; to chat",
        "pos": "verb",
        "skip": false,
        "lookupWord": "話す",
        "baseForm": "話す",
        "conjugation": "auxiliary / conjugated"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "",
        "pos": "空白",
        "skip": true,
        "lookupWord": "",
        "baseForm": "",
        "conjugation": null
      },
      {
        "surface": "「",
        "romaji": "‘",
        "meaning": "",
        "pos": "括弧開",
        "skip": true,
        "lookupWord": "",
        "baseForm": "",
        "conjugation": null
      },
      {
        "surface": "ボク",
        "romaji": "boku",
        "meaning": "I; me",
        "pos": "noun",
        "skip": false,
        "lookupWord": "ボク",
        "baseForm": "ボク",
        "conjugation": null
      },
      {
        "surface": "を",
        "romaji": "wo",
        "meaning": "indicates direct object of an action",
        "pos": "particle",
        "skip": false
      },
      {
        "surface": "信じて",
        "romaji": "shinjite",
        "meaning": "to believe; to believe in; to place trust in; to confide in; to have faith in",
        "pos": "verb",
        "skip": false,
        "lookupWord": "信じる",
        "baseForm": "信じる",
        "conjugation": "te-form"
      },
      {
        "surface": "」",
        "romaji": "’",
        "meaning": "",
        "pos": "括弧閉",
        "skip": true,
        "lookupWord": "",
        "baseForm": "",
        "conjugation": null
      }
    ],
    "translation": "You spoke, \"Believe in me\""
  },
  {
    "id": "l36",
    "start": 110.44,
    "end": 118.59,
    "text": "♪",
    "tokens": [
      {
        "surface": "♪",
        "romaji": "♪",
        "meaning": "",
        "pos": "noun",
        "skip": true,
        "lookupWord": "",
        "baseForm": "",
        "conjugation": null
      }
    ],
    "translation": ""
  },
  {
    "id": "l37",
    "start": 118.59,
    "end": 123.85,
    "text": "Ooh",
    "tokens": [
      {
        "surface": "Ooh",
        "romaji": "Ooh",
        "meaning": "",
        "pos": "noun",
        "skip": true,
        "lookupWord": "",
        "baseForm": "",
        "conjugation": null
      }
    ],
    "translation": ""
  },
  {
    "id": "l38",
    "start": 123.85,
    "end": 132.01,
    "text": "♪",
    "tokens": [
      {
        "surface": "♪",
        "romaji": "♪",
        "meaning": "",
        "pos": "noun",
        "skip": true,
        "lookupWord": "",
        "baseForm": "",
        "conjugation": null
      }
    ],
    "translation": ""
  },
  {
    "id": "l39",
    "start": 132.01,
    "end": 134.56,
    "text": "あれこれいらないものは消して",
    "tokens": [
      {
        "surface": "あれこれ",
        "romaji": "arekore",
        "meaning": "this and that; this or that; one thing or another; this way and that",
        "pos": "noun",
        "skip": false,
        "lookupWord": "あれこれ",
        "baseForm": "あれこれ",
        "conjugation": null
      },
      {
        "surface": "いらない",
        "romaji": "iranai",
        "meaning": "to be (of animate objects); to exist",
        "pos": "verb",
        "skip": false,
        "lookupWord": "いる",
        "baseForm": "いる",
        "conjugation": "auxiliary / conjugated"
      },
      {
        "surface": "もの",
        "romaji": "mono",
        "meaning": "thing; object; article; stuff; substance",
        "pos": "noun",
        "skip": false,
        "lookupWord": "もの",
        "baseForm": "もの",
        "conjugation": null
      },
      {
        "surface": "は",
        "romaji": "ha",
        "meaning": "indicates topic of a sentence",
        "pos": "particle",
        "skip": false
      },
      {
        "surface": "消して",
        "romaji": "keshite",
        "meaning": "to erase; to rub out; to rub off; to cross out; to delete",
        "pos": "verb",
        "skip": false,
        "lookupWord": "消す",
        "baseForm": "消す",
        "conjugation": "te-form"
      }
    ],
    "translation": "Erase everything you don't need"
  },
  {
    "id": "l40",
    "start": 134.56,
    "end": 137.26,
    "text": "リアルをカラフルに越えようぜ",
    "tokens": [
      {
        "surface": "リアル",
        "romaji": "riaru",
        "meaning": "real; realistic; true to life",
        "pos": "noun",
        "skip": false,
        "lookupWord": "リアル",
        "baseForm": "リアル",
        "conjugation": null
      },
      {
        "surface": "を",
        "romaji": "wo",
        "meaning": "indicates direct object of an action",
        "pos": "particle",
        "skip": false
      },
      {
        "surface": "カラフル",
        "romaji": "karafuru",
        "meaning": "colorful; colourful",
        "pos": "noun",
        "skip": false,
        "lookupWord": "カラフル",
        "baseForm": "カラフル",
        "conjugation": null
      },
      {
        "surface": "に",
        "romaji": "ni",
        "meaning": "indicates direction, destination, time, or target (to / at / in)",
        "pos": "particle",
        "skip": false
      },
      {
        "surface": "越えよう",
        "romaji": "koeyou",
        "meaning": "to cross over; to cross; to pass through; to pass over (out of); to go beyond; to go past",
        "pos": "verb",
        "skip": false,
        "lookupWord": "越える",
        "baseForm": "越える",
        "conjugation": "auxiliary / conjugated"
      },
      {
        "surface": "ぜ",
        "romaji": "ze",
        "meaning": "I can tell you",
        "pos": "particle",
        "skip": false,
        "lookupWord": "ぜ",
        "baseForm": "ぜ",
        "conjugation": null
      }
    ],
    "translation": "Let's go beyond reality colorfully"
  },
  {
    "id": "l41",
    "start": 137.26,
    "end": 139.11,
    "text": "ミュージック",
    "tokens": [
      {
        "surface": "ミュージック",
        "romaji": "myuujikku",
        "meaning": "music",
        "pos": "noun",
        "skip": false,
        "lookupWord": "ミュージック",
        "baseForm": "ミュージック",
        "conjugation": null
      }
    ],
    "translation": "Music"
  },
  {
    "id": "l42",
    "start": 139.11,
    "end": 140.16,
    "text": "今始まる",
    "tokens": [
      {
        "surface": "今",
        "romaji": "ima",
        "meaning": "now; the present time; just now; soon; immediately",
        "pos": "noun",
        "skip": false,
        "lookupWord": "今",
        "baseForm": "今",
        "conjugation": null
      },
      {
        "surface": "始まる",
        "romaji": "hajimaru",
        "meaning": "to begin; to start; to commence",
        "pos": "verb",
        "skip": false,
        "lookupWord": "始まる",
        "baseForm": "始まる",
        "conjugation": null
      }
    ],
    "translation": "Starts now"
  },
  {
    "id": "l43",
    "start": 140.16,
    "end": 142.65,
    "text": "ライジング",
    "tokens": [
      {
        "surface": "ライジング",
        "romaji": "raijingu",
        "meaning": "rising",
        "pos": "noun",
        "skip": false,
        "lookupWord": "ライジング",
        "baseForm": "ライジング",
        "conjugation": null
      }
    ],
    "translation": "Rising"
  },
  {
    "id": "l44",
    "start": 142.65,
    "end": 145.61,
    "text": "目をつぶりみんなで逃げようよ",
    "tokens": [
      {
        "surface": "目",
        "romaji": "me",
        "meaning": "eye; eyeball",
        "pos": "noun",
        "skip": false,
        "lookupWord": "目",
        "baseForm": "目",
        "conjugation": null
      },
      {
        "surface": "を",
        "romaji": "wo",
        "meaning": "indicates direct object of an action",
        "pos": "particle",
        "skip": false
      },
      {
        "surface": "つぶり",
        "romaji": "tsuburi",
        "meaning": "to close (one's eyes); to shut",
        "pos": "verb",
        "skip": false,
        "lookupWord": "つぶる",
        "baseForm": "つぶる",
        "conjugation": null
      },
      {
        "surface": "みんな",
        "romaji": "minna",
        "meaning": "everyone; everybody; all",
        "pos": "noun",
        "skip": false,
        "lookupWord": "みんな",
        "baseForm": "みんな",
        "conjugation": null
      },
      {
        "surface": "で",
        "romaji": "de",
        "meaning": "indicates location of action, means, or method (at / by / with)",
        "pos": "particle",
        "skip": false
      },
      {
        "surface": "逃げよう",
        "romaji": "nigeyou",
        "meaning": "to run away; to flee; to get away (e.g. from danger); to escape; to break out; to leave (e.g. one's spouse); to take cover",
        "pos": "verb",
        "skip": false,
        "lookupWord": "逃げる",
        "baseForm": "逃げる",
        "conjugation": "auxiliary / conjugated"
      },
      {
        "surface": "よ",
        "romaji": "yo",
        "meaning": "indicates new information or emphasis (you know)",
        "pos": "particle",
        "skip": false
      }
    ],
    "translation": "Let's all close our eyes and run away"
  },
  {
    "id": "l45",
    "start": 145.61,
    "end": 150.08,
    "text": "今よりイイモノを見せてあげるよ",
    "tokens": [
      {
        "surface": "今",
        "romaji": "ima",
        "meaning": "now; the present time; just now; soon; immediately",
        "pos": "noun",
        "skip": false,
        "lookupWord": "今",
        "baseForm": "今",
        "conjugation": null
      },
      {
        "surface": "より",
        "romaji": "yori",
        "meaning": "than",
        "pos": "particle",
        "skip": false,
        "lookupWord": "より",
        "baseForm": "より",
        "conjugation": null
      },
      {
        "surface": "イイ",
        "romaji": "ii",
        "meaning": "Iran-Iraq",
        "pos": "adjective",
        "skip": false,
        "lookupWord": "イイ",
        "baseForm": "イイ",
        "conjugation": null
      },
      {
        "surface": "モノ",
        "romaji": "mono",
        "meaning": "mono",
        "pos": "noun",
        "skip": false,
        "lookupWord": "モノ",
        "baseForm": "モノ",
        "conjugation": null
      },
      {
        "surface": "を",
        "romaji": "wo",
        "meaning": "indicates direct object of an action",
        "pos": "particle",
        "skip": false
      },
      {
        "surface": "見せて",
        "romaji": "misete",
        "meaning": "to show; to display",
        "pos": "verb",
        "skip": false,
        "lookupWord": "見せる",
        "baseForm": "見せる",
        "conjugation": "te-form"
      },
      {
        "surface": "あげる",
        "romaji": "ageru",
        "meaning": "to raise; to elevate",
        "pos": "verb",
        "skip": false,
        "lookupWord": "あげる",
        "baseForm": "あげる",
        "conjugation": null
      },
      {
        "surface": "よ",
        "romaji": "yo",
        "meaning": "indicates new information or emphasis (you know)",
        "pos": "particle",
        "skip": false
      }
    ],
    "translation": "I'll show you something better than now"
  },
  {
    "id": "l46",
    "start": 150.08,
    "end": 152.57,
    "text": "この歌を歌えば",
    "tokens": [
      {
        "surface": "この",
        "romaji": "kono",
        "meaning": "this",
        "pos": "adjectival",
        "skip": false,
        "lookupWord": "この",
        "baseForm": "この",
        "conjugation": null
      },
      {
        "surface": "歌",
        "romaji": "uta",
        "meaning": "song; singing",
        "pos": "noun",
        "skip": false,
        "lookupWord": "歌",
        "baseForm": "歌",
        "conjugation": null
      },
      {
        "surface": "を",
        "romaji": "wo",
        "meaning": "indicates direct object of an action",
        "pos": "particle",
        "skip": false
      },
      {
        "surface": "歌え",
        "romaji": "utae",
        "meaning": "to sing",
        "pos": "verb",
        "skip": false,
        "lookupWord": "歌う",
        "baseForm": "歌う",
        "conjugation": null
      },
      {
        "surface": "ば",
        "romaji": "ba",
        "meaning": "place; spot; space",
        "pos": "particle",
        "skip": false,
        "lookupWord": "ば",
        "baseForm": "ば",
        "conjugation": null
      }
    ],
    "translation": "If you sing this song"
  },
  {
    "id": "l47",
    "start": 152.57,
    "end": 154.03,
    "text": "Aah",
    "tokens": [
      {
        "surface": "Aah",
        "romaji": "Aah",
        "meaning": "",
        "pos": "noun",
        "skip": true,
        "lookupWord": "",
        "baseForm": "",
        "conjugation": null
      }
    ],
    "translation": ""
  },
  {
    "id": "l48",
    "start": 154.03,
    "end": 155.07,
    "text": "Do you wanna play?",
    "tokens": [
      {
        "surface": "Do",
        "romaji": "Do",
        "meaning": "",
        "pos": "noun",
        "skip": true,
        "lookupWord": "",
        "baseForm": "",
        "conjugation": null
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "",
        "pos": "空白",
        "skip": true,
        "lookupWord": "",
        "baseForm": "",
        "conjugation": null
      },
      {
        "surface": "you",
        "romaji": "you",
        "meaning": "",
        "pos": "noun",
        "skip": true,
        "lookupWord": "",
        "baseForm": "",
        "conjugation": null
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "",
        "pos": "空白",
        "skip": true,
        "lookupWord": "",
        "baseForm": "",
        "conjugation": null
      },
      {
        "surface": "wanna",
        "romaji": "wanna",
        "meaning": "",
        "pos": "noun",
        "skip": true,
        "lookupWord": "",
        "baseForm": "",
        "conjugation": null
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "",
        "pos": "空白",
        "skip": true,
        "lookupWord": "",
        "baseForm": "",
        "conjugation": null
      },
      {
        "surface": "play",
        "romaji": "play",
        "meaning": "",
        "pos": "noun",
        "skip": true,
        "lookupWord": "",
        "baseForm": "",
        "conjugation": null
      },
      {
        "surface": "?",
        "romaji": "?",
        "meaning": "",
        "pos": "noun",
        "skip": true,
        "lookupWord": "",
        "baseForm": "",
        "conjugation": null
      }
    ],
    "translation": ""
  },
  {
    "id": "l49",
    "start": 155.07,
    "end": 156.49,
    "text": "リアルゲーム ギリギリ",
    "tokens": [
      {
        "surface": "リアル",
        "romaji": "riaru",
        "meaning": "real; realistic; true to life",
        "pos": "noun",
        "skip": false,
        "lookupWord": "リアル",
        "baseForm": "リアル",
        "conjugation": null
      },
      {
        "surface": "ゲーム",
        "romaji": "geemu",
        "meaning": "game",
        "pos": "noun",
        "skip": false,
        "lookupWord": "ゲーム",
        "baseForm": "ゲーム",
        "conjugation": null
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "",
        "pos": "空白",
        "skip": true,
        "lookupWord": "",
        "baseForm": "",
        "conjugation": null
      },
      {
        "surface": "ギリギリ",
        "romaji": "girigiri",
        "meaning": "just barely; only just; at the very limit; at the last moment",
        "pos": "noun",
        "skip": false,
        "lookupWord": "ギリギリ",
        "baseForm": "ギリギリ",
        "conjugation": null
      }
    ],
    "translation": "Real game last minute"
  },
  {
    "id": "l50",
    "start": 156.49,
    "end": 159.47,
    "text": "綱渡りみたいな運命",
    "tokens": [
      {
        "surface": "綱渡り",
        "romaji": "tsunawatari",
        "meaning": "tightrope walking; high-wire act; funambulism",
        "pos": "noun",
        "skip": false,
        "lookupWord": "綱渡り",
        "baseForm": "綱渡り",
        "conjugation": null
      },
      {
        "surface": "みたい",
        "romaji": "mitai",
        "meaning": "-like; sort of; similar to; resembling",
        "pos": "noun",
        "skip": false,
        "lookupWord": "みたい",
        "baseForm": "みたい",
        "conjugation": null
      },
      {
        "surface": "な",
        "romaji": "na",
        "meaning": "be; is",
        "pos": "auxiliary verb",
        "skip": false,
        "lookupWord": "だ",
        "baseForm": "だ",
        "conjugation": null
      },
      {
        "surface": "運命",
        "romaji": "unmei",
        "meaning": "fate; destiny; lot",
        "pos": "noun",
        "skip": false,
        "lookupWord": "運命",
        "baseForm": "運命",
        "conjugation": null
      }
    ],
    "translation": "Fate is like walking a tightrope"
  },
  {
    "id": "l51",
    "start": 159.47,
    "end": 162.33,
    "text": "認めない戻れない忘れたい",
    "tokens": [
      {
        "surface": "認めない",
        "romaji": "mitomenai",
        "meaning": "to recognize; to recognise; to observe; to notice",
        "pos": "verb",
        "skip": false,
        "lookupWord": "認める",
        "baseForm": "認める",
        "conjugation": "auxiliary / conjugated"
      },
      {
        "surface": "戻れない",
        "romaji": "modorenai",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "verb",
        "skip": false,
        "lookupWord": "戻れる",
        "baseForm": "戻れる",
        "conjugation": "auxiliary / conjugated"
      },
      {
        "surface": "忘れたい",
        "romaji": "wasuretai",
        "meaning": "to forget; to leave carelessly; to be forgetful of; to forget about; to forget (an article)",
        "pos": "verb",
        "skip": false,
        "lookupWord": "忘れる",
        "baseForm": "忘れる",
        "conjugation": "auxiliary / conjugated"
      }
    ],
    "translation": "I don't accept it, I can't go back, I want to forget it"
  },
  {
    "id": "l52",
    "start": 162.33,
    "end": 164.48,
    "text": "夢の中に居させて",
    "tokens": [
      {
        "surface": "夢",
        "romaji": "yume",
        "meaning": "dream",
        "pos": "noun",
        "skip": false,
        "lookupWord": "夢",
        "baseForm": "夢",
        "conjugation": null
      },
      {
        "surface": "の",
        "romaji": "no",
        "meaning": "indicates possession or noun modification (of / 's)",
        "pos": "particle",
        "skip": false
      },
      {
        "surface": "中",
        "romaji": "naka",
        "meaning": "medium (size); average (grade, level, etc.); middle",
        "pos": "noun",
        "skip": false,
        "lookupWord": "中",
        "baseForm": "中",
        "conjugation": null
      },
      {
        "surface": "に",
        "romaji": "ni",
        "meaning": "indicates direction, destination, time, or target (to / at / in)",
        "pos": "particle",
        "skip": false
      },
      {
        "surface": "居",
        "romaji": "i",
        "meaning": "to be (of animate objects); to exist",
        "pos": "verb",
        "skip": false,
        "lookupWord": "居る",
        "baseForm": "居る",
        "conjugation": null
      },
      {
        "surface": "させて",
        "romaji": "sasete",
        "meaning": "(any) particular; notable; noteworthy; significant; considerable",
        "pos": "verb",
        "skip": false,
        "lookupWord": "させる",
        "baseForm": "させる",
        "conjugation": "te-form"
      }
    ],
    "translation": "Let me stay in my dreams"
  },
  {
    "id": "l53",
    "start": 164.48,
    "end": 166.42,
    "text": "I wanna be free",
    "tokens": [
      {
        "surface": "I",
        "romaji": "I",
        "meaning": "",
        "pos": "noun",
        "skip": true,
        "lookupWord": "",
        "baseForm": "",
        "conjugation": null
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "",
        "pos": "空白",
        "skip": true,
        "lookupWord": "",
        "baseForm": "",
        "conjugation": null
      },
      {
        "surface": "wanna",
        "romaji": "wanna",
        "meaning": "",
        "pos": "noun",
        "skip": true,
        "lookupWord": "",
        "baseForm": "",
        "conjugation": null
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "",
        "pos": "空白",
        "skip": true,
        "lookupWord": "",
        "baseForm": "",
        "conjugation": null
      },
      {
        "surface": "be",
        "romaji": "be",
        "meaning": "",
        "pos": "noun",
        "skip": true,
        "lookupWord": "",
        "baseForm": "",
        "conjugation": null
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "",
        "pos": "空白",
        "skip": true,
        "lookupWord": "",
        "baseForm": "",
        "conjugation": null
      },
      {
        "surface": "free",
        "romaji": "free",
        "meaning": "",
        "pos": "noun",
        "skip": true,
        "lookupWord": "",
        "baseForm": "",
        "conjugation": null
      }
    ],
    "translation": ""
  },
  {
    "id": "l54",
    "start": 166.42,
    "end": 169.33,
    "text": "見えるよ新時代が",
    "tokens": [
      {
        "surface": "見える",
        "romaji": "mieru",
        "meaning": "to be seen; to be visible; to be in sight",
        "pos": "verb",
        "skip": false,
        "lookupWord": "見える",
        "baseForm": "見える",
        "conjugation": null
      },
      {
        "surface": "よ",
        "romaji": "yo",
        "meaning": "indicates new information or emphasis (you know)",
        "pos": "particle",
        "skip": false
      },
      {
        "surface": "新",
        "romaji": "shin",
        "meaning": "new; neo-",
        "pos": "名詞接続",
        "skip": false,
        "lookupWord": "新",
        "baseForm": "新",
        "conjugation": null
      },
      {
        "surface": "時代",
        "romaji": "jidai",
        "meaning": "period; epoch; era; age",
        "pos": "noun",
        "skip": false,
        "lookupWord": "時代",
        "baseForm": "時代",
        "conjugation": null
      },
      {
        "surface": "が",
        "romaji": "ga",
        "meaning": "indicates subject of a sentence",
        "pos": "particle",
        "skip": false
      }
    ],
    "translation": "I can see a new era"
  },
  {
    "id": "l55",
    "start": 169.33,
    "end": 171.97,
    "text": "世界の向こうへ",
    "tokens": [
      {
        "surface": "世界",
        "romaji": "sekai",
        "meaning": "the world; society; the universe",
        "pos": "noun",
        "skip": false,
        "lookupWord": "世界",
        "baseForm": "世界",
        "conjugation": null
      },
      {
        "surface": "の",
        "romaji": "no",
        "meaning": "indicates possession or noun modification (of / 's)",
        "pos": "particle",
        "skip": false
      },
      {
        "surface": "向こう",
        "romaji": "mukou",
        "meaning": "opposite side; other side",
        "pos": "noun",
        "skip": false,
        "lookupWord": "向こう",
        "baseForm": "向こう",
        "conjugation": null
      },
      {
        "surface": "へ",
        "romaji": "he",
        "meaning": "indicates direction or goal (towards / to)",
        "pos": "particle",
        "skip": false
      }
    ],
    "translation": "To the other side of the world"
  },
  {
    "id": "l56",
    "start": 171.97,
    "end": 173.24,
    "text": "さあ行くよ",
    "tokens": [
      {
        "surface": "さあ",
        "romaji": "saa",
        "meaning": "come (on); come now; come along; here",
        "pos": "interjection",
        "skip": false,
        "lookupWord": "さあ",
        "baseForm": "さあ",
        "conjugation": null
      },
      {
        "surface": "行く",
        "romaji": "iku",
        "meaning": "to go; to move (towards); to head (towards); to leave (for)",
        "pos": "verb",
        "skip": false,
        "lookupWord": "行く",
        "baseForm": "行く",
        "conjugation": null
      },
      {
        "surface": "よ",
        "romaji": "yo",
        "meaning": "indicates new information or emphasis (you know)",
        "pos": "particle",
        "skip": false
      }
    ],
    "translation": "Let's go"
  },
  {
    "id": "l57",
    "start": 173.24,
    "end": 174.86,
    "text": "New world",
    "tokens": [
      {
        "surface": "new",
        "romaji": "new",
        "meaning": "",
        "pos": "noun",
        "skip": true,
        "lookupWord": "",
        "baseForm": "",
        "conjugation": null
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "",
        "pos": "空白",
        "skip": true,
        "lookupWord": "",
        "baseForm": "",
        "conjugation": null
      },
      {
        "surface": "world",
        "romaji": "world",
        "meaning": "",
        "pos": "noun",
        "skip": true,
        "lookupWord": "",
        "baseForm": "",
        "conjugation": null
      }
    ],
    "translation": ""
  },
  {
    "id": "l58",
    "start": 174.86,
    "end": 175.89,
    "text": "♪",
    "tokens": [
      {
        "surface": "♪",
        "romaji": "♪",
        "meaning": "",
        "pos": "noun",
        "skip": true,
        "lookupWord": "",
        "baseForm": "",
        "conjugation": null
      }
    ],
    "translation": ""
  },
  {
    "id": "l59",
    "start": 175.89,
    "end": 177.2,
    "text": "信じたいわ",
    "tokens": [
      {
        "surface": "信じたい",
        "romaji": "shinjitai",
        "meaning": "to believe; to believe in; to place trust in; to confide in; to have faith in",
        "pos": "verb",
        "skip": false,
        "lookupWord": "信じる",
        "baseForm": "信じる",
        "conjugation": "auxiliary / conjugated"
      },
      {
        "surface": "わ",
        "romaji": "wa",
        "meaning": "ring; circle; loop",
        "pos": "particle",
        "skip": false,
        "lookupWord": "わ",
        "baseForm": "わ",
        "conjugation": null
      }
    ],
    "translation": "I want to believe it"
  },
  {
    "id": "l60",
    "start": 177.2,
    "end": 178.68,
    "text": "この未来を",
    "tokens": [
      {
        "surface": "この",
        "romaji": "kono",
        "meaning": "this",
        "pos": "adjectival",
        "skip": false,
        "lookupWord": "この",
        "baseForm": "この",
        "conjugation": null
      },
      {
        "surface": "未来",
        "romaji": "mirai",
        "meaning": "(distant) future",
        "pos": "noun",
        "skip": false,
        "lookupWord": "未来",
        "baseForm": "未来",
        "conjugation": null
      },
      {
        "surface": "を",
        "romaji": "wo",
        "meaning": "indicates direct object of an action",
        "pos": "particle",
        "skip": false
      }
    ],
    "translation": "This future"
  },
  {
    "id": "l61",
    "start": 178.68,
    "end": 180.36,
    "text": "世界中全部",
    "tokens": [
      {
        "surface": "世界中",
        "romaji": "sekaijuu",
        "meaning": "around the world; throughout the world",
        "pos": "noun",
        "skip": false,
        "lookupWord": "世界中",
        "baseForm": "世界中",
        "conjugation": null
      },
      {
        "surface": "全部",
        "romaji": "zenbu",
        "meaning": "all; entire; whole; altogether",
        "pos": "noun",
        "skip": false,
        "lookupWord": "全部",
        "baseForm": "全部",
        "conjugation": null
      }
    ],
    "translation": "All over the world"
  },
  {
    "id": "l62",
    "start": 180.36,
    "end": 183.2,
    "text": "変えてしまえば",
    "tokens": [
      {
        "surface": "変えて",
        "romaji": "kaete",
        "meaning": "to change; to alter; to transform; to convert; to turn; to vary",
        "pos": "verb",
        "skip": false,
        "lookupWord": "変える",
        "baseForm": "変える",
        "conjugation": "te-form"
      },
      {
        "surface": "しまえ",
        "romaji": "shimae",
        "meaning": "to finish; to stop; to end; to put an end to; to bring to a close",
        "pos": "verb",
        "skip": false,
        "lookupWord": "しまう",
        "baseForm": "しまう",
        "conjugation": null
      },
      {
        "surface": "ば",
        "romaji": "ba",
        "meaning": "place; spot; space",
        "pos": "particle",
        "skip": false,
        "lookupWord": "ば",
        "baseForm": "ば",
        "conjugation": null
      }
    ],
    "translation": "If you change it"
  },
  {
    "id": "l63",
    "start": 183.2,
    "end": 186.61,
    "text": "変えてしまえば",
    "tokens": [
      {
        "surface": "変えて",
        "romaji": "kaete",
        "meaning": "to change; to alter; to transform; to convert; to turn; to vary",
        "pos": "verb",
        "skip": false,
        "lookupWord": "変える",
        "baseForm": "変える",
        "conjugation": "te-form"
      },
      {
        "surface": "しまえ",
        "romaji": "shimae",
        "meaning": "to finish; to stop; to end; to put an end to; to bring to a close",
        "pos": "verb",
        "skip": false,
        "lookupWord": "しまう",
        "baseForm": "しまう",
        "conjugation": null
      },
      {
        "surface": "ば",
        "romaji": "ba",
        "meaning": "place; spot; space",
        "pos": "particle",
        "skip": false,
        "lookupWord": "ば",
        "baseForm": "ば",
        "conjugation": null
      }
    ],
    "translation": "If you change it"
  },
  {
    "id": "l64",
    "start": 186.61,
    "end": 191.33,
    "text": "果てしない音楽がもっと届くように",
    "tokens": [
      {
        "surface": "果てしない",
        "romaji": "hateshinai",
        "meaning": "endless; boundless; everlasting",
        "pos": "adjective",
        "skip": false,
        "lookupWord": "果てしない",
        "baseForm": "果てしない",
        "conjugation": null
      },
      {
        "surface": "音楽",
        "romaji": "ongaku",
        "meaning": "music",
        "pos": "noun",
        "skip": false,
        "lookupWord": "音楽",
        "baseForm": "音楽",
        "conjugation": null
      },
      {
        "surface": "が",
        "romaji": "ga",
        "meaning": "indicates subject of a sentence",
        "pos": "particle",
        "skip": false
      },
      {
        "surface": "もっと",
        "romaji": "motto",
        "meaning": "(some) more; even more; longer; further",
        "pos": "adverb",
        "skip": false,
        "lookupWord": "もっと",
        "baseForm": "もっと",
        "conjugation": null
      },
      {
        "surface": "届く",
        "romaji": "todoku",
        "meaning": "to reach; to touch; to get to; to carry (of sound)",
        "pos": "verb",
        "skip": false,
        "lookupWord": "届く",
        "baseForm": "届く",
        "conjugation": null
      },
      {
        "surface": "よう",
        "romaji": "you",
        "meaning": "appearing ...; looking ...",
        "pos": "noun",
        "skip": false,
        "lookupWord": "よう",
        "baseForm": "よう",
        "conjugation": null
      },
      {
        "surface": "に",
        "romaji": "ni",
        "meaning": "indicates direction, destination, time, or target (to / at / in)",
        "pos": "particle",
        "skip": false
      }
    ],
    "translation": "May more endless music reach you"
  },
  {
    "id": "l65",
    "start": 191.33,
    "end": 194.12,
    "text": "夢を見せるよ",
    "tokens": [
      {
        "surface": "夢",
        "romaji": "yume",
        "meaning": "dream",
        "pos": "noun",
        "skip": false,
        "lookupWord": "夢",
        "baseForm": "夢",
        "conjugation": null
      },
      {
        "surface": "を",
        "romaji": "wo",
        "meaning": "indicates direct object of an action",
        "pos": "particle",
        "skip": false
      },
      {
        "surface": "見せる",
        "romaji": "miseru",
        "meaning": "to show; to display",
        "pos": "verb",
        "skip": false,
        "lookupWord": "見せる",
        "baseForm": "見せる",
        "conjugation": null
      },
      {
        "surface": "よ",
        "romaji": "yo",
        "meaning": "indicates new information or emphasis (you know)",
        "pos": "particle",
        "skip": false
      }
    ],
    "translation": "I'll show you a dream"
  },
  {
    "id": "l66",
    "start": 194.12,
    "end": 196.76,
    "text": "夢を見せるよ",
    "tokens": [
      {
        "surface": "夢",
        "romaji": "yume",
        "meaning": "dream",
        "pos": "noun",
        "skip": false,
        "lookupWord": "夢",
        "baseForm": "夢",
        "conjugation": null
      },
      {
        "surface": "を",
        "romaji": "wo",
        "meaning": "indicates direct object of an action",
        "pos": "particle",
        "skip": false
      },
      {
        "surface": "見せる",
        "romaji": "miseru",
        "meaning": "to show; to display",
        "pos": "verb",
        "skip": false,
        "lookupWord": "見せる",
        "baseForm": "見せる",
        "conjugation": null
      },
      {
        "surface": "よ",
        "romaji": "yo",
        "meaning": "indicates new information or emphasis (you know)",
        "pos": "particle",
        "skip": false
      }
    ],
    "translation": "I'll show you a dream"
  },
  {
    "id": "l67",
    "start": 196.76,
    "end": 198.22,
    "text": "新時代だ",
    "tokens": [
      {
        "surface": "新",
        "romaji": "shin",
        "meaning": "new; neo-",
        "pos": "名詞接続",
        "skip": false,
        "lookupWord": "新",
        "baseForm": "新",
        "conjugation": null
      },
      {
        "surface": "時代",
        "romaji": "jidai",
        "meaning": "period; epoch; era; age",
        "pos": "noun",
        "skip": false,
        "lookupWord": "時代",
        "baseForm": "時代",
        "conjugation": null
      },
      {
        "surface": "だ",
        "romaji": "da",
        "meaning": "be; is",
        "pos": "auxiliary verb",
        "skip": false,
        "lookupWord": "だ",
        "baseForm": "だ",
        "conjugation": null
      }
    ],
    "translation": "It's a new era"
  },
  {
    "id": "l68",
    "start": 198.22,
    "end": 206.52,
    "text": "♪",
    "tokens": [
      {
        "surface": "♪",
        "romaji": "♪",
        "meaning": "",
        "pos": "noun",
        "skip": true,
        "lookupWord": "",
        "baseForm": "",
        "conjugation": null
      }
    ],
    "translation": ""
  },
  {
    "id": "l69",
    "start": 206.52,
    "end": 211.68,
    "text": "Ooh",
    "tokens": [
      {
        "surface": "Ooh",
        "romaji": "Ooh",
        "meaning": "",
        "pos": "noun",
        "skip": true,
        "lookupWord": "",
        "baseForm": "",
        "conjugation": null
      }
    ],
    "translation": ""
  },
  {
    "id": "l70",
    "start": 211.68,
    "end": 218.72,
    "text": "♪",
    "tokens": [
      {
        "surface": "♪",
        "romaji": "♪",
        "meaning": "",
        "pos": "noun",
        "skip": true,
        "lookupWord": "",
        "baseForm": "",
        "conjugation": null
      }
    ],
    "translation": ""
  },
  {
    "id": "l71",
    "start": 218.72,
    "end": 222.72,
    "text": "新時代だ",
    "tokens": [
      {
        "surface": "新",
        "romaji": "shin",
        "meaning": "new; neo-",
        "pos": "名詞接続",
        "skip": false,
        "lookupWord": "新",
        "baseForm": "新",
        "conjugation": null
      },
      {
        "surface": "時代",
        "romaji": "jidai",
        "meaning": "period; epoch; era; age",
        "pos": "noun",
        "skip": false,
        "lookupWord": "時代",
        "baseForm": "時代",
        "conjugation": null
      },
      {
        "surface": "だ",
        "romaji": "da",
        "meaning": "be; is",
        "pos": "auxiliary verb",
        "skip": false,
        "lookupWord": "だ",
        "baseForm": "だ",
        "conjugation": null
      }
    ],
    "translation": "It's a new era"
  }
];
