import { LyricLine } from "@/lib/types";

// Auto-generated by scripts/generate-lyrics.mjs for "someday" by Emarie.
// Words come from kuromoji (segmentation), wanakana (romaji), and Jisho
// (dictionary meanings) — spot-check before shipping, don't trust blindly.
export const somedayLyrics: LyricLine[] = [
  {
    "id": "l1",
    "start": 8.83,
    "end": 15.46,
    "tokens": [
      {
        "surface": "Was",
        "romaji": "Was",
        "meaning": "was; were",
        "pos": "noun"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "空白",
        "skip": true
      },
      {
        "surface": "good",
        "romaji": "good",
        "meaning": "good; excellent; fine; nice; pleasant; agreeable",
        "pos": "noun"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "空白",
        "skip": true
      },
      {
        "surface": "to",
        "romaji": "to",
        "meaning": "door (esp. Japanese-style)",
        "pos": "noun"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "空白",
        "skip": true
      },
      {
        "surface": "know",
        "romaji": "know",
        "meaning": "to know; to be aware (of); to be acquainted (with)",
        "pos": "noun"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "空白",
        "skip": true
      },
      {
        "surface": "you",
        "romaji": "you",
        "meaning": "appearing ...; looking ...",
        "pos": "noun"
      }
    ],
    "translation": "Was good to know you"
  },
  {
    "id": "l2",
    "start": 15.46,
    "end": 21.6,
    "tokens": [
      {
        "surface": "But",
        "romaji": "But",
        "meaning": "Butterfly (Koda Kumi song)",
        "pos": "noun"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "空白",
        "skip": true
      },
      {
        "surface": "I",
        "romaji": "I",
        "meaning": "1st (in a sequence denoted by the iroha system); a; i",
        "pos": "noun"
      },
      {
        "surface": "'",
        "romaji": "'",
        "meaning": "some nerve (as in \"you have some nerve to ...\")",
        "pos": "noun"
      },
      {
        "surface": "m",
        "romaji": "m",
        "meaning": "morning; a.m.",
        "pos": "noun"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "空白",
        "skip": true
      },
      {
        "surface": "not",
        "romaji": "not",
        "meaning": "not exceeding ...; not more than ...; ... and under; ... and below; ... or fewer",
        "pos": "noun"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "空白",
        "skip": true
      },
      {
        "surface": "gonna",
        "romaji": "gonna",
        "meaning": "You're Gonna Make Me Lonesome When You Go",
        "pos": "noun"
      }
    ],
    "translation": "But I'm not gonna"
  },
  {
    "id": "l3",
    "start": 21.6,
    "end": 29.27,
    "tokens": [
      {
        "surface": "Pretend",
        "romaji": "Pretend",
        "meaning": "to pretend; to feign",
        "pos": "noun"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "空白",
        "skip": true
      },
      {
        "surface": "I",
        "romaji": "I",
        "meaning": "1st (in a sequence denoted by the iroha system); a; i",
        "pos": "noun"
      },
      {
        "surface": "'",
        "romaji": "'",
        "meaning": "some nerve (as in \"you have some nerve to ...\")",
        "pos": "noun"
      },
      {
        "surface": "m",
        "romaji": "m",
        "meaning": "morning; a.m.",
        "pos": "noun"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "空白",
        "skip": true
      },
      {
        "surface": "all",
        "romaji": "all",
        "meaning": "all; entire; whole; altogether",
        "pos": "noun"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "空白",
        "skip": true
      },
      {
        "surface": "better",
        "romaji": "better",
        "meaning": "better; preferable; less objectionable; least-worst",
        "pos": "noun"
      }
    ],
    "translation": "Pretend I'm all better"
  },
  {
    "id": "l4",
    "start": 29.27,
    "end": 36.09,
    "tokens": [
      {
        "surface": "Thought",
        "romaji": "Thought",
        "meaning": "thought; consideration; thinking",
        "pos": "noun"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "空白",
        "skip": true
      },
      {
        "surface": "we",
        "romaji": "we",
        "meaning": "we",
        "pos": "noun"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "空白",
        "skip": true
      },
      {
        "surface": "were",
        "romaji": "were",
        "meaning": "was; were",
        "pos": "noun"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "空白",
        "skip": true
      },
      {
        "surface": "forever",
        "romaji": "forever",
        "meaning": "forever; eternally; for good; as long as one likes; indefinitely; endlessly; for a long time",
        "pos": "noun"
      }
    ],
    "translation": "Thought we were forever"
  },
  {
    "id": "l5",
    "start": 36.09,
    "end": 42.01,
    "tokens": [
      {
        "surface": "Hearts",
        "romaji": "Hearts",
        "meaning": "animal heart (usu. grilled on skewers)",
        "pos": "noun"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "空白",
        "skip": true
      },
      {
        "surface": "still",
        "romaji": "still",
        "meaning": "still; yet",
        "pos": "noun"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "空白",
        "skip": true
      },
      {
        "surface": "in",
        "romaji": "in",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "noun"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "空白",
        "skip": true
      },
      {
        "surface": "pieces",
        "romaji": "pieces",
        "meaning": "cutting to pieces; tearing to pieces",
        "pos": "noun"
      }
    ],
    "translation": "Hearts still in pieces"
  },
  {
    "id": "l6",
    "start": 42.01,
    "end": 48.47,
    "tokens": [
      {
        "surface": "And",
        "romaji": "And",
        "meaning": "Android (operating system)",
        "pos": "noun"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "空白",
        "skip": true
      },
      {
        "surface": "your",
        "romaji": "your",
        "meaning": "your house; your home; your family",
        "pos": "noun"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "空白",
        "skip": true
      },
      {
        "surface": "shadow",
        "romaji": "shadow",
        "meaning": "shadow; silhouette; figure; shape",
        "pos": "noun"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "空白",
        "skip": true
      },
      {
        "surface": "follows",
        "romaji": "follows",
        "meaning": "in the following manner; as follows",
        "pos": "noun"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "空白",
        "skip": true
      },
      {
        "surface": "me",
        "romaji": "me",
        "meaning": "eye; eyeball",
        "pos": "noun"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "空白",
        "skip": true
      },
      {
        "surface": "places",
        "romaji": "places",
        "meaning": "places alongside a railway line, bus route, major thoroughfare, etc.",
        "pos": "noun"
      },
      {
        "surface": ",",
        "romaji": ",",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "noun"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "空白",
        "skip": true
      },
      {
        "surface": "all",
        "romaji": "all",
        "meaning": "all; entire; whole; altogether",
        "pos": "noun"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "空白",
        "skip": true
      },
      {
        "surface": "the",
        "romaji": "the",
        "meaning": "river; stream",
        "pos": "noun"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "空白",
        "skip": true
      },
      {
        "surface": "time",
        "romaji": "time",
        "meaning": "bloodshot eyes",
        "pos": "noun"
      }
    ],
    "translation": "And your shadow follows me places, all the time"
  },
  {
    "id": "l7",
    "start": 48.47,
    "end": 55.9,
    "tokens": [
      {
        "surface": "I",
        "romaji": "I",
        "meaning": "1st (in a sequence denoted by the iroha system); a; i",
        "pos": "noun"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "空白",
        "skip": true
      },
      {
        "surface": "can",
        "romaji": "can",
        "meaning": "can; tin",
        "pos": "noun"
      },
      {
        "surface": "'",
        "romaji": "'",
        "meaning": "some nerve (as in \"you have some nerve to ...\")",
        "pos": "noun"
      },
      {
        "surface": "t",
        "romaji": "t",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "noun"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "空白",
        "skip": true
      },
      {
        "surface": "shake",
        "romaji": "shake",
        "meaning": "family of Shinto priests serving a shrine on a hereditary basis",
        "pos": "noun"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "空白",
        "skip": true
      },
      {
        "surface": "this",
        "romaji": "this",
        "meaning": "this; this one",
        "pos": "noun"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "空白",
        "skip": true
      },
      {
        "surface": "feeling",
        "romaji": "feeling",
        "meaning": "feeling; mood",
        "pos": "noun"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "空白",
        "skip": true
      },
      {
        "surface": "of",
        "romaji": "of",
        "meaning": "member of an assembly; member of the Diet; member of parliament; member of Congress",
        "pos": "noun"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "空白",
        "skip": true
      },
      {
        "surface": "loneliness",
        "romaji": "loneliness",
        "meaning": "solitude; loneliness; isolation",
        "pos": "noun"
      }
    ],
    "translation": "I can't shake this feeling of loneliness"
  },
  {
    "id": "l8",
    "start": 55.9,
    "end": 59.65,
    "tokens": [
      {
        "surface": "That",
        "romaji": "That",
        "meaning": "that; that thing",
        "pos": "noun"
      },
      {
        "surface": "'",
        "romaji": "'",
        "meaning": "some nerve (as in \"you have some nerve to ...\")",
        "pos": "noun"
      },
      {
        "surface": "s",
        "romaji": "s",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "noun"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "空白",
        "skip": true
      },
      {
        "surface": "just",
        "romaji": "just",
        "meaning": "just (now, at the moment, etc.); just as; in the act of; as soon as; at the moment that",
        "pos": "noun"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "空白",
        "skip": true
      },
      {
        "surface": "life",
        "romaji": "life",
        "meaning": "life; life force",
        "pos": "noun"
      },
      {
        "surface": ",",
        "romaji": ",",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "noun"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "空白",
        "skip": true
      },
      {
        "surface": "I",
        "romaji": "I",
        "meaning": "1st (in a sequence denoted by the iroha system); a; i",
        "pos": "noun"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "空白",
        "skip": true
      },
      {
        "surface": "guess",
        "romaji": "guess",
        "meaning": "guess; conjecture",
        "pos": "noun"
      }
    ],
    "translation": "That's just life, I guess"
  },
  {
    "id": "l9",
    "start": 59.65,
    "end": 63.34,
    "tokens": [
      {
        "surface": "But",
        "romaji": "But",
        "meaning": "Butterfly (Koda Kumi song)",
        "pos": "noun"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "空白",
        "skip": true
      },
      {
        "surface": "I",
        "romaji": "I",
        "meaning": "1st (in a sequence denoted by the iroha system); a; i",
        "pos": "noun"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "空白",
        "skip": true
      },
      {
        "surface": "believe",
        "romaji": "believe",
        "meaning": "to believe; to believe in; to place trust in; to confide in; to have faith in",
        "pos": "noun"
      },
      {
        "surface": ",",
        "romaji": ",",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "noun"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "空白",
        "skip": true
      },
      {
        "surface": "someday",
        "romaji": "someday",
        "meaning": "before very long; soon; someday; one of these days; sooner or later",
        "pos": "noun"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "空白",
        "skip": true
      },
      {
        "surface": "soon",
        "romaji": "soon",
        "meaning": "soon; shortly; before long; in a short time; in a little while",
        "pos": "noun"
      }
    ],
    "translation": "But I believe, someday soon"
  },
  {
    "id": "l10",
    "start": 63.34,
    "end": 68.05,
    "tokens": [
      {
        "surface": "I",
        "romaji": "I",
        "meaning": "1st (in a sequence denoted by the iroha system); a; i",
        "pos": "noun"
      },
      {
        "surface": "'",
        "romaji": "'",
        "meaning": "some nerve (as in \"you have some nerve to ...\")",
        "pos": "noun"
      },
      {
        "surface": "ll",
        "romaji": "ll",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "noun"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "空白",
        "skip": true
      },
      {
        "surface": "learn",
        "romaji": "learn",
        "meaning": "to take lessons in; to be taught; to learn (from a teacher); to study (under a teacher); to get training in",
        "pos": "noun"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "空白",
        "skip": true
      },
      {
        "surface": "to",
        "romaji": "to",
        "meaning": "door (esp. Japanese-style)",
        "pos": "noun"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "空白",
        "skip": true
      },
      {
        "surface": "overcome",
        "romaji": "overcome",
        "meaning": "to push aside; to overcome (e.g. difficulties); to reject",
        "pos": "noun"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "空白",
        "skip": true
      },
      {
        "surface": "it",
        "romaji": "it",
        "meaning": "that; it",
        "pos": "noun"
      }
    ],
    "translation": "I'll learn to overcome it"
  },
  {
    "id": "l11",
    "start": 68.05,
    "end": 71.67,
    "tokens": [
      {
        "surface": "The",
        "romaji": "The",
        "meaning": "The Harimaya Bridge",
        "pos": "noun"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "空白",
        "skip": true
      },
      {
        "surface": "scars",
        "romaji": "scars",
        "meaning": "fingernail mark; scratch",
        "pos": "noun"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "空白",
        "skip": true
      },
      {
        "surface": "will",
        "romaji": "will",
        "meaning": "will; volition; intention; intent; determination",
        "pos": "noun"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "空白",
        "skip": true
      },
      {
        "surface": "heal",
        "romaji": "heal",
        "meaning": "to cure; to heal",
        "pos": "noun"
      },
      {
        "surface": ",",
        "romaji": ",",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "noun"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "空白",
        "skip": true
      },
      {
        "surface": "heart",
        "romaji": "heart",
        "meaning": "heart",
        "pos": "noun"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "空白",
        "skip": true
      },
      {
        "surface": "will",
        "romaji": "will",
        "meaning": "will; volition; intention; intent; determination",
        "pos": "noun"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "空白",
        "skip": true
      },
      {
        "surface": "bloom",
        "romaji": "bloom",
        "meaning": "flower; blossom; bloom; petal",
        "pos": "noun"
      }
    ],
    "translation": "The scars will heal, heart will bloom"
  },
  {
    "id": "l12",
    "start": 71.67,
    "end": 73.47,
    "tokens": [
      {
        "surface": "No",
        "romaji": "No",
        "meaning": "Nothing Without You (song)",
        "pos": "noun"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "空白",
        "skip": true
      },
      {
        "surface": "more",
        "romaji": "more",
        "meaning": "leak; leakage",
        "pos": "noun"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "空白",
        "skip": true
      },
      {
        "surface": "dwelling",
        "romaji": "dwelling",
        "meaning": "dwelling; house; residence; address",
        "pos": "noun"
      }
    ],
    "translation": "No more dwelling"
  },
  {
    "id": "l13",
    "start": 73.47,
    "end": 76.85,
    "tokens": [
      {
        "surface": "'",
        "romaji": "'",
        "meaning": "some nerve (as in \"you have some nerve to ...\")",
        "pos": "noun"
      },
      {
        "surface": "Cause",
        "romaji": "Cause",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "noun"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "空白",
        "skip": true
      },
      {
        "surface": "today",
        "romaji": "today",
        "meaning": "today; this day",
        "pos": "noun"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "空白",
        "skip": true
      },
      {
        "surface": "I",
        "romaji": "I",
        "meaning": "1st (in a sequence denoted by the iroha system); a; i",
        "pos": "noun"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "空白",
        "skip": true
      },
      {
        "surface": "choose",
        "romaji": "choose",
        "meaning": "to choose; to select; to pick (out)",
        "pos": "noun"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "空白",
        "skip": true
      },
      {
        "surface": "to",
        "romaji": "to",
        "meaning": "door (esp. Japanese-style)",
        "pos": "noun"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "空白",
        "skip": true
      },
      {
        "surface": "say",
        "romaji": "say",
        "meaning": "say; well; um; er",
        "pos": "noun"
      }
    ],
    "translation": "'Cause today I choose to say"
  },
  {
    "id": "l14",
    "start": 76.85,
    "end": 79.77,
    "tokens": [
      {
        "surface": "\"",
        "romaji": "\"",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "noun"
      },
      {
        "surface": "I",
        "romaji": "I",
        "meaning": "1st (in a sequence denoted by the iroha system); a; i",
        "pos": "noun"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "空白",
        "skip": true
      },
      {
        "surface": "will",
        "romaji": "will",
        "meaning": "will; volition; intention; intent; determination",
        "pos": "noun"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "空白",
        "skip": true
      },
      {
        "surface": "love",
        "romaji": "love",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "noun"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "空白",
        "skip": true
      },
      {
        "surface": "again",
        "romaji": "again",
        "meaning": "again; once more; once again; another time; some other time",
        "pos": "noun"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "空白",
        "skip": true
      },
      {
        "surface": "someday",
        "romaji": "someday",
        "meaning": "before very long; soon; someday; one of these days; sooner or later",
        "pos": "noun"
      },
      {
        "surface": "\"",
        "romaji": "\"",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "noun"
      }
    ],
    "translation": "\"I will love again someday\""
  },
  {
    "id": "l15",
    "start": 79.77,
    "end": 83.17,
    "tokens": [
      {
        "surface": "So",
        "romaji": "So",
        "meaning": "Soviet Union",
        "pos": "noun"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "空白",
        "skip": true
      },
      {
        "surface": "I",
        "romaji": "I",
        "meaning": "1st (in a sequence denoted by the iroha system); a; i",
        "pos": "noun"
      },
      {
        "surface": "'",
        "romaji": "'",
        "meaning": "some nerve (as in \"you have some nerve to ...\")",
        "pos": "noun"
      },
      {
        "surface": "m",
        "romaji": "m",
        "meaning": "morning; a.m.",
        "pos": "noun"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "空白",
        "skip": true
      },
      {
        "surface": "not",
        "romaji": "not",
        "meaning": "not exceeding ...; not more than ...; ... and under; ... and below; ... or fewer",
        "pos": "noun"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "空白",
        "skip": true
      },
      {
        "surface": "gonna",
        "romaji": "gonna",
        "meaning": "You're Gonna Make Me Lonesome When You Go",
        "pos": "noun"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "空白",
        "skip": true
      },
      {
        "surface": "stay",
        "romaji": "stay",
        "meaning": "stay; sojourn",
        "pos": "noun"
      }
    ],
    "translation": "So I'm not gonna stay"
  },
  {
    "id": "l16",
    "start": 83.17,
    "end": 101.98,
    "tokens": [
      {
        "surface": "Paralyzed",
        "romaji": "Paralyzed",
        "meaning": "to be petrified; to be unable to move; to be paralyzed (with horror); to be stupefied (with amazement)",
        "pos": "noun"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "空白",
        "skip": true
      },
      {
        "surface": "'",
        "romaji": "'",
        "meaning": "some nerve (as in \"you have some nerve to ...\")",
        "pos": "noun"
      },
      {
        "surface": "cause",
        "romaji": "cause",
        "meaning": "cause; origin; source",
        "pos": "noun"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "空白",
        "skip": true
      },
      {
        "surface": "I",
        "romaji": "I",
        "meaning": "1st (in a sequence denoted by the iroha system); a; i",
        "pos": "noun"
      },
      {
        "surface": "'",
        "romaji": "'",
        "meaning": "some nerve (as in \"you have some nerve to ...\")",
        "pos": "noun"
      },
      {
        "surface": "m",
        "romaji": "m",
        "meaning": "morning; a.m.",
        "pos": "noun"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "空白",
        "skip": true
      },
      {
        "surface": "not",
        "romaji": "not",
        "meaning": "not exceeding ...; not more than ...; ... and under; ... and below; ... or fewer",
        "pos": "noun"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "空白",
        "skip": true
      },
      {
        "surface": "by",
        "romaji": "by",
        "meaning": "with; by; by means of",
        "pos": "noun"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "空白",
        "skip": true
      },
      {
        "surface": "your",
        "romaji": "your",
        "meaning": "your house; your home; your family",
        "pos": "noun"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "空白",
        "skip": true
      },
      {
        "surface": "side",
        "romaji": "side",
        "meaning": "zigzag-shaped paper streamer often used to adorn Shinto-related objects",
        "pos": "noun"
      }
    ],
    "translation": "Paralyzed 'cause I'm not by your side"
  },
  {
    "id": "l17",
    "start": 101.98,
    "end": 108.93,
    "tokens": [
      {
        "surface": "Time",
        "romaji": "Time",
        "meaning": "Time (Arashi album)",
        "pos": "noun"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "空白",
        "skip": true
      },
      {
        "surface": "passes",
        "romaji": "passes",
        "meaning": "boarding pass; boarding ticket",
        "pos": "noun"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "空白",
        "skip": true
      },
      {
        "surface": "slowly",
        "romaji": "slowly",
        "meaning": "slowly; unhurriedly; without haste; leisurely; at one's leisure",
        "pos": "noun"
      }
    ],
    "translation": "Time passes slowly"
  },
  {
    "id": "l18",
    "start": 108.93,
    "end": 115.13,
    "tokens": [
      {
        "surface": "Makes",
        "romaji": "Makes",
        "meaning": "to hang up (e.g. a coat, a picture on the wall); to let hang; to suspend (from); to hoist (e.g. sail); to raise (e.g. flag)",
        "pos": "noun"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "空白",
        "skip": true
      },
      {
        "surface": "me",
        "romaji": "me",
        "meaning": "eye; eyeball",
        "pos": "noun"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "空白",
        "skip": true
      },
      {
        "surface": "feel",
        "romaji": "feel",
        "meaning": "feel (of something); touch; texture; sensation",
        "pos": "noun"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "空白",
        "skip": true
      },
      {
        "surface": "lonely",
        "romaji": "lonely",
        "meaning": "lonely; lonesome; solitary; desolate",
        "pos": "noun"
      }
    ],
    "translation": "Makes me feel lonely"
  },
  {
    "id": "l19",
    "start": 115.13,
    "end": 122.28,
    "tokens": [
      {
        "surface": "Gotta",
        "romaji": "Gotta",
        "meaning": "She's Gotta Have It (film)",
        "pos": "noun"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "空白",
        "skip": true
      },
      {
        "surface": "stop",
        "romaji": "stop",
        "meaning": "to stop (moving); to come to a stop",
        "pos": "noun"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "空白",
        "skip": true
      },
      {
        "surface": "feeling",
        "romaji": "feeling",
        "meaning": "feeling; mood",
        "pos": "noun"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "空白",
        "skip": true
      },
      {
        "surface": "sorry",
        "romaji": "sorry",
        "meaning": "inexcusable; unjustifiable; unpardonable",
        "pos": "noun"
      }
    ],
    "translation": "Gotta stop feeling sorry"
  },
  {
    "id": "l20",
    "start": 122.28,
    "end": 129.26,
    "tokens": [
      {
        "surface": "I",
        "romaji": "I",
        "meaning": "1st (in a sequence denoted by the iroha system); a; i",
        "pos": "noun"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "空白",
        "skip": true
      },
      {
        "surface": "can",
        "romaji": "can",
        "meaning": "can; tin",
        "pos": "noun"
      },
      {
        "surface": "'",
        "romaji": "'",
        "meaning": "some nerve (as in \"you have some nerve to ...\")",
        "pos": "noun"
      },
      {
        "surface": "t",
        "romaji": "t",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "noun"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "空白",
        "skip": true
      },
      {
        "surface": "always",
        "romaji": "always",
        "meaning": "always; all the time; at all times",
        "pos": "noun"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "空白",
        "skip": true
      },
      {
        "surface": "feel",
        "romaji": "feel",
        "meaning": "feel (of something); touch; texture; sensation",
        "pos": "noun"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "空白",
        "skip": true
      },
      {
        "surface": "worried",
        "romaji": "worried",
        "meaning": "to be troubled; to have difficulty; to be in a fix; to be at a loss; to be stumped; to be embarrassed",
        "pos": "noun"
      }
    ],
    "translation": "I can't always feel worried"
  },
  {
    "id": "l21",
    "start": 129.26,
    "end": 135.42,
    "tokens": [
      {
        "surface": "Mind",
        "romaji": "Mind",
        "meaning": "mind; heart; spirit",
        "pos": "noun"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "空白",
        "skip": true
      },
      {
        "surface": "won",
        "romaji": "won",
        "meaning": "won (currency of North Korea and South Korea)",
        "pos": "noun"
      },
      {
        "surface": "'",
        "romaji": "'",
        "meaning": "some nerve (as in \"you have some nerve to ...\")",
        "pos": "noun"
      },
      {
        "surface": "t",
        "romaji": "t",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "noun"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "空白",
        "skip": true
      },
      {
        "surface": "stop",
        "romaji": "stop",
        "meaning": "to stop (moving); to come to a stop",
        "pos": "noun"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "空白",
        "skip": true
      },
      {
        "surface": "spinning",
        "romaji": "spinning",
        "meaning": "spinning (textiles)",
        "pos": "noun"
      }
    ],
    "translation": "Mind won't stop spinning"
  },
  {
    "id": "l22",
    "start": 135.42,
    "end": 141.48,
    "tokens": [
      {
        "surface": "And",
        "romaji": "And",
        "meaning": "Android (operating system)",
        "pos": "noun"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "空白",
        "skip": true
      },
      {
        "surface": "I",
        "romaji": "I",
        "meaning": "1st (in a sequence denoted by the iroha system); a; i",
        "pos": "noun"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "空白",
        "skip": true
      },
      {
        "surface": "keep",
        "romaji": "keep",
        "meaning": "to keep (a pet or other animal); to have; to own; to raise; to rear; to feed",
        "pos": "noun"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "空白",
        "skip": true
      },
      {
        "surface": "on",
        "romaji": "on",
        "meaning": "favour; favor; obligation; debt of gratitude",
        "pos": "noun"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "空白",
        "skip": true
      },
      {
        "surface": "overthinking",
        "romaji": "overthinking",
        "meaning": "overthinking",
        "pos": "noun"
      },
      {
        "surface": ",",
        "romaji": ",",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "noun"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "空白",
        "skip": true
      },
      {
        "surface": "all",
        "romaji": "all",
        "meaning": "all; entire; whole; altogether",
        "pos": "noun"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "空白",
        "skip": true
      },
      {
        "surface": "the",
        "romaji": "the",
        "meaning": "river; stream",
        "pos": "noun"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "空白",
        "skip": true
      },
      {
        "surface": "time",
        "romaji": "time",
        "meaning": "bloodshot eyes",
        "pos": "noun"
      }
    ],
    "translation": "And I keep on overthinking, all the time"
  },
  {
    "id": "l23",
    "start": 141.48,
    "end": 148.82,
    "tokens": [
      {
        "surface": "I",
        "romaji": "I",
        "meaning": "1st (in a sequence denoted by the iroha system); a; i",
        "pos": "noun"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "空白",
        "skip": true
      },
      {
        "surface": "hope",
        "romaji": "hope",
        "meaning": "hope; wish; aspiration",
        "pos": "noun"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "空白",
        "skip": true
      },
      {
        "surface": "with",
        "romaji": "with",
        "meaning": "together; jointly",
        "pos": "noun"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "空白",
        "skip": true
      },
      {
        "surface": "time",
        "romaji": "time",
        "meaning": "bloodshot eyes",
        "pos": "noun"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "空白",
        "skip": true
      },
      {
        "surface": "the",
        "romaji": "the",
        "meaning": "river; stream",
        "pos": "noun"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "空白",
        "skip": true
      },
      {
        "surface": "healing",
        "romaji": "healing",
        "meaning": "healing; cure; recovery",
        "pos": "noun"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "空白",
        "skip": true
      },
      {
        "surface": "will",
        "romaji": "will",
        "meaning": "will; volition; intention; intent; determination",
        "pos": "noun"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "空白",
        "skip": true
      },
      {
        "surface": "mend",
        "romaji": "mend",
        "meaning": "to mend; to patch up; to repair; to fix; to darn",
        "pos": "noun"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "空白",
        "skip": true
      },
      {
        "surface": "my",
        "romaji": "my",
        "meaning": "my; our; one's own",
        "pos": "noun"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "空白",
        "skip": true
      },
      {
        "surface": "soul",
        "romaji": "soul",
        "meaning": "soul; spirit; departed soul; ghost",
        "pos": "noun"
      }
    ],
    "translation": "I hope with time the healing will mend my soul"
  },
  {
    "id": "l24",
    "start": 148.82,
    "end": 152.86,
    "tokens": [
      {
        "surface": "And",
        "romaji": "And",
        "meaning": "Android (operating system)",
        "pos": "noun"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "空白",
        "skip": true
      },
      {
        "surface": "I",
        "romaji": "I",
        "meaning": "1st (in a sequence denoted by the iroha system); a; i",
        "pos": "noun"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "空白",
        "skip": true
      },
      {
        "surface": "can",
        "romaji": "can",
        "meaning": "can; tin",
        "pos": "noun"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "空白",
        "skip": true
      },
      {
        "surface": "let",
        "romaji": "let",
        "meaning": "to let pass; to allow through; to let through; to make way (for)",
        "pos": "noun"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "空白",
        "skip": true
      },
      {
        "surface": "you",
        "romaji": "you",
        "meaning": "appearing ...; looking ...",
        "pos": "noun"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "空白",
        "skip": true
      },
      {
        "surface": "go",
        "romaji": "go",
        "meaning": "five; 5",
        "pos": "noun"
      }
    ],
    "translation": "And I can let you go"
  },
  {
    "id": "l25",
    "start": 152.86,
    "end": 156.6,
    "tokens": [
      {
        "surface": "But",
        "romaji": "But",
        "meaning": "Butterfly (Koda Kumi song)",
        "pos": "noun"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "空白",
        "skip": true
      },
      {
        "surface": "I",
        "romaji": "I",
        "meaning": "1st (in a sequence denoted by the iroha system); a; i",
        "pos": "noun"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "空白",
        "skip": true
      },
      {
        "surface": "believe",
        "romaji": "believe",
        "meaning": "to believe; to believe in; to place trust in; to confide in; to have faith in",
        "pos": "noun"
      },
      {
        "surface": ",",
        "romaji": ",",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "noun"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "空白",
        "skip": true
      },
      {
        "surface": "someday",
        "romaji": "someday",
        "meaning": "before very long; soon; someday; one of these days; sooner or later",
        "pos": "noun"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "空白",
        "skip": true
      },
      {
        "surface": "soon",
        "romaji": "soon",
        "meaning": "soon; shortly; before long; in a short time; in a little while",
        "pos": "noun"
      }
    ],
    "translation": "But I believe, someday soon"
  },
  {
    "id": "l26",
    "start": 156.6,
    "end": 161.27,
    "tokens": [
      {
        "surface": "I",
        "romaji": "I",
        "meaning": "1st (in a sequence denoted by the iroha system); a; i",
        "pos": "noun"
      },
      {
        "surface": "'",
        "romaji": "'",
        "meaning": "some nerve (as in \"you have some nerve to ...\")",
        "pos": "noun"
      },
      {
        "surface": "ll",
        "romaji": "ll",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "noun"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "空白",
        "skip": true
      },
      {
        "surface": "learn",
        "romaji": "learn",
        "meaning": "to take lessons in; to be taught; to learn (from a teacher); to study (under a teacher); to get training in",
        "pos": "noun"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "空白",
        "skip": true
      },
      {
        "surface": "to",
        "romaji": "to",
        "meaning": "door (esp. Japanese-style)",
        "pos": "noun"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "空白",
        "skip": true
      },
      {
        "surface": "overcome",
        "romaji": "overcome",
        "meaning": "to push aside; to overcome (e.g. difficulties); to reject",
        "pos": "noun"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "空白",
        "skip": true
      },
      {
        "surface": "it",
        "romaji": "it",
        "meaning": "that; it",
        "pos": "noun"
      }
    ],
    "translation": "I'll learn to overcome it"
  },
  {
    "id": "l27",
    "start": 161.27,
    "end": 164.83,
    "tokens": [
      {
        "surface": "The",
        "romaji": "The",
        "meaning": "The Harimaya Bridge",
        "pos": "noun"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "空白",
        "skip": true
      },
      {
        "surface": "scars",
        "romaji": "scars",
        "meaning": "fingernail mark; scratch",
        "pos": "noun"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "空白",
        "skip": true
      },
      {
        "surface": "will",
        "romaji": "will",
        "meaning": "will; volition; intention; intent; determination",
        "pos": "noun"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "空白",
        "skip": true
      },
      {
        "surface": "heal",
        "romaji": "heal",
        "meaning": "to cure; to heal",
        "pos": "noun"
      },
      {
        "surface": ",",
        "romaji": ",",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "noun"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "空白",
        "skip": true
      },
      {
        "surface": "heart",
        "romaji": "heart",
        "meaning": "heart",
        "pos": "noun"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "空白",
        "skip": true
      },
      {
        "surface": "will",
        "romaji": "will",
        "meaning": "will; volition; intention; intent; determination",
        "pos": "noun"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "空白",
        "skip": true
      },
      {
        "surface": "bloom",
        "romaji": "bloom",
        "meaning": "flower; blossom; bloom; petal",
        "pos": "noun"
      }
    ],
    "translation": "The scars will heal, heart will bloom"
  },
  {
    "id": "l28",
    "start": 164.83,
    "end": 166.46,
    "tokens": [
      {
        "surface": "No",
        "romaji": "No",
        "meaning": "Nothing Without You (song)",
        "pos": "noun"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "空白",
        "skip": true
      },
      {
        "surface": "more",
        "romaji": "more",
        "meaning": "leak; leakage",
        "pos": "noun"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "空白",
        "skip": true
      },
      {
        "surface": "dwelling",
        "romaji": "dwelling",
        "meaning": "dwelling; house; residence; address",
        "pos": "noun"
      }
    ],
    "translation": "No more dwelling"
  },
  {
    "id": "l29",
    "start": 166.46,
    "end": 169.86,
    "tokens": [
      {
        "surface": "'",
        "romaji": "'",
        "meaning": "some nerve (as in \"you have some nerve to ...\")",
        "pos": "noun"
      },
      {
        "surface": "Cause",
        "romaji": "Cause",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "noun"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "空白",
        "skip": true
      },
      {
        "surface": "today",
        "romaji": "today",
        "meaning": "today; this day",
        "pos": "noun"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "空白",
        "skip": true
      },
      {
        "surface": "I",
        "romaji": "I",
        "meaning": "1st (in a sequence denoted by the iroha system); a; i",
        "pos": "noun"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "空白",
        "skip": true
      },
      {
        "surface": "choose",
        "romaji": "choose",
        "meaning": "to choose; to select; to pick (out)",
        "pos": "noun"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "空白",
        "skip": true
      },
      {
        "surface": "to",
        "romaji": "to",
        "meaning": "door (esp. Japanese-style)",
        "pos": "noun"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "空白",
        "skip": true
      },
      {
        "surface": "say",
        "romaji": "say",
        "meaning": "say; well; um; er",
        "pos": "noun"
      }
    ],
    "translation": "'Cause today I choose to say"
  },
  {
    "id": "l30",
    "start": 169.86,
    "end": 173.51,
    "tokens": [
      {
        "surface": "\"",
        "romaji": "\"",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "noun"
      },
      {
        "surface": "I",
        "romaji": "I",
        "meaning": "1st (in a sequence denoted by the iroha system); a; i",
        "pos": "noun"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "空白",
        "skip": true
      },
      {
        "surface": "will",
        "romaji": "will",
        "meaning": "will; volition; intention; intent; determination",
        "pos": "noun"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "空白",
        "skip": true
      },
      {
        "surface": "love",
        "romaji": "love",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "noun"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "空白",
        "skip": true
      },
      {
        "surface": "again",
        "romaji": "again",
        "meaning": "again; once more; once again; another time; some other time",
        "pos": "noun"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "空白",
        "skip": true
      },
      {
        "surface": "someday",
        "romaji": "someday",
        "meaning": "before very long; soon; someday; one of these days; sooner or later",
        "pos": "noun"
      },
      {
        "surface": "\"",
        "romaji": "\"",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "noun"
      }
    ],
    "translation": "\"I will love again someday\""
  },
  {
    "id": "l31",
    "start": 173.51,
    "end": 177.19,
    "tokens": [
      {
        "surface": "So",
        "romaji": "So",
        "meaning": "Soviet Union",
        "pos": "noun"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "空白",
        "skip": true
      },
      {
        "surface": "I",
        "romaji": "I",
        "meaning": "1st (in a sequence denoted by the iroha system); a; i",
        "pos": "noun"
      },
      {
        "surface": "'",
        "romaji": "'",
        "meaning": "some nerve (as in \"you have some nerve to ...\")",
        "pos": "noun"
      },
      {
        "surface": "m",
        "romaji": "m",
        "meaning": "morning; a.m.",
        "pos": "noun"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "空白",
        "skip": true
      },
      {
        "surface": "not",
        "romaji": "not",
        "meaning": "not exceeding ...; not more than ...; ... and under; ... and below; ... or fewer",
        "pos": "noun"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "空白",
        "skip": true
      },
      {
        "surface": "gonna",
        "romaji": "gonna",
        "meaning": "You're Gonna Make Me Lonesome When You Go",
        "pos": "noun"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "空白",
        "skip": true
      },
      {
        "surface": "stay",
        "romaji": "stay",
        "meaning": "stay; sojourn",
        "pos": "noun"
      }
    ],
    "translation": "So I'm not gonna stay"
  },
  {
    "id": "l32",
    "start": 177.19,
    "end": 179.53,
    "tokens": [
      {
        "surface": "Paralyzed",
        "romaji": "Paralyzed",
        "meaning": "to be petrified; to be unable to move; to be paralyzed (with horror); to be stupefied (with amazement)",
        "pos": "noun"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "空白",
        "skip": true
      },
      {
        "surface": "'",
        "romaji": "'",
        "meaning": "some nerve (as in \"you have some nerve to ...\")",
        "pos": "noun"
      },
      {
        "surface": "cause",
        "romaji": "cause",
        "meaning": "cause; origin; source",
        "pos": "noun"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "空白",
        "skip": true
      },
      {
        "surface": "I",
        "romaji": "I",
        "meaning": "1st (in a sequence denoted by the iroha system); a; i",
        "pos": "noun"
      },
      {
        "surface": "'",
        "romaji": "'",
        "meaning": "some nerve (as in \"you have some nerve to ...\")",
        "pos": "noun"
      },
      {
        "surface": "m",
        "romaji": "m",
        "meaning": "morning; a.m.",
        "pos": "noun"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "空白",
        "skip": true
      },
      {
        "surface": "not",
        "romaji": "not",
        "meaning": "not exceeding ...; not more than ...; ... and under; ... and below; ... or fewer",
        "pos": "noun"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "空白",
        "skip": true
      },
      {
        "surface": "by",
        "romaji": "by",
        "meaning": "with; by; by means of",
        "pos": "noun"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "空白",
        "skip": true
      },
      {
        "surface": "your",
        "romaji": "your",
        "meaning": "your house; your home; your family",
        "pos": "noun"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "空白",
        "skip": true
      },
      {
        "surface": "side",
        "romaji": "side",
        "meaning": "zigzag-shaped paper streamer often used to adorn Shinto-related objects",
        "pos": "noun"
      }
    ],
    "translation": "Paralyzed 'cause I'm not by your side"
  },
  {
    "id": "l33",
    "start": 179.53,
    "end": 186.42,
    "tokens": [
      {
        "surface": "But",
        "romaji": "But",
        "meaning": "Butterfly (Koda Kumi song)",
        "pos": "noun"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "空白",
        "skip": true
      },
      {
        "surface": "I",
        "romaji": "I",
        "meaning": "1st (in a sequence denoted by the iroha system); a; i",
        "pos": "noun"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "空白",
        "skip": true
      },
      {
        "surface": "believe",
        "romaji": "believe",
        "meaning": "to believe; to believe in; to place trust in; to confide in; to have faith in",
        "pos": "noun"
      },
      {
        "surface": ",",
        "romaji": ",",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "noun"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "空白",
        "skip": true
      },
      {
        "surface": "that",
        "romaji": "that",
        "meaning": "that; that thing",
        "pos": "noun"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "空白",
        "skip": true
      },
      {
        "surface": "I",
        "romaji": "I",
        "meaning": "1st (in a sequence denoted by the iroha system); a; i",
        "pos": "noun"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "空白",
        "skip": true
      },
      {
        "surface": "will",
        "romaji": "will",
        "meaning": "will; volition; intention; intent; determination",
        "pos": "noun"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "空白",
        "skip": true
      },
      {
        "surface": "be",
        "romaji": "be",
        "meaning": "word used at sentence-end (like a particle) to indicate speculation, volition or invitation",
        "pos": "noun"
      },
      {
        "surface": ",",
        "romaji": ",",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "noun"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "空白",
        "skip": true
      },
      {
        "surface": "much",
        "romaji": "much",
        "meaning": "probably; likely; perhaps; maybe",
        "pos": "noun"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "空白",
        "skip": true
      },
      {
        "surface": "better",
        "romaji": "better",
        "meaning": "better; preferable; less objectionable; least-worst",
        "pos": "noun"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "空白",
        "skip": true
      },
      {
        "surface": "eventually",
        "romaji": "eventually",
        "meaning": "before very long; soon; someday; one of these days; sooner or later",
        "pos": "noun"
      }
    ],
    "translation": "But I believe, that I will be, much better eventually"
  },
  {
    "id": "l34",
    "start": 186.42,
    "end": 194.87,
    "tokens": [
      {
        "surface": "But",
        "romaji": "But",
        "meaning": "Butterfly (Koda Kumi song)",
        "pos": "noun"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "空白",
        "skip": true
      },
      {
        "surface": "I",
        "romaji": "I",
        "meaning": "1st (in a sequence denoted by the iroha system); a; i",
        "pos": "noun"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "空白",
        "skip": true
      },
      {
        "surface": "won",
        "romaji": "won",
        "meaning": "won (currency of North Korea and South Korea)",
        "pos": "noun"
      },
      {
        "surface": "'",
        "romaji": "'",
        "meaning": "some nerve (as in \"you have some nerve to ...\")",
        "pos": "noun"
      },
      {
        "surface": "t",
        "romaji": "t",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "noun"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "空白",
        "skip": true
      },
      {
        "surface": "forget",
        "romaji": "forget",
        "meaning": "to forget; to leave carelessly; to be forgetful of; to forget about; to forget (an article)",
        "pos": "noun"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "空白",
        "skip": true
      },
      {
        "surface": "our",
        "romaji": "our",
        "meaning": "my; our; one's own",
        "pos": "noun"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "空白",
        "skip": true
      },
      {
        "surface": "love",
        "romaji": "love",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "noun"
      },
      {
        "surface": ",",
        "romaji": ",",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "noun"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "空白",
        "skip": true
      },
      {
        "surface": "ever",
        "romaji": "ever",
        "meaning": "(not) ever; (not) by any means; (not) in the least; (not) in any way; (not) at all",
        "pos": "noun"
      }
    ],
    "translation": "But I won't forget our love, ever"
  },
  {
    "id": "l35",
    "start": 194.87,
    "end": 208.42,
    "tokens": [
      {
        "surface": "Time",
        "romaji": "Time",
        "meaning": "Time (Arashi album)",
        "pos": "noun"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "空白",
        "skip": true
      },
      {
        "surface": "heals",
        "romaji": "heals",
        "meaning": "time will cure all; time heals all wounds",
        "pos": "noun"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "空白",
        "skip": true
      },
      {
        "surface": "all",
        "romaji": "all",
        "meaning": "all; entire; whole; altogether",
        "pos": "noun"
      },
      {
        "surface": ",",
        "romaji": ",",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "noun"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "空白",
        "skip": true
      },
      {
        "surface": "know",
        "romaji": "know",
        "meaning": "to know; to be aware (of); to be acquainted (with)",
        "pos": "noun"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "空白",
        "skip": true
      },
      {
        "surface": "that",
        "romaji": "that",
        "meaning": "that; that thing",
        "pos": "noun"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "空白",
        "skip": true
      },
      {
        "surface": "time",
        "romaji": "time",
        "meaning": "bloodshot eyes",
        "pos": "noun"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "空白",
        "skip": true
      },
      {
        "surface": "heals",
        "romaji": "heals",
        "meaning": "time will cure all; time heals all wounds",
        "pos": "noun"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "空白",
        "skip": true
      },
      {
        "surface": "all",
        "romaji": "all",
        "meaning": "all; entire; whole; altogether",
        "pos": "noun"
      }
    ],
    "translation": "Time heals all, know that time heals all"
  },
  {
    "id": "l36",
    "start": 208.42,
    "end": 212.13,
    "tokens": [
      {
        "surface": "I",
        "romaji": "I",
        "meaning": "1st (in a sequence denoted by the iroha system); a; i",
        "pos": "noun"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "空白",
        "skip": true
      },
      {
        "surface": "believe",
        "romaji": "believe",
        "meaning": "to believe; to believe in; to place trust in; to confide in; to have faith in",
        "pos": "noun"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "空白",
        "skip": true
      },
      {
        "surface": "that",
        "romaji": "that",
        "meaning": "that; that thing",
        "pos": "noun"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "空白",
        "skip": true
      },
      {
        "surface": "someday",
        "romaji": "someday",
        "meaning": "before very long; soon; someday; one of these days; sooner or later",
        "pos": "noun"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "空白",
        "skip": true
      },
      {
        "surface": "soon",
        "romaji": "soon",
        "meaning": "soon; shortly; before long; in a short time; in a little while",
        "pos": "noun"
      }
    ],
    "translation": "I believe that someday soon"
  },
  {
    "id": "l37",
    "start": 212.13,
    "end": 216.84,
    "tokens": [
      {
        "surface": "I",
        "romaji": "I",
        "meaning": "1st (in a sequence denoted by the iroha system); a; i",
        "pos": "noun"
      },
      {
        "surface": "'",
        "romaji": "'",
        "meaning": "some nerve (as in \"you have some nerve to ...\")",
        "pos": "noun"
      },
      {
        "surface": "ll",
        "romaji": "ll",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "noun"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "空白",
        "skip": true
      },
      {
        "surface": "remember",
        "romaji": "remember",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "noun"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "空白",
        "skip": true
      },
      {
        "surface": "you",
        "romaji": "you",
        "meaning": "appearing ...; looking ...",
        "pos": "noun"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "空白",
        "skip": true
      },
      {
        "surface": "with",
        "romaji": "with",
        "meaning": "together; jointly",
        "pos": "noun"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "空白",
        "skip": true
      },
      {
        "surface": "a",
        "romaji": "a",
        "meaning": "sub-; second-rate; inferior",
        "pos": "noun"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "空白",
        "skip": true
      },
      {
        "surface": "smile",
        "romaji": "smile",
        "meaning": "smile",
        "pos": "noun"
      }
    ],
    "translation": "I'll remember you with a smile"
  },
  {
    "id": "l38",
    "start": 216.84,
    "end": 218.73,
    "tokens": [
      {
        "surface": "And",
        "romaji": "And",
        "meaning": "Android (operating system)",
        "pos": "noun"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "空白",
        "skip": true
      },
      {
        "surface": "overcome",
        "romaji": "overcome",
        "meaning": "to push aside; to overcome (e.g. difficulties); to reject",
        "pos": "noun"
      }
    ],
    "translation": "And overcome"
  },
  {
    "id": "l39",
    "start": 218.73,
    "end": 225.29,
    "tokens": [
      {
        "surface": "And",
        "romaji": "And",
        "meaning": "Android (operating system)",
        "pos": "noun"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "空白",
        "skip": true
      },
      {
        "surface": "I",
        "romaji": "I",
        "meaning": "1st (in a sequence denoted by the iroha system); a; i",
        "pos": "noun"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "空白",
        "skip": true
      },
      {
        "surface": "will",
        "romaji": "will",
        "meaning": "will; volition; intention; intent; determination",
        "pos": "noun"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "空白",
        "skip": true
      },
      {
        "surface": "overcome",
        "romaji": "overcome",
        "meaning": "to push aside; to overcome (e.g. difficulties); to reject",
        "pos": "noun"
      }
    ],
    "translation": "And I will overcome"
  },
  {
    "id": "l40",
    "start": 225.29,
    "end": 228.69,
    "tokens": [
      {
        "surface": "Someday",
        "romaji": "Someday",
        "meaning": "Someday (Mariah Carey song)",
        "pos": "noun"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "空白",
        "skip": true
      },
      {
        "surface": "soon",
        "romaji": "soon",
        "meaning": "soon; shortly; before long; in a short time; in a little while",
        "pos": "noun"
      },
      {
        "surface": ",",
        "romaji": ",",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "noun"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "空白",
        "skip": true
      },
      {
        "surface": "I",
        "romaji": "I",
        "meaning": "1st (in a sequence denoted by the iroha system); a; i",
        "pos": "noun"
      },
      {
        "surface": "'",
        "romaji": "'",
        "meaning": "some nerve (as in \"you have some nerve to ...\")",
        "pos": "noun"
      },
      {
        "surface": "ll",
        "romaji": "ll",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "noun"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "空白",
        "skip": true
      },
      {
        "surface": "overcome",
        "romaji": "overcome",
        "meaning": "to push aside; to overcome (e.g. difficulties); to reject",
        "pos": "noun"
      }
    ],
    "translation": "Someday soon, I'll overcome"
  },
  {
    "id": "l41",
    "start": 228.69,
    "end": 234.59,
    "tokens": [
      {
        "surface": "Someday",
        "romaji": "Someday",
        "meaning": "Someday (Mariah Carey song)",
        "pos": "noun"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "空白",
        "skip": true
      },
      {
        "surface": "soon",
        "romaji": "soon",
        "meaning": "soon; shortly; before long; in a short time; in a little while",
        "pos": "noun"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "空白",
        "skip": true
      },
      {
        "surface": "I",
        "romaji": "I",
        "meaning": "1st (in a sequence denoted by the iroha system); a; i",
        "pos": "noun"
      },
      {
        "surface": "'",
        "romaji": "'",
        "meaning": "some nerve (as in \"you have some nerve to ...\")",
        "pos": "noun"
      },
      {
        "surface": "ll",
        "romaji": "ll",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "noun"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "空白",
        "skip": true
      },
      {
        "surface": "over",
        "romaji": "over",
        "meaning": "above; over; up",
        "pos": "noun"
      },
      {
        "surface": ",",
        "romaji": ",",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "noun"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "空白",
        "skip": true
      },
      {
        "surface": "over",
        "romaji": "over",
        "meaning": "above; over; up",
        "pos": "noun"
      },
      {
        "surface": "-",
        "romaji": "-",
        "meaning": "long-vowel mark",
        "pos": "noun"
      },
      {
        "surface": "come",
        "romaji": "come",
        "meaning": "come (on); come now; come along; here",
        "pos": "noun"
      }
    ],
    "translation": "Someday soon I'll over, over-come"
  },
  {
    "id": "l42",
    "start": 234.59,
    "end": 236.86,
    "tokens": [
      {
        "surface": "I",
        "romaji": "I",
        "meaning": "1st (in a sequence denoted by the iroha system); a; i",
        "pos": "noun"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "空白",
        "skip": true
      },
      {
        "surface": "choose",
        "romaji": "choose",
        "meaning": "to choose; to select; to pick (out)",
        "pos": "noun"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "空白",
        "skip": true
      },
      {
        "surface": "to",
        "romaji": "to",
        "meaning": "door (esp. Japanese-style)",
        "pos": "noun"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "空白",
        "skip": true
      },
      {
        "surface": "say",
        "romaji": "say",
        "meaning": "say; well; um; er",
        "pos": "noun"
      }
    ],
    "translation": "I choose to say"
  },
  {
    "id": "l43",
    "start": 236.86,
    "end": 241.66,
    "tokens": [
      {
        "surface": "\"",
        "romaji": "\"",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "noun"
      },
      {
        "surface": "I",
        "romaji": "I",
        "meaning": "1st (in a sequence denoted by the iroha system); a; i",
        "pos": "noun"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "空白",
        "skip": true
      },
      {
        "surface": "will",
        "romaji": "will",
        "meaning": "will; volition; intention; intent; determination",
        "pos": "noun"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "空白",
        "skip": true
      },
      {
        "surface": "love",
        "romaji": "love",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "noun"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "空白",
        "skip": true
      },
      {
        "surface": "again",
        "romaji": "again",
        "meaning": "again; once more; once again; another time; some other time",
        "pos": "noun"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "空白",
        "skip": true
      },
      {
        "surface": "someday",
        "romaji": "someday",
        "meaning": "before very long; soon; someday; one of these days; sooner or later",
        "pos": "noun"
      },
      {
        "surface": ",",
        "romaji": ",",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "noun"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "空白",
        "skip": true
      },
      {
        "surface": "again",
        "romaji": "again",
        "meaning": "again; once more; once again; another time; some other time",
        "pos": "noun"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "空白",
        "skip": true
      },
      {
        "surface": "someday",
        "romaji": "someday",
        "meaning": "before very long; soon; someday; one of these days; sooner or later",
        "pos": "noun"
      },
      {
        "surface": "\"",
        "romaji": "\"",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "noun"
      }
    ],
    "translation": "\"I will love again someday, again someday\""
  },
  {
    "id": "l44",
    "start": 241.66,
    "end": 245.66,
    "tokens": [
      {
        "surface": "I",
        "romaji": "I",
        "meaning": "1st (in a sequence denoted by the iroha system); a; i",
        "pos": "noun"
      },
      {
        "surface": "'",
        "romaji": "'",
        "meaning": "some nerve (as in \"you have some nerve to ...\")",
        "pos": "noun"
      },
      {
        "surface": "ll",
        "romaji": "ll",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "noun"
      },
      {
        "surface": " ",
        "romaji": " ",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "空白",
        "skip": true
      },
      {
        "surface": "overcome",
        "romaji": "overcome",
        "meaning": "to push aside; to overcome (e.g. difficulties); to reject",
        "pos": "noun"
      }
    ],
    "translation": "I'll overcome"
  }
];
