// Auto-generated by scripts/annotate-lyrics.mjs — review before use.
// Meanings are rough dictionary-form glosses from Jisho, not verified
// translations. Kuromoji can mis-segment ambiguous phrases. Read through
// this and fix anything that's wrong before wiring it into data/tracks.ts.
import { LyricLine } from "@/lib/types";

export const testDemoLyrics: LyricLine[] = [
  {
    "id": "l1",
    "start": 0,
    "end": 3,
    "tokens": [
      {
        "surface": "今日",
        "romaji": "kyou",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "noun"
      },
      {
        "surface": "は",
        "romaji": "wa",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "particle"
      },
      {
        "surface": "いい",
        "romaji": "ii",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "adjective"
      },
      {
        "surface": "天気",
        "romaji": "tenki",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "noun"
      },
      {
        "surface": "です",
        "romaji": "desu",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "auxiliary verb"
      },
      {
        "surface": "ね",
        "romaji": "ne",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "particle"
      }
    ]
  },
  {
    "id": "l2",
    "start": 3,
    "end": 6,
    "tokens": [
      {
        "surface": "友達",
        "romaji": "tomodachi",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "noun"
      },
      {
        "surface": "と",
        "romaji": "to",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "particle"
      },
      {
        "surface": "公園",
        "romaji": "kouen",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "noun"
      },
      {
        "surface": "へ",
        "romaji": "e",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "particle"
      },
      {
        "surface": "行き",
        "romaji": "iki",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "verb"
      },
      {
        "surface": "ます",
        "romaji": "masu",
        "meaning": "(no dictionary match — fill in manually)",
        "pos": "auxiliary verb"
      }
    ]
  }
];
