#!/usr/bin/env node
/**
 * One-step version of fetch-lyrics.mjs + tokenize-lyrics.mjs: fetches
 * synced lyrics for a track from LRCLIB (via your local /api/lyrics route),
 * then immediately tokenizes each line with kuromoji (segmentation),
 * wanakana (romaji), and Jisho (dictionary meanings).
 *
 * Still requires the Next.js dev server to be running (npm run dev), since
 * this calls your local /api/lyrics route rather than LRCLIB directly.
 *
 * Usage:
 *   node scripts/import-lyrics.mjs "<track name>" "<artist name>" [output-id]
 *
 * Example:
 *   node scripts/import-lyrics.mjs "Mirage" "Creepy Nuts" mirage
 *
 * [output-id] is optional — it defaults to a slugified version of the track
 * name, so "Mirage" already becomes "mirage" on its own. Pass a third
 * argument only when you want a different id (e.g. the track name has
 * characters you don't want in a filename, or you want it to match an id
 * you've already used in data/tracks.ts).
 */

import { writeFile, mkdir } from "node:fs/promises";
import path from "node:path";
import kuromoji from "kuromoji";
import * as wanakana from "wanakana";

const [, , trackName, artistName, outputIdArg] = process.argv;

if (!trackName || !artistName) {
  console.error('Usage: node scripts/import-lyrics.mjs "<track>" "<artist>" [output-id]');
  process.exit(1);
}

const outputId = outputIdArg || slugify(trackName);
const devServerUrl = process.env.DEV_SERVER_URL || "http://localhost:3000";
const DICT_PATH = path.join(process.cwd(), "node_modules", "kuromoji", "dict");
const JISHO_DELAY_MS = 250; // be polite to Jisho's free public API
const meaningCache = new Map();

async function main() {
  // --- Step 1: fetch synced lyrics from LRCLIB via the local API route ---
  const url = `${devServerUrl}/api/lyrics?track=${encodeURIComponent(
    trackName
  )}&artist=${encodeURIComponent(artistName)}`;

  console.log(`Fetching from ${url} ...`);
  const res = await fetch(url);

  const contentType = res.headers.get("content-type") || "";
  if (!contentType.includes("application/json")) {
    const body = await res.text();
    console.error(
      `Expected JSON from ${url} but got "${contentType || "unknown content-type"}" ` +
        `(HTTP ${res.status}). This usually means:\n` +
        `  - the dev server isn't running (start it with \`npm run dev\` in another terminal), or\n` +
        `  - something else is already running on port 3000, or\n` +
        `  - the route hit an uncaught error — check the terminal running \`npm run dev\` for a stack trace.\n\n` +
        `First 300 characters of the response body:\n${body.slice(0, 300)}`
    );
    process.exit(1);
  }

  const data = await res.json();
  if (!res.ok) {
    console.error(`Request failed: ${data.error || res.statusText}`);
    process.exit(1);
  }

  if (!data.syncedLyrics) {
    console.error(
      "LRCLIB has no line-synced lyrics for that track/artist. Try a slightly " +
        "different spelling, or check https://lrclib.net directly."
    );
    process.exit(1);
  }

  const rawLines = parseLrc(data.syncedLyrics);

  const outDir = path.join(process.cwd(), "data", "imports");
  await mkdir(outDir, { recursive: true });

  // Keep the raw, untokenized timestamps around too — useful if you ever
  // want to check the fetch step independently of the tokenizing step.
  await writeFile(
    path.join(outDir, `${outputId}.json`),
    JSON.stringify(
      { id: outputId, title: data.trackName, artist: data.artistName, lines: rawLines },
      null,
      2
    ),
    "utf-8"
  );

  // --- Step 2: tokenize each line with kuromoji + wanakana + Jisho ---
  console.log("Loading kuromoji dictionary (first run only, ~a few seconds)...");
  const tokenizer = await buildTokenizer();

  const outLines = [];
  for (let i = 0; i < rawLines.length; i++) {
    const line = rawLines[i];
    console.log(`Tokenizing line ${i + 1}/${rawLines.length} ...`);
    const tokens = await tokenizeLine(tokenizer, line.text);
    outLines.push({ id: line.id, start: line.start, end: line.end, tokens });
  }

  const jsonOutPath = path.join(outDir, `${outputId}.tokens.json`);
  await writeFile(jsonOutPath, JSON.stringify(outLines, null, 2), "utf-8");

  const tsOutPath = path.join(outDir, `${outputId}.lyrics.generated.ts`);
  const tsContents = [
    `import { LyricLine } from "@/lib/types";`,
    ``,
    `// Auto-generated by scripts/import-lyrics.mjs for "${trackName}" by ${artistName}.`,
    `// Words come from kuromoji (segmentation), wanakana (romaji), and Jisho`,
    `// (dictionary meanings) — spot-check before shipping, don't trust blindly.`,
    `export const generatedLyrics: LyricLine[] = ${JSON.stringify(outLines, null, 2)};`,
    ``,
  ].join("\n");
  await writeFile(tsOutPath, tsContents, "utf-8");

  console.log(`\nWrote:`);
  console.log(`  data/imports/${outputId}.json (raw timestamps)`);
  console.log(`  data/imports/${outputId}.tokens.json`);
  console.log(`  data/imports/${outputId}.lyrics.generated.ts`);
  console.log(
    `\nNext: in data/tracks.ts, import { generatedLyrics } from "./imports/${outputId}.lyrics.generated" ` +
      `and set that track's \`lyrics: generatedLyrics\`. Then read through it — the meanings are dictionary ` +
      `lookups, not verified against how the word's actually used in the song.`
  );
}

/** Parses basic (non-enhanced) LRC text into [{ id, start, end, text }]. */
function parseLrc(lrcText) {
  const lineRe = /^\[(\d+):(\d+(?:\.\d+)?)\](.*)$/;
  const parsed = [];

  for (const rawLine of lrcText.split("\n")) {
    const m = rawLine.match(lineRe);
    if (!m) continue;
    const [, minutes, seconds, text] = m;
    const time = Number(minutes) * 60 + Number(seconds);
    const trimmed = text.trim();
    if (!trimmed) continue;
    parsed.push({ start: time, text: trimmed });
  }

  return parsed.map((line, i) => ({
    id: `l${i + 1}`,
    start: round2(line.start),
    end: round2(parsed[i + 1] ? parsed[i + 1].start : line.start + 4),
    text: line.text,
  }));
}

function buildTokenizer() {
  return new Promise((resolve, reject) => {
    kuromoji.builder({ dicPath: DICT_PATH }).build((err, tokenizer) => {
      if (err) reject(err);
      else resolve(tokenizer);
    });
  });
}

async function tokenizeLine(tokenizer, text) {
  const kuromojiTokens = tokenizer.tokenize(text);
  const tokens = [];

  for (const t of kuromojiTokens) {
    const isSymbol = t.pos === "記号"; // punctuation/symbols

    if (isSymbol) {
      tokens.push({ surface: t.surface_form, romaji: "", meaning: "", skip: true });
      continue;
    }

    const reading = t.reading && t.reading !== "*" ? t.reading : t.surface_form;
    const romaji = wanakana.toRomaji(reading);
    const lookupWord = t.basic_form && t.basic_form !== "*" ? t.basic_form : t.surface_form;
    const meaning = await lookupMeaning(lookupWord);

    tokens.push({
      surface: t.surface_form,
      romaji,
      meaning,
      pos: mapPos(t.pos, t.pos_detail_1),
    });
  }

  return tokens;
}

/** Maps kuromoji's Japanese POS tags to the simple English ones tracks.ts uses. */
function mapPos(pos, detail) {
  switch (pos) {
    case "名詞":
      return "noun";
    case "動詞":
      return "verb";
    case "形容詞":
      return "adjective";
    case "副詞":
      return "adverb";
    case "助詞":
      return "particle";
    case "助動詞":
      return "auxiliary verb";
    case "連体詞":
      return "adjectival";
    case "接続詞":
      return "conjunction";
    case "感動詞":
      return "interjection";
    default:
      return detail && detail !== "*" ? detail : pos;
  }
}

async function lookupMeaning(word) {
  if (meaningCache.has(word)) return meaningCache.get(word);

  let meaning = "";
  try {
    const res = await fetch(
      `https://jisho.org/api/v1/search/words?keyword=${encodeURIComponent(word)}`
    );
    if (res.ok) {
      const data = await res.json();
      const senses = data?.data?.[0]?.senses;
      if (senses && senses.length > 0) {
        meaning = senses[0].english_definitions?.join("; ") ?? "";
      }
    }
  } catch {
    // network hiccup — leave meaning blank rather than crash the whole run
  }

  if (!meaning) meaning = "(no dictionary match — fill in manually)";

  meaningCache.set(word, meaning);
  await new Promise((r) => setTimeout(r, JISHO_DELAY_MS));
  return meaning;
}

function round2(n) {
  return Math.round(n * 100) / 100;
}

function slugify(str) {
  return str
    .toLowerCase()
    .normalize("NFKD")
    .replace(/[^\w\s-]/g, "")
    .trim()
    .replace(/\s+/g, "-");
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
