#!/usr/bin/env node
/**
 * Takes a skeleton file written by fetch-lyrics.mjs (data/imports/<id>.json,
 * one raw `text` line per entry) and produces a fully tokenized version:
 * each line's text is split into words with kuromoji (a Japanese
 * morphological analyzer), romanized with wanakana, and glossed with
 * definitions from Jisho's public dictionary API.
 *
 * This only looks up ordinary dictionary words — it has no idea about the
 * song itself, so treat the output as a first draft: check it against the
 * actual lines, especially for particles doing something idiomatic, verb
 * conjugations, or words with several unrelated meanings (homographs).
 *
 * Usage:
 *   node scripts/tokenize-lyrics.mjs data/imports/mirage.json
 *
 * Writes:
 *   data/imports/mirage.tokens.json         (plain data, for inspection)
 *   data/imports/mirage.lyrics.generated.ts (import straight into tracks.ts)
 */

import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import kuromoji from "kuromoji";
import * as wanakana from "wanakana";

const [, , inputPathArg] = process.argv;

if (!inputPathArg) {
  console.error("Usage: node scripts/tokenize-lyrics.mjs data/imports/<id>.json");
  process.exit(1);
}

const DICT_PATH = path.join(process.cwd(), "node_modules", "kuromoji", "dict");
const JISHO_DELAY_MS = 250; // be polite to Jisho's free public API
const meaningCache = new Map();

async function main() {
  const inputPath = path.resolve(inputPathArg);
  const raw = JSON.parse(await readFile(inputPath, "utf-8"));

  if (!Array.isArray(raw.lines)) {
    console.error(`Expected ${inputPath} to have a "lines" array (from fetch-lyrics.mjs).`);
    process.exit(1);
  }

  console.log("Loading kuromoji dictionary (first run only, ~a few seconds)...");
  const tokenizer = await buildTokenizer();

  const outLines = [];
  for (let i = 0; i < raw.lines.length; i++) {
    const line = raw.lines[i];
    console.log(`Tokenizing line ${i + 1}/${raw.lines.length} ...`);
    const tokens = await tokenizeLine(tokenizer, line.text);
    outLines.push({
      id: line.id || `l${i + 1}`,
      start: line.start,
      end: line.end,
      tokens,
    });
  }

  const outDir = path.dirname(inputPath);
  const baseName = path.basename(inputPath, ".json");

  const jsonOutPath = path.join(outDir, `${baseName}.tokens.json`);
  await writeFile(jsonOutPath, JSON.stringify(outLines, null, 2), "utf-8");

  const tsOutPath = path.join(outDir, `${baseName}.lyrics.generated.ts`);
  const tsContents = [
    `import { LyricLine } from "@/lib/types";`,
    ``,
    `// Auto-generated by scripts/tokenize-lyrics.mjs from ${path.basename(inputPath)}.`,
    `// Words come from kuromoji (segmentation), wanakana (romaji), and Jisho`,
    `// (dictionary meanings) — spot-check before shipping, don't trust blindly.`,
    `export const generatedLyrics: LyricLine[] = ${JSON.stringify(outLines, null, 2)};`,
    ``,
  ].join("\n");
  await writeFile(tsOutPath, tsContents, "utf-8");

  console.log(`\nWrote:`);
  console.log(`  ${path.relative(process.cwd(), jsonOutPath)}`);
  console.log(`  ${path.relative(process.cwd(), tsOutPath)}`);
  console.log(
    `\nNext: in data/tracks.ts, import { generatedLyrics } from "./imports/${baseName}.lyrics.generated" ` +
      `and set that track's \`lyrics: generatedLyrics\`. Then read through it — the meanings are dictionary ` +
      `lookups, not verified against how the word's actually used in the song.`
  );
}

function buildTokenizer() {
  return new Promise((resolve, reject) => {
    kuromoji.builder({ dicPath: DICT_PATH }).build((err, tokenizer) => {
      if (err) reject(err);
      else resolve(tokenizer);
    });
  });
}

async function tokenizeLine(tokenizer, text) {
  const kuromojiTokens = tokenizer.tokenize(text);
  const tokens = [];

  for (const t of kuromojiTokens) {
    const isSymbol = t.pos === "記号"; // punctuation/symbols

    if (isSymbol) {
      tokens.push({ surface: t.surface_form, romaji: "", meaning: "", skip: true });
      continue;
    }

    const reading = t.reading && t.reading !== "*" ? t.reading : t.surface_form;
    const romaji = wanakana.toRomaji(reading);
    const lookupWord =
      t.basic_form && t.basic_form !== "*" ? t.basic_form : t.surface_form;

    const meaning = await lookupMeaning(lookupWord);

    tokens.push({
      surface: t.surface_form,
      romaji,
      meaning,
      pos: mapPos(t.pos, t.pos_detail_1),
    });
  }

  return tokens;
}

/** Maps kuromoji's Japanese POS tags to the simple English ones tracks.ts uses. */
function mapPos(pos, detail) {
  switch (pos) {
    case "名詞":
      return "noun";
    case "動詞":
      return "verb";
    case "形容詞":
      return "adjective";
    case "副詞":
      return "adverb";
    case "助詞":
      return "particle";
    case "助動詞":
      return "auxiliary verb";
    case "連体詞":
      return "adjectival";
    case "接続詞":
      return "conjunction";
    case "感動詞":
      return "interjection";
    default:
      return detail && detail !== "*" ? detail : pos;
  }
}

async function lookupMeaning(word) {
  if (meaningCache.has(word)) return meaningCache.get(word);

  let meaning = "";
  try {
    const res = await fetch(
      `https://jisho.org/api/v1/search/words?keyword=${encodeURIComponent(word)}`
    );
    if (res.ok) {
      const data = await res.json();
      const senses = data?.data?.[0]?.senses;
      if (senses && senses.length > 0) {
        meaning = senses[0].english_definitions?.join("; ") ?? "";
      }
    }
  } catch {
    // network hiccup — leave meaning blank rather than crash the whole run
  }

  if (!meaning) meaning = "(no dictionary match — fill in manually)";

  meaningCache.set(word, meaning);
  await new Promise((r) => setTimeout(r, JISHO_DELAY_MS));
  return meaning;
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
